/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Ejecutivo_Vinculacion_Frames;

/**
 *
 * @author suare
 */
public class EditarPoliza extends javax.swing.JFrame {

    /**
     * Creates new form EditarPoliza
     */
    public EditarPoliza() {
        initComponents();
        this.setSize(525, 600); // Fuerza el tamaño exacto
        this.setLocationRelativeTo(null); // Centra la ventana en tu monitor
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        JBNGuardarCliente = new javax.swing.JButton();
        lblLogoInicio = new javax.swing.JLabel();
        JBNCancelar = new javax.swing.JButton();
        JTFNumPoliza = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        JTFDireccion = new javax.swing.JTextField();
        JTFTelefono = new javax.swing.JTextField();
        JTFCorreo = new javax.swing.JTextField();
        JTFEmpresa = new javax.swing.JTextField();
        JBNGuardar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Montserrat", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 102, 102));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Editar Poliza");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 20, 240, -1));

        JBNGuardarCliente.setBackground(new java.awt.Color(0, 153, 102));
        JBNGuardarCliente.setFont(new java.awt.Font("Montserrat", 1, 14)); // NOI18N
        JBNGuardarCliente.setForeground(new java.awt.Color(255, 255, 255));
        JBNGuardarCliente.setText("Buscar");
        JBNGuardarCliente.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        JBNGuardarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBNGuardarClienteActionPerformed(evt);
            }
        });
        getContentPane().add(JBNGuardarCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, 120, 40));

        lblLogoInicio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Logo ETS 75 px.png"))); // NOI18N
        getContentPane().add(lblLogoInicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 480, -1, -1));

        JBNCancelar.setFont(new java.awt.Font("Montserrat", 1, 14)); // NOI18N
        JBNCancelar.setText("Cancelar");
        JBNCancelar.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        JBNCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBNCancelarActionPerformed(evt);
            }
        });
        getContentPane().add(JBNCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 510, 90, 30));

        JTFNumPoliza.setForeground(new java.awt.Color(153, 153, 153));
        JTFNumPoliza.setText("                         Número de póliza");
        JTFNumPoliza.setPreferredSize(new java.awt.Dimension(350, 40));
        JTFNumPoliza.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTFNumPolizaActionPerformed(evt);
            }
        });
        getContentPane().add(JTFNumPoliza, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 90, 280, -1));

        jLabel3.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(153, 153, 153));
        jLabel3.setText("Dirección");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 240, 90, 40));

        jLabel4.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(153, 153, 153));
        jLabel4.setText("Telefono");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 310, 80, 40));

        jLabel5.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(153, 153, 153));
        jLabel5.setText("Correo");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 380, 90, 40));

        jLabel2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(153, 153, 153));
        jLabel2.setText("Empresa");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 170, 90, 40));

        JTFDireccion.setForeground(new java.awt.Color(153, 153, 153));
        JTFDireccion.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        JTFDireccion.setText("Direccíon");
        JTFDireccion.setPreferredSize(new java.awt.Dimension(350, 40));
        JTFDireccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTFDireccionActionPerformed(evt);
            }
        });
        getContentPane().add(JTFDireccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 240, 340, -1));

        JTFTelefono.setForeground(new java.awt.Color(153, 153, 153));
        JTFTelefono.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        JTFTelefono.setText("Teléfono");
        JTFTelefono.setPreferredSize(new java.awt.Dimension(350, 40));
        JTFTelefono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTFTelefonoActionPerformed(evt);
            }
        });
        getContentPane().add(JTFTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 310, 340, -1));

        JTFCorreo.setForeground(new java.awt.Color(153, 153, 153));
        JTFCorreo.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        JTFCorreo.setText("Correo electrónico");
        JTFCorreo.setPreferredSize(new java.awt.Dimension(350, 40));
        JTFCorreo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTFCorreoActionPerformed(evt);
            }
        });
        getContentPane().add(JTFCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 380, 340, -1));

        JTFEmpresa.setForeground(new java.awt.Color(153, 153, 153));
        JTFEmpresa.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        JTFEmpresa.setText("Nombre (s)");
        JTFEmpresa.setMinimumSize(new java.awt.Dimension(66, 28));
        JTFEmpresa.setPreferredSize(new java.awt.Dimension(350, 40));
        JTFEmpresa.setRequestFocusEnabled(false);
        JTFEmpresa.setVerifyInputWhenFocusTarget(false);
        JTFEmpresa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTFEmpresaActionPerformed(evt);
            }
        });
        getContentPane().add(JTFEmpresa, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 170, 340, -1));

        JBNGuardar.setBackground(new java.awt.Color(0, 153, 102));
        JBNGuardar.setFont(new java.awt.Font("Montserrat", 1, 14)); // NOI18N
        JBNGuardar.setForeground(new java.awt.Color(255, 255, 255));
        JBNGuardar.setText("Guardar");
        JBNGuardar.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        JBNGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBNGuardarActionPerformed(evt);
            }
        });
        getContentPane().add(JBNGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 460, 224, 42));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JBNGuardarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBNGuardarClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JBNGuardarClienteActionPerformed

    private void JBNCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBNCancelarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JBNCancelarActionPerformed

    private void JTFDireccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTFDireccionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JTFDireccionActionPerformed

    private void JTFTelefonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTFTelefonoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JTFTelefonoActionPerformed

    private void JTFCorreoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTFCorreoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JTFCorreoActionPerformed

    private void JTFEmpresaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTFEmpresaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JTFEmpresaActionPerformed

    private void JBNGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBNGuardarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JBNGuardarActionPerformed

    private void JTFNumPolizaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTFNumPolizaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JTFNumPolizaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EditarPoliza.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EditarPoliza.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EditarPoliza.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EditarPoliza.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EditarPoliza().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton JBNCancelar;
    public javax.swing.JButton JBNGuardar;
    public javax.swing.JButton JBNGuardarCliente;
    public javax.swing.JTextField JTFCorreo;
    public javax.swing.JTextField JTFDireccion;
    public javax.swing.JTextField JTFEmpresa;
    public javax.swing.JTextField JTFNumPoliza;
    public javax.swing.JTextField JTFTelefono;
    public javax.swing.JLabel jLabel1;
    public javax.swing.JLabel jLabel2;
    public javax.swing.JLabel jLabel3;
    public javax.swing.JLabel jLabel4;
    public javax.swing.JLabel jLabel5;
    public javax.swing.JLabel lblLogoInicio;
    // End of variables declaration//GEN-END:variables
}
