/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Ejecutivo_Vinculacion_Frames;

/**
 *
 * @author suare
 */
public class EditarPoliza extends javax.swing.JFrame {

    /**
     * Creates new form EditarPoliza
     */
    public EditarPoliza() {
        initComponents();
        this.setSize(700, 650); // Fuerza el tamaño exacto
        this.setResizable(false);
        this.setLocationRelativeTo(null); // Centra la ventana en tu monitor
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JPFondo = new ImagenPanel_EV("/imagenes/FondoETS.jpg");
        jLabel1 = new javax.swing.JLabel();
        JBNGuardarCliente = new javax.swing.JButton();
        lblLogoInicio = new javax.swing.JLabel();
        JBNCancelar = new javax.swing.JButton();
        JTFNumPoliza = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        JTFDireccion = new javax.swing.JTextField();
        JTFTelefono = new javax.swing.JTextField();
        JTFCorreo = new javax.swing.JTextField();
        JTFEmpresa = new javax.swing.JTextField();
        JBNGuardar = new javax.swing.JButton();
        JLBBusqueda = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator1 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        JPFondo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Montserrat", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 102, 102));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Editar Poliza");
        JPFondo.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 680, 40));

        JBNGuardarCliente.setBackground(new java.awt.Color(0, 153, 102));
        JBNGuardarCliente.setFont(new java.awt.Font("Montserrat", 1, 14)); // NOI18N
        JBNGuardarCliente.setForeground(new java.awt.Color(255, 255, 255));
        JBNGuardarCliente.setText("Buscar");
        JBNGuardarCliente.setBorder(null);
        JBNGuardarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBNGuardarClienteActionPerformed(evt);
            }
        });
        JPFondo.add(JBNGuardarCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 100, 120, 40));

        lblLogoInicio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Logo ETS 75 px.png"))); // NOI18N
        JPFondo.add(lblLogoInicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 530, -1, -1));

        JBNCancelar.setFont(new java.awt.Font("Montserrat", 1, 14)); // NOI18N
        JBNCancelar.setText("Cancelar");
        JBNCancelar.setBorder(null);
        JBNCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBNCancelarActionPerformed(evt);
            }
        });
        JPFondo.add(JBNCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 560, 90, 30));

        JTFNumPoliza.setForeground(new java.awt.Color(102, 102, 102));
        JTFNumPoliza.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        JTFNumPoliza.setText("Número de póliza");
        JTFNumPoliza.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(200, 200, 200), 1, true));
        JTFNumPoliza.setMargin(new java.awt.Insets(5, 10, 5, 10));
        JTFNumPoliza.setPreferredSize(new java.awt.Dimension(350, 40));
        JTFNumPoliza.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                JTFNumPolizaFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                JTFNumPolizaFocusLost(evt);
            }
        });
        JTFNumPoliza.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTFNumPolizaActionPerformed(evt);
            }
        });
        JPFondo.add(JTFNumPoliza, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, 480, 40));

        jLabel3.setFont(new java.awt.Font("Montserrat", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(102, 102, 102));
        jLabel3.setText("Dirección");
        JPFondo.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 280, 90, 40));

        jLabel4.setFont(new java.awt.Font("Montserrat", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(102, 102, 102));
        jLabel4.setText("Telefono");
        JPFondo.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 350, 80, 40));

        jLabel5.setFont(new java.awt.Font("Montserrat", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(102, 102, 102));
        jLabel5.setText("Correo");
        JPFondo.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 420, 90, 40));

        jLabel2.setFont(new java.awt.Font("Montserrat", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(102, 102, 102));
        jLabel2.setText("Empresa");
        JPFondo.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 210, 100, 40));

        JTFDireccion.setForeground(new java.awt.Color(102, 102, 102));
        JTFDireccion.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        JTFDireccion.setText("Direccíon");
        JTFDireccion.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(200, 200, 200), 1, true));
        JTFDireccion.setMargin(new java.awt.Insets(5, 10, 5, 10));
        JTFDireccion.setPreferredSize(new java.awt.Dimension(350, 40));
        JTFDireccion.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                JTFDireccionFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                JTFDireccionFocusLost(evt);
            }
        });
        JTFDireccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTFDireccionActionPerformed(evt);
            }
        });
        JTFDireccion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                JTFDireccionKeyTyped(evt);
            }
        });
        JPFondo.add(JTFDireccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 280, 520, -1));

        JTFTelefono.setForeground(new java.awt.Color(102, 102, 102));
        JTFTelefono.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        JTFTelefono.setText("Teléfono");
        JTFTelefono.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(200, 200, 200), 1, true));
        JTFTelefono.setMargin(new java.awt.Insets(5, 10, 5, 10));
        JTFTelefono.setPreferredSize(new java.awt.Dimension(350, 40));
        JTFTelefono.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                JTFTelefonoFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                JTFTelefonoFocusLost(evt);
            }
        });
        JTFTelefono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTFTelefonoActionPerformed(evt);
            }
        });
        JTFTelefono.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                JTFTelefonoKeyTyped(evt);
            }
        });
        JPFondo.add(JTFTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 350, 520, -1));

        JTFCorreo.setForeground(new java.awt.Color(102, 102, 102));
        JTFCorreo.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        JTFCorreo.setText("Correo electrónico");
        JTFCorreo.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(200, 200, 200), 1, true));
        JTFCorreo.setMargin(new java.awt.Insets(5, 10, 5, 10));
        JTFCorreo.setPreferredSize(new java.awt.Dimension(350, 40));
        JTFCorreo.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                JTFCorreoFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                JTFCorreoFocusLost(evt);
            }
        });
        JTFCorreo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTFCorreoActionPerformed(evt);
            }
        });
        JTFCorreo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                JTFCorreoKeyTyped(evt);
            }
        });
        JPFondo.add(JTFCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 420, 520, -1));

        JTFEmpresa.setForeground(new java.awt.Color(102, 102, 102));
        JTFEmpresa.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        JTFEmpresa.setText("Nombre (s)");
        JTFEmpresa.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(200, 200, 200), 1, true));
        JTFEmpresa.setMargin(new java.awt.Insets(5, 10, 5, 10));
        JTFEmpresa.setMinimumSize(new java.awt.Dimension(66, 28));
        JTFEmpresa.setPreferredSize(new java.awt.Dimension(350, 40));
        JTFEmpresa.setRequestFocusEnabled(false);
        JTFEmpresa.setVerifyInputWhenFocusTarget(false);
        JTFEmpresa.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                JTFEmpresaFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                JTFEmpresaFocusLost(evt);
            }
        });
        JTFEmpresa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTFEmpresaActionPerformed(evt);
            }
        });
        JTFEmpresa.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                JTFEmpresaKeyTyped(evt);
            }
        });
        JPFondo.add(JTFEmpresa, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 210, 520, -1));

        JBNGuardar.setBackground(new java.awt.Color(0, 153, 102));
        JBNGuardar.setFont(new java.awt.Font("Montserrat", 1, 14)); // NOI18N
        JBNGuardar.setForeground(new java.awt.Color(255, 255, 255));
        JBNGuardar.setText("Guardar");
        JBNGuardar.setBorder(null);
        JBNGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBNGuardarActionPerformed(evt);
            }
        });
        JPFondo.add(JBNGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 520, 224, 42));

        JLBBusqueda.setFont(new java.awt.Font("Montserrat", 1, 14)); // NOI18N
        JLBBusqueda.setForeground(new java.awt.Color(102, 102, 102));
        JLBBusqueda.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        JLBBusqueda.setText("Busqueda de Póliza por Numero");
        JPFondo.add(JLBBusqueda, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, 250, 40));

        jSeparator2.setAlignmentX(1.0F);
        jSeparator2.setAlignmentY(1.0F);
        JPFondo.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 70, 410, 10));

        jSeparator3.setAlignmentX(1.0F);
        jSeparator3.setAlignmentY(1.0F);
        JPFondo.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 30, 10));

        jSeparator1.setAlignmentX(1.0F);
        jSeparator1.setAlignmentY(1.0F);
        JPFondo.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 160, 690, 10));

        getContentPane().add(JPFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 690, 620));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JBNGuardarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBNGuardarClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JBNGuardarClienteActionPerformed

    private void JBNCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBNCancelarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JBNCancelarActionPerformed

    private void JTFDireccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTFDireccionActionPerformed
        // TODO add your handling code here:
        JTFDireccion.addActionListener(e -> JTFTelefono.requestFocus());

    }//GEN-LAST:event_JTFDireccionActionPerformed

    private void JTFTelefonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTFTelefonoActionPerformed
        // TODO add your handling code here:
        JTFTelefono.addActionListener(e -> JTFCorreo.requestFocus());

    }//GEN-LAST:event_JTFTelefonoActionPerformed

    private void JTFCorreoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTFCorreoActionPerformed
        // TODO add your handling code here:
        JTFCorreo.addActionListener(e -> JBNGuardar.doClick());

    }//GEN-LAST:event_JTFCorreoActionPerformed

    private void JTFEmpresaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTFEmpresaActionPerformed
        // TODO add your handling code here:
        JTFEmpresa.addActionListener(e -> JTFDireccion.requestFocus());
    }//GEN-LAST:event_JTFEmpresaActionPerformed

    private void JBNGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBNGuardarActionPerformed
        // TODO add your handling code here:
        String correo = JTFCorreo.getText().trim();
        String tel = JTFTelefono.getText().trim();

        if (tel.length() < 10) {
            javax.swing.JOptionPane.showMessageDialog(this, "El teléfono debe tener 10 dígitos.", "Error de formato", javax.swing.JOptionPane.ERROR_MESSAGE);

        } else if (!correo.contains("@") || !correo.contains(".")) {
            javax.swing.JOptionPane.showMessageDialog(this, "Error de formato, asegurate que el correo contenga '@' y un dominio.", "Correo inválido", javax.swing.JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_JBNGuardarActionPerformed

    private void JTFNumPolizaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTFNumPolizaActionPerformed
        // TODO add your handling code here:
        JTFNumPoliza.addActionListener(e -> JBNGuardarCliente.doClick());
    }//GEN-LAST:event_JTFNumPolizaActionPerformed

    private void JTFEmpresaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_JTFEmpresaFocusGained
        // TODO add your handling code here:
        if (JTFEmpresa.getText().equals("Empresa")) {
            JTFEmpresa.setText("");
            JTFEmpresa.setForeground(new java.awt.Color(255, 255, 255));
        }
    }//GEN-LAST:event_JTFEmpresaFocusGained

    private void JTFEmpresaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_JTFEmpresaFocusLost
        // TODO add your handling code here:
        if (JTFEmpresa.getText().isEmpty()) {
            JTFEmpresa.setText("Empresa");
            JTFEmpresa.setForeground(new java.awt.Color(153, 153, 153));
        }
    }//GEN-LAST:event_JTFEmpresaFocusLost

    private void JTFDireccionFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_JTFDireccionFocusGained
        // TODO add your handling code here:
        if (JTFDireccion.getText().equals("Dirección")) {
            JTFDireccion.setText("");
            JTFDireccion.setForeground(new java.awt.Color(255, 255, 255));
        }
    }//GEN-LAST:event_JTFDireccionFocusGained

    private void JTFDireccionFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_JTFDireccionFocusLost
        // TODO add your handling code here:
        if (JTFDireccion.getText().isEmpty()) {
            JTFDireccion.setText("Dirección");
            JTFDireccion.setForeground(new java.awt.Color(153, 153, 153));
        }
    }//GEN-LAST:event_JTFDireccionFocusLost

    private void JTFTelefonoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_JTFTelefonoFocusGained
        // TODO add your handling code here:
        if (JTFTelefono.getText().equals("Telefono")) {
            JTFTelefono.setText("");
            JTFTelefono.setForeground(new java.awt.Color(255, 255, 255));
        }
    }//GEN-LAST:event_JTFTelefonoFocusGained

    private void JTFTelefonoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_JTFTelefonoFocusLost
        // TODO add your handling code here:
        if (JTFTelefono.getText().isEmpty()) {
            JTFTelefono.setText("Telefono");
            JTFTelefono.setForeground(new java.awt.Color(153, 153, 153));
        }
    }//GEN-LAST:event_JTFTelefonoFocusLost

    private void JTFCorreoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_JTFCorreoFocusGained
        // TODO add your handling code here:
        if (JTFCorreo.getText().equals("Correo")) {
            JTFCorreo.setText("");
            JTFCorreo.setForeground(new java.awt.Color(255, 255, 255));
        }
    }//GEN-LAST:event_JTFCorreoFocusGained

    private void JTFCorreoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_JTFCorreoFocusLost
        // TODO add your handling code here:
        if (JTFCorreo.getText().isEmpty()) {
            JTFCorreo.setText("Correo");
            JTFCorreo.setForeground(new java.awt.Color(153, 153, 153));
        }
    }//GEN-LAST:event_JTFCorreoFocusLost

    private void JTFEmpresaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_JTFEmpresaKeyTyped
        // TODO add your handling code here:
        if (((javax.swing.JTextField) evt.getSource()).getText().length() >= 100) {
            evt.consume();
        }
    }//GEN-LAST:event_JTFEmpresaKeyTyped

    private void JTFDireccionKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_JTFDireccionKeyTyped
        // TODO add your handling code here:
        if (((javax.swing.JTextField) evt.getSource()).getText().length() >= 100) {
            evt.consume();
        }
    }//GEN-LAST:event_JTFDireccionKeyTyped

    private void JTFTelefonoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_JTFTelefonoKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if (!Character.isDigit(c) || JTFTelefono.getText().length() >= 10) {
            evt.consume();
        }
    }//GEN-LAST:event_JTFTelefonoKeyTyped

    private void JTFCorreoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_JTFCorreoKeyTyped
        // TODO add your handling code here:
        if (((javax.swing.JTextField) evt.getSource()).getText().length() >= 50) {
            evt.consume();
        }
    }//GEN-LAST:event_JTFCorreoKeyTyped

    private void JTFNumPolizaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_JTFNumPolizaFocusGained
        // TODO add your handling code here:
        if (JTFNumPoliza.getText().equals("Número de póliza")) {
            JTFNumPoliza.setText("");
            JTFNumPoliza.setForeground(new java.awt.Color(205, 205, 205));
        }
    }//GEN-LAST:event_JTFNumPolizaFocusGained

    private void JTFNumPolizaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_JTFNumPolizaFocusLost
        // TODO add your handling code here:
        if (JTFNumPoliza.getText().isEmpty()) {
            JTFNumPoliza.setText("Número de póliza");
            JTFNumPoliza.setForeground(new java.awt.Color(153, 153, 153));
        }
    }//GEN-LAST:event_JTFNumPolizaFocusLost

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EditarPoliza.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EditarPoliza.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EditarPoliza.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EditarPoliza.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EditarPoliza().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton JBNCancelar;
    public javax.swing.JButton JBNGuardar;
    public javax.swing.JButton JBNGuardarCliente;
    public javax.swing.JLabel JLBBusqueda;
    private javax.swing.JPanel JPFondo;
    public javax.swing.JTextField JTFCorreo;
    public javax.swing.JTextField JTFDireccion;
    public javax.swing.JTextField JTFEmpresa;
    public javax.swing.JTextField JTFNumPoliza;
    public javax.swing.JTextField JTFTelefono;
    public javax.swing.JLabel jLabel1;
    public javax.swing.JLabel jLabel2;
    public javax.swing.JLabel jLabel3;
    public javax.swing.JLabel jLabel4;
    public javax.swing.JLabel jLabel5;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    public javax.swing.JLabel lblLogoInicio;
    // End of variables declaration//GEN-END:variables
}
