/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Ejecutivo_Vinculacion_Frames;

/**
 *
 * @author Alejandro
 */
public class MenuEjecutivoVinculacion2 extends javax.swing.JFrame {

    /**
     * Creates new form MenuEjecutivoVinculacion2
     */
    public MenuEjecutivoVinculacion2() {
        initComponents();
        this.setSize(450, 380); // Fuerza el tamaño exacto
        this.setLocationRelativeTo(null); // Centra la ventana en tu monitor
        JMBEjecutivoVinculacion.add(javax.swing.Box.createHorizontalGlue(), 3);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JLBBienvenido = new javax.swing.JLabel();
        JLBEjecutivoVinculacion = new javax.swing.JLabel();
        JBNNuevaPoliza = new javax.swing.JButton();
        JBNNuevoCliente = new javax.swing.JButton();
        JLBLogo = new javax.swing.JLabel();
        JMBEjecutivoVinculacion = new javax.swing.JMenuBar();
        JMNClientes = new javax.swing.JMenu();
        JMINuevoCliente = new javax.swing.JMenuItem();
        JMIModificarCliente = new javax.swing.JMenuItem();
        JMNPolizas = new javax.swing.JMenu();
        JMINuevaPoliza = new javax.swing.JMenuItem();
        JMIEditarPoliza = new javax.swing.JMenuItem();
        JMIRenovarPoliza = new javax.swing.JMenuItem();
        JMICancelarPoliza = new javax.swing.JMenuItem();
        JMNUsuarios = new javax.swing.JMenu();
        JMINuevoUsuario = new javax.swing.JMenuItem();
        JMIEditarUsuario = new javax.swing.JMenuItem();
        JMNCerrarSesion = new javax.swing.JMenu();
        JMICerrarSesion = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        JLBBienvenido.setFont(new java.awt.Font("Montserrat", 1, 24)); // NOI18N
        JLBBienvenido.setForeground(new java.awt.Color(153, 153, 153));
        JLBBienvenido.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        JLBBienvenido.setText("¡Bienvenido!");

        JLBEjecutivoVinculacion.setFont(new java.awt.Font("Montserrat", 1, 24)); // NOI18N
        JLBEjecutivoVinculacion.setForeground(new java.awt.Color(153, 153, 153));
        JLBEjecutivoVinculacion.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        JLBEjecutivoVinculacion.setText("Ejecutivo de Vinculación");

        JBNNuevaPoliza.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos90/nuevapoliza90.png"))); // NOI18N
        JBNNuevaPoliza.setToolTipText("");

        JBNNuevoCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos90/nuevocliente90.png"))); // NOI18N

        JMBEjecutivoVinculacion.setFont(new java.awt.Font("Montserrat", 0, 12)); // NOI18N

        JMNClientes.setText("Clientes");

        JMINuevoCliente.setText("Nuevo Cliente");
        JMNClientes.add(JMINuevoCliente);

        JMIModificarCliente.setText("Modificar Cliente");
        JMNClientes.add(JMIModificarCliente);

        JMBEjecutivoVinculacion.add(JMNClientes);

        JMNPolizas.setText("Polizas");

        JMINuevaPoliza.setText("Nueva poliza");
        JMNPolizas.add(JMINuevaPoliza);

        JMIEditarPoliza.setText("Modificar Poliza");
        JMNPolizas.add(JMIEditarPoliza);

        JMIRenovarPoliza.setText("Renovar Poliza");
        JMNPolizas.add(JMIRenovarPoliza);

        JMICancelarPoliza.setText("Cancelar Poliza");
        JMNPolizas.add(JMICancelarPoliza);

        JMBEjecutivoVinculacion.add(JMNPolizas);

        JMNUsuarios.setText("Usuarios");

        JMINuevoUsuario.setText("Nuevo usuario");
        JMINuevoUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JMINuevoUsuarioActionPerformed(evt);
            }
        });
        JMNUsuarios.add(JMINuevoUsuario);

        JMIEditarUsuario.setText("Editar Usuario");
        JMNUsuarios.add(JMIEditarUsuario);

        JMBEjecutivoVinculacion.add(JMNUsuarios);

        JMNCerrarSesion.setText("Cerrar Sesión");
        JMNCerrarSesion.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);

        JMICerrarSesion.setText("Salir");
        JMNCerrarSesion.add(JMICerrarSesion);

        JMBEjecutivoVinculacion.add(JMNCerrarSesion);

        setJMenuBar(JMBEjecutivoVinculacion);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(105, 105, 105)
                        .addComponent(JBNNuevoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(50, 50, 50)
                        .addComponent(JBNNuevaPoliza, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(64, 64, 64)
                        .addComponent(JLBEjecutivoVinculacion, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(JLBLogo))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(99, 99, 99)
                        .addComponent(JLBBienvenido, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(65, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(JLBBienvenido)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(JLBEjecutivoVinculacion)
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(JBNNuevoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JBNNuevaPoliza, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 78, Short.MAX_VALUE)
                .addComponent(JLBLogo)
                .addGap(17, 17, 17))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JMINuevoUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JMINuevoUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JMINuevoUsuarioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuEjecutivoVinculacion2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuEjecutivoVinculacion2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuEjecutivoVinculacion2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuEjecutivoVinculacion2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                MenuEjecutivoVinculacion2 vista = new MenuEjecutivoVinculacion2();
                new Ejecutivo_Vinculacion_Controladores.ControladorMenuEjecutivo(vista);
                vista.setVisible(true);
            }
        });
    }
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton JBNNuevaPoliza;
    public javax.swing.JButton JBNNuevoCliente;
    private javax.swing.JLabel JLBBienvenido;
    private javax.swing.JLabel JLBEjecutivoVinculacion;
    private javax.swing.JLabel JLBLogo;
    private javax.swing.JMenuBar JMBEjecutivoVinculacion;
    public javax.swing.JMenuItem JMICancelarPoliza;
    public javax.swing.JMenuItem JMICerrarSesion;
    public javax.swing.JMenuItem JMIEditarPoliza;
    public javax.swing.JMenuItem JMIEditarUsuario;
    public javax.swing.JMenuItem JMIModificarCliente;
    public javax.swing.JMenuItem JMINuevaPoliza;
    public javax.swing.JMenuItem JMINuevoCliente;
    public javax.swing.JMenuItem JMINuevoUsuario;
    public javax.swing.JMenuItem JMIRenovarPoliza;
    public javax.swing.JMenu JMNCerrarSesion;
    public javax.swing.JMenu JMNClientes;
    public javax.swing.JMenu JMNPolizas;
    private javax.swing.JMenu JMNUsuarios;
    // End of variables declaration//GEN-END:variables
}
