/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Ejecutivo_Vinculacion_Frames;

/**
 *
 * @author Alejandro
 */
public class MenuEjecutivoVinculacion2 extends javax.swing.JFrame {

    /**
     * Creates new form MenuEjecutivoVinculacion2
     */
    public MenuEjecutivoVinculacion2() {
        initComponents();
        this.setSize(800, 600); // Fuerza el tamaño exacto
        this.setResizable(false);
        this.setLocationRelativeTo(null); // Centra la ventana en tu monitor
        JMBEjecutivoVinculacion.add(javax.swing.Box.createHorizontalGlue(), 3);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JPFondo = new ImagenPanel_EV("/imagenes/FondoETS.jpg");
        jLabel1 = new javax.swing.JLabel();
        JLBBienvenido = new javax.swing.JLabel();
        JLBEjecutivoVinculacion = new javax.swing.JLabel();
        JBNNuevaPoliza = new javax.swing.JButton();
        JBNNuevoCliente = new javax.swing.JButton();
        JLBLogo = new javax.swing.JLabel();
        JMBEjecutivoVinculacion = new javax.swing.JMenuBar();
        JMNClientes = new javax.swing.JMenu();
        JMINuevoCliente = new javax.swing.JMenuItem();
        JMIModificarCliente = new javax.swing.JMenuItem();
        JMNPolizas = new javax.swing.JMenu();
        JMINuevaPoliza = new javax.swing.JMenuItem();
        JMIEditarPoliza = new javax.swing.JMenuItem();
        JMIRenovarPoliza = new javax.swing.JMenuItem();
        JMICancelarPoliza = new javax.swing.JMenuItem();
        JMNUsuarios = new javax.swing.JMenu();
        JMINuevoUsuario = new javax.swing.JMenuItem();
        JMIEditarUsuario = new javax.swing.JMenuItem();
        JMNCerrarSesion = new javax.swing.JMenu();
        JMICerrarSesion = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        JPFondo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Logo ETS 75 px.png"))); // NOI18N
        JPFondo.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, 80));

        JLBBienvenido.setFont(new java.awt.Font("Montserrat", 1, 48)); // NOI18N
        JLBBienvenido.setForeground(new java.awt.Color(102, 102, 102));
        JLBBienvenido.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        JLBBienvenido.setText("¡Bienvenido!");
        JPFondo.add(JLBBienvenido, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 780, 60));

        JLBEjecutivoVinculacion.setFont(new java.awt.Font("Montserrat", 1, 48)); // NOI18N
        JLBEjecutivoVinculacion.setForeground(new java.awt.Color(102, 102, 102));
        JLBEjecutivoVinculacion.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        JLBEjecutivoVinculacion.setText("Ejecutivo de Vinculación");
        JPFondo.add(JLBEjecutivoVinculacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 130, 780, 60));

        JBNNuevaPoliza.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos90/nuevapoliza90.png"))); // NOI18N
        JBNNuevaPoliza.setToolTipText("");
        JPFondo.add(JBNNuevaPoliza, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 250, 140, 150));

        JBNNuevoCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos90/nuevocliente90.png"))); // NOI18N
        JPFondo.add(JBNNuevoCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 250, 140, 150));
        JPFondo.add(JLBLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 500, -1, -1));

        getContentPane().add(JPFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 810, 540));

        JMBEjecutivoVinculacion.setFont(new java.awt.Font("Montserrat", 0, 12)); // NOI18N

        JMNClientes.setText("Clientes");

        JMINuevoCliente.setText("Nuevo Cliente");
        JMNClientes.add(JMINuevoCliente);

        JMIModificarCliente.setText("Modificar Cliente");
        JMNClientes.add(JMIModificarCliente);

        JMBEjecutivoVinculacion.add(JMNClientes);

        JMNPolizas.setText("Polizas");

        JMINuevaPoliza.setText("Nueva poliza");
        JMNPolizas.add(JMINuevaPoliza);

        JMIEditarPoliza.setText("Modificar Poliza");
        JMNPolizas.add(JMIEditarPoliza);

        JMIRenovarPoliza.setText("Renovar Poliza");
        JMNPolizas.add(JMIRenovarPoliza);

        JMICancelarPoliza.setText("Cancelar Poliza");
        JMNPolizas.add(JMICancelarPoliza);

        JMBEjecutivoVinculacion.add(JMNPolizas);

        JMNUsuarios.setText("Usuarios");

        JMINuevoUsuario.setText("Nuevo usuario");
        JMINuevoUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JMINuevoUsuarioActionPerformed(evt);
            }
        });
        JMNUsuarios.add(JMINuevoUsuario);

        JMIEditarUsuario.setText("Editar Usuario");
        JMNUsuarios.add(JMIEditarUsuario);

        JMBEjecutivoVinculacion.add(JMNUsuarios);

        JMNCerrarSesion.setText("Cerrar Sesión");
        JMNCerrarSesion.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);

        JMICerrarSesion.setText("Salir");
        JMNCerrarSesion.add(JMICerrarSesion);

        JMBEjecutivoVinculacion.add(JMNCerrarSesion);

        setJMenuBar(JMBEjecutivoVinculacion);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JMINuevoUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JMINuevoUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JMINuevoUsuarioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuEjecutivoVinculacion2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuEjecutivoVinculacion2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuEjecutivoVinculacion2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuEjecutivoVinculacion2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                MenuEjecutivoVinculacion2 vista = new MenuEjecutivoVinculacion2();
                new Ejecutivo_Vinculacion_Controladores.ControladorMenuEjecutivo(vista);
                vista.setVisible(true);
            }
        });
    }
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton JBNNuevaPoliza;
    public javax.swing.JButton JBNNuevoCliente;
    private javax.swing.JLabel JLBBienvenido;
    private javax.swing.JLabel JLBEjecutivoVinculacion;
    private javax.swing.JLabel JLBLogo;
    private javax.swing.JMenuBar JMBEjecutivoVinculacion;
    public javax.swing.JMenuItem JMICancelarPoliza;
    public javax.swing.JMenuItem JMICerrarSesion;
    public javax.swing.JMenuItem JMIEditarPoliza;
    public javax.swing.JMenuItem JMIEditarUsuario;
    public javax.swing.JMenuItem JMIModificarCliente;
    public javax.swing.JMenuItem JMINuevaPoliza;
    public javax.swing.JMenuItem JMINuevoCliente;
    public javax.swing.JMenuItem JMINuevoUsuario;
    public javax.swing.JMenuItem JMIRenovarPoliza;
    public javax.swing.JMenu JMNCerrarSesion;
    public javax.swing.JMenu JMNClientes;
    public javax.swing.JMenu JMNPolizas;
    private javax.swing.JMenu JMNUsuarios;
    private javax.swing.JPanel JPFondo;
    public javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
