/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Ejecutivo_Vinculacion_Frames;

/**
 *
 * @author suare
 */
public class ModificarUsuario extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(ModificarUsuario.class.getName());

    /**
     * Creates new form ModificarUsuario
     */
    public ModificarUsuario() {
        initComponents();
                this.setSize(525, 600); // Fuerza el tamaño exacto
              this.setLocationRelativeTo(null); // Centra la ventana en tu monitor
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        JTFnombre = new javax.swing.JTextField();
        JTFapellido = new javax.swing.JTextField();
        JTFlocacion = new javax.swing.JTextField();
        JTFcorreo = new javax.swing.JTextField();
        JTFtelefono = new javax.swing.JTextField();
        JBTguardar = new javax.swing.JButton();
        JBTcancelar = new javax.swing.JButton();
        JTFcliente = new javax.swing.JTextField();
        JTFempresa = new javax.swing.JTextField();
        JCBcliente = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        JCBempresa = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Modificar Usuario");

        jLabel2.setText("Nombre ");

        jLabel3.setText("Apellido");

        jLabel4.setText("locacion");

        jLabel5.setText("Correo");

        jLabel6.setText("Telefono");

        JTFnombre.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        JTFnombre.setText("Nombre (s)");
        JTFnombre.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                JTFnombreFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                JTFnombreFocusLost(evt);
            }
        });
        JTFnombre.addActionListener(this::JTFnombreActionPerformed);
        JTFnombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                JTFnombreKeyTyped(evt);
            }
        });

        JTFapellido.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        JTFapellido.setText("Apellido (s)");
        JTFapellido.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                JTFapellidoFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                JTFapellidoFocusLost(evt);
            }
        });
        JTFapellido.addActionListener(this::JTFapellidoActionPerformed);
        JTFapellido.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                JTFapellidoKeyTyped(evt);
            }
        });

        JTFlocacion.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        JTFlocacion.setText("Locación");
        JTFlocacion.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                JTFlocacionFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                JTFlocacionFocusLost(evt);
            }
        });
        JTFlocacion.addActionListener(this::JTFlocacionActionPerformed);
        JTFlocacion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                JTFlocacionKeyTyped(evt);
            }
        });

        JTFcorreo.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        JTFcorreo.setText("Correo");
        JTFcorreo.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                JTFcorreoFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                JTFcorreoFocusLost(evt);
            }
        });
        JTFcorreo.addActionListener(this::JTFcorreoActionPerformed);
        JTFcorreo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                JTFcorreoKeyTyped(evt);
            }
        });

        JTFtelefono.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        JTFtelefono.setText("Telefono");
        JTFtelefono.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                JTFtelefonoFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                JTFtelefonoFocusLost(evt);
            }
        });
        JTFtelefono.addActionListener(this::JTFtelefonoActionPerformed);
        JTFtelefono.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                JTFtelefonoKeyTyped(evt);
            }
        });

        JBTguardar.setText("guardar");
        JBTguardar.addActionListener(this::JBTguardarActionPerformed);

        JBTcancelar.setText("cancelar");

        JTFcliente.setText("Usuario");
        JTFcliente.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                JTFclienteFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                JTFclienteFocusLost(evt);
            }
        });

        JTFempresa.setText("Empresa");
        JTFempresa.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                JTFempresaFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                JTFempresaFocusLost(evt);
            }
        });
        JTFempresa.addActionListener(this::JTFempresaActionPerformed);

        JCBcliente.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel7.setText("Usuario");

        jLabel8.setText("Empresa");

        JCBempresa.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(252, 252, 252)
                        .addComponent(JBTguardar, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel4)
                                .addComponent(jLabel3))
                            .addComponent(jLabel5)
                            .addComponent(jLabel6))
                        .addGap(50, 50, 50)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(JTFnombre)
                            .addComponent(JTFapellido)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(JTFtelefono, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(JTFlocacion, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(JTFcorreo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 120, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(91, 91, 91)
                                        .addComponent(jLabel7))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(63, 63, 63)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(JCBcliente, 0, 128, Short.MAX_VALUE)
                                            .addComponent(JTFcliente))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(31, 31, 31)
                                        .addComponent(jLabel8))
                                    .addComponent(JTFempresa)
                                    .addComponent(JCBempresa, 0, 115, Short.MAX_VALUE)))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(113, 113, 113)))
                .addComponent(JBTcancelar)
                .addGap(48, 48, 48))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(JTFcliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(JTFempresa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(JCBcliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JCBempresa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 92, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(JTFnombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(JTFapellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(JTFlocacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(JTFcorreo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(JTFtelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JBTguardar)
                    .addComponent(JBTcancelar))
                .addGap(61, 61, 61))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JTFclienteFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_JTFclienteFocusGained
        // TODO add your handling code here:
        if (JTFcliente.getText().equals("Usuario")) {
            JTFcliente.setText("");
            JTFcliente.setForeground(new java.awt.Color(205, 205, 205));
        }
    }//GEN-LAST:event_JTFclienteFocusGained

    private void JTFclienteFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_JTFclienteFocusLost
        // TODO add your handling code here:
        if (JTFcliente.getText().isEmpty()) {
            JTFcliente.setText("Usuario");
            JTFcliente.setForeground(new java.awt.Color(153, 153, 153));
        }
    }//GEN-LAST:event_JTFclienteFocusLost

    private void JTFempresaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_JTFempresaFocusGained
        // TODO add your handling code here:
        if (JTFempresa.getText().equals("Empresa")) {
            JTFempresa.setText("");
            JTFempresa.setForeground(new java.awt.Color(205, 205, 205));
        }
    }//GEN-LAST:event_JTFempresaFocusGained

    private void JTFempresaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_JTFempresaFocusLost
        // TODO add your handling code here:
        if (JTFempresa.getText().isEmpty()) {
            JTFempresa.setText("Empresa");
            JTFempresa.setForeground(new java.awt.Color(153, 153, 153));
        }
    }//GEN-LAST:event_JTFempresaFocusLost

    private void JTFapellidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTFapellidoActionPerformed
        // TODO add your handling code here:
        JTFapellido.addActionListener(e -> JTFlocacion.requestFocus());

    }//GEN-LAST:event_JTFapellidoActionPerformed

    private void JTFnombreFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_JTFnombreFocusGained
        // TODO add your handling code here:
        if (JTFnombre.getText().equals("Nombre (s)")) {
            JTFnombre.setText("");
            JTFnombre.setForeground(new java.awt.Color(205, 205, 205));
        }
    }//GEN-LAST:event_JTFnombreFocusGained

    private void JTFnombreFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_JTFnombreFocusLost
        // TODO add your handling code here:
        if (JTFnombre.getText().isEmpty()) {
            JTFnombre.setText("Nombre (s)");
            JTFnombre.setForeground(new java.awt.Color(153, 153, 153));
        }
    }//GEN-LAST:event_JTFnombreFocusLost

    private void JTFapellidoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_JTFapellidoFocusGained
        // TODO add your handling code here:
        if (JTFapellido.getText().equals("Apellido (s)")) {
            JTFapellido.setText("");
            JTFapellido.setForeground(new java.awt.Color(205, 205, 205));
        }
    }//GEN-LAST:event_JTFapellidoFocusGained

    private void JTFapellidoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_JTFapellidoFocusLost
        // TODO add your handling code here:
        if (JTFapellido.getText().isEmpty()) {
            JTFapellido.setText("Apellido (s)");
            JTFapellido.setForeground(new java.awt.Color(153, 153, 153));
        }
    }//GEN-LAST:event_JTFapellidoFocusLost

    private void JTFlocacionFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_JTFlocacionFocusGained
        // TODO add your handling code here:
        if (JTFlocacion.getText().equals("Locación")) {
            JTFlocacion.setText("");
            JTFlocacion.setForeground(new java.awt.Color(205, 205, 205));
        }
    }//GEN-LAST:event_JTFlocacionFocusGained

    private void JTFlocacionFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_JTFlocacionFocusLost
        // TODO add your handling code here:
        if (JTFlocacion.getText().isEmpty()) {
            JTFlocacion.setText("Locación");
            JTFlocacion.setForeground(new java.awt.Color(153, 153, 153));
        }
    }//GEN-LAST:event_JTFlocacionFocusLost

    private void JTFcorreoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_JTFcorreoFocusGained
        // TODO add your handling code here:
        if (JTFcorreo.getText().equals("Correo")) {
            JTFcorreo.setText("");
            JTFcorreo.setForeground(new java.awt.Color(205, 205, 205));
        }
    }//GEN-LAST:event_JTFcorreoFocusGained

    private void JTFcorreoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_JTFcorreoFocusLost
        // TODO add your handling code here:
        if (JTFcorreo.getText().isEmpty()) {
            JTFcorreo.setText("Correo");
            JTFcorreo.setForeground(new java.awt.Color(153, 153, 153));
        }
    }//GEN-LAST:event_JTFcorreoFocusLost

    private void JTFtelefonoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_JTFtelefonoFocusGained
        // TODO add your handling code here:
        if (JTFtelefono.getText().equals("Telefono")) {
            JTFtelefono.setText("");
            JTFtelefono.setForeground(new java.awt.Color(205, 205, 205));
        }
    }//GEN-LAST:event_JTFtelefonoFocusGained

    private void JTFtelefonoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_JTFtelefonoFocusLost
        // TODO add your handling code here:
        if (JTFtelefono.getText().isEmpty()) {
            JTFtelefono.setText("Telefono");
            JTFtelefono.setForeground(new java.awt.Color(153, 153, 153));
        }
    }//GEN-LAST:event_JTFtelefonoFocusLost

    private void JTFnombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTFnombreActionPerformed
        // TODO add your handling code here:
        JTFnombre.addActionListener(e -> JTFapellido.requestFocus());

    }//GEN-LAST:event_JTFnombreActionPerformed

    private void JTFlocacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTFlocacionActionPerformed
        // TODO add your handling code here:
        JTFlocacion.addActionListener(e -> JTFcorreo.requestFocus());
    }//GEN-LAST:event_JTFlocacionActionPerformed

    private void JTFcorreoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTFcorreoActionPerformed
        // TODO add your handling code here:
        JTFcorreo.addActionListener(e -> JTFtelefono.requestFocus());
    }//GEN-LAST:event_JTFcorreoActionPerformed

    private void JTFtelefonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTFtelefonoActionPerformed
        // TODO add your handling code here:
        JTFtelefono.addActionListener(e -> JBTguardar.doClick());

    }//GEN-LAST:event_JTFtelefonoActionPerformed

    private void JTFnombreKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_JTFnombreKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        javax.swing.JTextField field = (javax.swing.JTextField) evt.getSource();
        if (!(Character.isLetter(c) || c == ' ' || Character.isISOControl(c)) || field.getText().length() >= 50) {
            evt.consume();
        }
    }//GEN-LAST:event_JTFnombreKeyTyped

    private void JTFapellidoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_JTFapellidoKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        javax.swing.JTextField field = (javax.swing.JTextField) evt.getSource();
        if (!(Character.isLetter(c) || c == ' ' || Character.isISOControl(c)) || field.getText().length() >= 50) {
            evt.consume();
        }
    }//GEN-LAST:event_JTFapellidoKeyTyped

    private void JTFlocacionKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_JTFlocacionKeyTyped
        // TODO add your handling code here:
        if (((javax.swing.JTextField) evt.getSource()).getText().length() >= 100) {
            evt.consume();
        }
    }//GEN-LAST:event_JTFlocacionKeyTyped

    private void JTFcorreoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_JTFcorreoKeyTyped
        // TODO add your handling code here:
        if (((javax.swing.JTextField) evt.getSource()).getText().length() >= 100) {
            evt.consume();
        }
    }//GEN-LAST:event_JTFcorreoKeyTyped

    private void JTFtelefonoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_JTFtelefonoKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if (!Character.isDigit(c) || JTFtelefono.getText().length() >= 10) {
            evt.consume();
        }
    }//GEN-LAST:event_JTFtelefonoKeyTyped

    private void JBTguardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBTguardarActionPerformed
        // TODO add your handling code here:
        String correo = JTFcorreo.getText().trim();
        String tel = JTFtelefono.getText().trim();

        if (tel.length() < 10) {
            javax.swing.JOptionPane.showMessageDialog(this, "El teléfono debe tener 10 dígitos.", "Error de formato", javax.swing.JOptionPane.ERROR_MESSAGE);

        } else if (!correo.contains("@") || !correo.contains(".")) {
            javax.swing.JOptionPane.showMessageDialog(this, "Error de formato, asegurate que el correo contenga '@' y un dominio.", "Correo inválido", javax.swing.JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_JBTguardarActionPerformed

    private void JTFempresaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTFempresaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JTFempresaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new ModificarUsuario().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton JBTcancelar;
    public javax.swing.JButton JBTguardar;
    public javax.swing.JComboBox<String> JCBcliente;
    public javax.swing.JComboBox<String> JCBempresa;
    public javax.swing.JTextField JTFapellido;
    public javax.swing.JTextField JTFcliente;
    public javax.swing.JTextField JTFcorreo;
    public javax.swing.JTextField JTFempresa;
    public javax.swing.JTextField JTFlocacion;
    public javax.swing.JTextField JTFnombre;
    public javax.swing.JTextField JTFtelefono;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    // End of variables declaration//GEN-END:variables
}
