/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Ejecutivo_Vinculacion_Frames;

/**
 *
 * @author suare
 */
public class ModificarCliente extends javax.swing.JFrame {

    /**
     * Creates new form ModificarCliente
     */
    public ModificarCliente() {
        initComponents();
        this.setSize(525, 600); // Fuerza el tamaño exacto
        this.setLocationRelativeTo(null); // Centra la ventana en tu monitor
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JBNGuardar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        JBNCancelar = new javax.swing.JButton();
        JLBApellido = new javax.swing.JLabel();
        JLBATelefono = new javax.swing.JLabel();
        JLBCorreo = new javax.swing.JLabel();
        JLBNombre = new javax.swing.JLabel();
        JTFApellido = new javax.swing.JTextField();
        JTFTelefono = new javax.swing.JTextField();
        JTFCorreo = new javax.swing.JTextField();
        JTFnombre = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        JTFCorreoBusqueda = new javax.swing.JTextField();
        JBNBuscar = new javax.swing.JButton();
        JTFTelefonoBusqueda = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        JBNGuardar.setBackground(new java.awt.Color(0, 153, 102));
        JBNGuardar.setFont(new java.awt.Font("Montserrat", 1, 14)); // NOI18N
        JBNGuardar.setForeground(new java.awt.Color(255, 255, 255));
        JBNGuardar.setText("Guardar");
        JBNGuardar.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        JBNGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBNGuardarActionPerformed(evt);
            }
        });
        getContentPane().add(JBNGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 450, 224, 42));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Logo ETS 75 px.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 480, -1, -1));

        JBNCancelar.setFont(new java.awt.Font("Montserrat", 1, 14)); // NOI18N
        JBNCancelar.setText("Cancelar");
        JBNCancelar.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        JBNCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBNCancelarActionPerformed(evt);
            }
        });
        getContentPane().add(JBNCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 510, 90, 30));

        JLBApellido.setFont(new java.awt.Font("Montserrat", 1, 14)); // NOI18N
        JLBApellido.setForeground(new java.awt.Color(153, 153, 153));
        JLBApellido.setText("Apellido (s)");
        getContentPane().add(JLBApellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 240, 80, 40));

        JLBATelefono.setFont(new java.awt.Font("Montserrat", 1, 14)); // NOI18N
        JLBATelefono.setForeground(new java.awt.Color(153, 153, 153));
        JLBATelefono.setText("Telefono");
        getContentPane().add(JLBATelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 310, 80, 40));

        JLBCorreo.setFont(new java.awt.Font("Montserrat", 1, 14)); // NOI18N
        JLBCorreo.setForeground(new java.awt.Color(153, 153, 153));
        JLBCorreo.setText("Correo");
        getContentPane().add(JLBCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 380, 90, 40));

        JLBNombre.setFont(new java.awt.Font("Montserrat", 1, 14)); // NOI18N
        JLBNombre.setForeground(new java.awt.Color(153, 153, 153));
        JLBNombre.setText("Nombre (s)");
        getContentPane().add(JLBNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 170, 80, 40));

        JTFApellido.setForeground(new java.awt.Color(153, 153, 153));
        JTFApellido.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        JTFApellido.setText("Apellido (s)");
        JTFApellido.setMinimumSize(new java.awt.Dimension(350, 40));
        JTFApellido.setPreferredSize(new java.awt.Dimension(350, 40));
        JTFApellido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTFApellidoActionPerformed(evt);
            }
        });
        JTFApellido.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                JTFApellidoKeyTyped(evt);
            }
        });
        getContentPane().add(JTFApellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 240, 340, -1));

        JTFTelefono.setForeground(new java.awt.Color(153, 153, 153));
        JTFTelefono.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        JTFTelefono.setText("Telefono");
        JTFTelefono.setMinimumSize(new java.awt.Dimension(350, 40));
        JTFTelefono.setPreferredSize(new java.awt.Dimension(350, 40));
        JTFTelefono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTFTelefonoActionPerformed(evt);
            }
        });
        JTFTelefono.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                JTFTelefonoKeyTyped(evt);
            }
        });
        getContentPane().add(JTFTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 310, 340, -1));

        JTFCorreo.setForeground(new java.awt.Color(153, 153, 153));
        JTFCorreo.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        JTFCorreo.setText("Correo electrónico");
        JTFCorreo.setMinimumSize(new java.awt.Dimension(350, 40));
        JTFCorreo.setPreferredSize(new java.awt.Dimension(350, 40));
        JTFCorreo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTFCorreoActionPerformed(evt);
            }
        });
        JTFCorreo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                JTFCorreoKeyTyped(evt);
            }
        });
        getContentPane().add(JTFCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 380, 340, -1));

        JTFnombre.setForeground(new java.awt.Color(153, 153, 153));
        JTFnombre.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        JTFnombre.setText("Nombre (s)");
        JTFnombre.setToolTipText("");
        JTFnombre.setMinimumSize(new java.awt.Dimension(350, 40));
        JTFnombre.setPreferredSize(new java.awt.Dimension(350, 40));
        JTFnombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTFnombreActionPerformed(evt);
            }
        });
        JTFnombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                JTFnombreKeyTyped(evt);
            }
        });
        getContentPane().add(JTFnombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 170, 340, -1));

        jLabel2.setFont(new java.awt.Font("Montserrat", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(102, 102, 102));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Modificar cliente");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 20, 240, -1));

        JTFCorreoBusqueda.setForeground(new java.awt.Color(153, 153, 153));
        JTFCorreoBusqueda.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        JTFCorreoBusqueda.setText("Correo registrado");
        JTFCorreoBusqueda.setActionCommand("<Not Set>");
        JTFCorreoBusqueda.setMinimumSize(new java.awt.Dimension(350, 40));
        JTFCorreoBusqueda.setPreferredSize(new java.awt.Dimension(350, 40));
        JTFCorreoBusqueda.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                JTFCorreoBusquedaFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                JTFCorreoBusquedaFocusLost(evt);
            }
        });
        JTFCorreoBusqueda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTFCorreoBusquedaActionPerformed(evt);
            }
        });
        JTFCorreoBusqueda.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                JTFCorreoBusquedaKeyTyped(evt);
            }
        });
        getContentPane().add(JTFCorreoBusqueda, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 90, 290, 30));

        JBNBuscar.setBackground(new java.awt.Color(0, 153, 102));
        JBNBuscar.setFont(new java.awt.Font("Montserrat", 1, 14)); // NOI18N
        JBNBuscar.setForeground(new java.awt.Color(255, 255, 255));
        JBNBuscar.setText("Buscar");
        JBNBuscar.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        JBNBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBNBuscarActionPerformed(evt);
            }
        });
        getContentPane().add(JBNBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 100, 120, 40));

        JTFTelefonoBusqueda.setForeground(new java.awt.Color(102, 102, 102));
        JTFTelefonoBusqueda.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        JTFTelefonoBusqueda.setText("Telefono");
        getContentPane().add(JTFTelefonoBusqueda, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 130, 290, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JBNGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBNGuardarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JBNGuardarActionPerformed

    private void JBNCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBNCancelarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JBNCancelarActionPerformed

    private void JTFApellidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTFApellidoActionPerformed
        // TODO add your handling code here:
        JTFApellido.addActionListener(e -> JTFTelefono.requestFocus());
    }//GEN-LAST:event_JTFApellidoActionPerformed

    private void JTFTelefonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTFTelefonoActionPerformed
        // TODO add your handling code here:
        JTFTelefono.addActionListener(e -> JTFCorreo.requestFocus());
    }//GEN-LAST:event_JTFTelefonoActionPerformed

    private void JTFCorreoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTFCorreoActionPerformed
        // TODO add your handling code here:
        JTFCorreo.addActionListener(e -> JBNGuardar.doClick());
    }//GEN-LAST:event_JTFCorreoActionPerformed

    private void JTFnombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTFnombreActionPerformed
        // TODO add your handling code here:
        JTFnombre.addActionListener(e -> JTFApellido.requestFocus());
    }//GEN-LAST:event_JTFnombreActionPerformed

    private void JTFCorreoBusquedaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTFCorreoBusquedaActionPerformed
        // TODO add your handling code here:
        JTFCorreoBusqueda.addActionListener(e -> JBNBuscar.doClick());
    }//GEN-LAST:event_JTFCorreoBusquedaActionPerformed

    private void JBNBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBNBuscarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JBNBuscarActionPerformed

    private void JTFCorreoBusquedaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_JTFCorreoBusquedaFocusGained
        // TODO add your handling code here:
        if (JTFCorreoBusqueda.getText().equals("Correo registrado")) {
            JTFCorreoBusqueda.setText("");
            JTFCorreoBusqueda.setForeground(new java.awt.Color(205, 205, 205));
        }
    }//GEN-LAST:event_JTFCorreoBusquedaFocusGained

    private void JTFCorreoBusquedaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_JTFCorreoBusquedaFocusLost
        // TODO add your handling code here:
        if (JTFCorreoBusqueda.getText().isEmpty()) {
            JTFCorreoBusqueda.setText("Correo registrado");
            JTFCorreoBusqueda.setForeground(new java.awt.Color(153, 153, 153));
        }
    }//GEN-LAST:event_JTFCorreoBusquedaFocusLost

    private void JTFnombreKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_JTFnombreKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        javax.swing.JTextField field = (javax.swing.JTextField) evt.getSource();
        if (!(Character.isLetter(c) || c == ' ' || Character.isISOControl(c)) || field.getText().length() >= 50) {
            evt.consume();
        }
    }//GEN-LAST:event_JTFnombreKeyTyped

    private void JTFApellidoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_JTFApellidoKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        javax.swing.JTextField field = (javax.swing.JTextField) evt.getSource();
        if (!(Character.isLetter(c) || c == ' ' || Character.isISOControl(c)) || field.getText().length() >= 50) {
            evt.consume();
        }
    }//GEN-LAST:event_JTFApellidoKeyTyped

    private void JTFTelefonoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_JTFTelefonoKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if (!Character.isDigit(c) || JTFTelefono.getText().length() >= 10) {
            evt.consume();
        }
    }//GEN-LAST:event_JTFTelefonoKeyTyped

    private void JTFCorreoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_JTFCorreoKeyTyped
        // TODO add your handling code here:
        if (((javax.swing.JTextField) evt.getSource()).getText().length() >= 100) {
            evt.consume();
        }
    }//GEN-LAST:event_JTFCorreoKeyTyped

    private void JTFCorreoBusquedaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_JTFCorreoBusquedaKeyTyped
        // TODO add your handling code here:
        if (((javax.swing.JTextField) evt.getSource()).getText().length() >= 100) {
            evt.consume();
        }
    }//GEN-LAST:event_JTFCorreoBusquedaKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ModificarCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ModificarCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ModificarCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ModificarCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ModificarCliente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton JBNBuscar;
    public javax.swing.JButton JBNCancelar;
    public javax.swing.JButton JBNGuardar;
    public javax.swing.JLabel JLBATelefono;
    public javax.swing.JLabel JLBApellido;
    public javax.swing.JLabel JLBCorreo;
    public javax.swing.JLabel JLBNombre;
    public javax.swing.JTextField JTFApellido;
    public javax.swing.JTextField JTFCorreo;
    public javax.swing.JTextField JTFCorreoBusqueda;
    public javax.swing.JTextField JTFTelefono;
    public javax.swing.JTextField JTFTelefonoBusqueda;
    public javax.swing.JTextField JTFnombre;
    public javax.swing.JLabel jLabel1;
    public javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
