/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Ejecutivo_Vinculacion_Frames;

/**
 *
 * @author glomy
 */
public class NuevaPoliza2 extends javax.swing.JFrame {

    /**
     * Creates new form Registrar_Usuario
     */
    public NuevaPoliza2() {
        initComponents();
        this.setSize(800, 600); // Fuerza el tamaño exacto
        this.setResizable(false);
        this.setLocationRelativeTo(null); // Centra la ventana en tu monitor
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JPFondo = new ImagenPanel_EV("/imagenes/FondoETS.jpg");
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        JTFEmpresa1 = new javax.swing.JTextField();
        JTFDireccion1 = new javax.swing.JTextField();
        JTFTelefono1 = new javax.swing.JTextField();
        JTFCorreo1 = new javax.swing.JTextField();
        JCBFechaVencimiento1 = new javax.swing.JComboBox<>();
        JBNRegistrar1 = new javax.swing.JButton();
        JBNCancelar1 = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        JLBRegistrarTecnico = new javax.swing.JLabel();
        JLBNombre = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        JPFondo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setFont(new java.awt.Font("Montserrat", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(102, 102, 102));
        jLabel9.setText("Empresa");
        JPFondo.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 120, 150, 40));

        jLabel10.setFont(new java.awt.Font("Montserrat", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(102, 102, 102));
        jLabel10.setText("Dirección");
        JPFondo.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 190, 150, 40));

        jLabel11.setFont(new java.awt.Font("Montserrat", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(102, 102, 102));
        jLabel11.setText("Telefono");
        JPFondo.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 260, 150, 40));

        jLabel12.setFont(new java.awt.Font("Montserrat", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(102, 102, 102));
        jLabel12.setText("Correo");
        JPFondo.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 330, 150, 40));

        jLabel13.setFont(new java.awt.Font("Montserrat", 1, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(102, 102, 102));
        jLabel13.setText("Fecha de vencimiento");
        JPFondo.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 400, 210, 40));

        JTFEmpresa1.setForeground(new java.awt.Color(153, 153, 153));
        JTFEmpresa1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        JTFEmpresa1.setText("Empresa");
        JTFEmpresa1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(200, 200, 200), 1, true));
        JTFEmpresa1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                JTFEmpresa1FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                JTFEmpresa1FocusLost(evt);
            }
        });
        JTFEmpresa1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTFEmpresa1ActionPerformed(evt);
            }
        });
        JTFEmpresa1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                JTFEmpresa1KeyTyped(evt);
            }
        });
        JPFondo.add(JTFEmpresa1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 120, 550, 40));

        JTFDireccion1.setForeground(new java.awt.Color(153, 153, 153));
        JTFDireccion1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        JTFDireccion1.setText("Dirección");
        JTFDireccion1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(200, 200, 200), 1, true));
        JTFDireccion1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                JTFDireccion1FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                JTFDireccion1FocusLost(evt);
            }
        });
        JTFDireccion1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTFDireccion1ActionPerformed(evt);
            }
        });
        JTFDireccion1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                JTFDireccion1KeyTyped(evt);
            }
        });
        JPFondo.add(JTFDireccion1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 190, 550, 40));

        JTFTelefono1.setForeground(new java.awt.Color(153, 153, 153));
        JTFTelefono1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        JTFTelefono1.setText("Telefono");
        JTFTelefono1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(200, 200, 200), 1, true));
        JTFTelefono1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                JTFTelefono1FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                JTFTelefono1FocusLost(evt);
            }
        });
        JTFTelefono1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTFTelefono1ActionPerformed(evt);
            }
        });
        JTFTelefono1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                JTFTelefono1KeyTyped(evt);
            }
        });
        JPFondo.add(JTFTelefono1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 260, 550, 40));

        JTFCorreo1.setForeground(new java.awt.Color(153, 153, 153));
        JTFCorreo1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        JTFCorreo1.setText("Correo");
        JTFCorreo1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(200, 200, 200), 1, true));
        JTFCorreo1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                JTFCorreo1FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                JTFCorreo1FocusLost(evt);
            }
        });
        JTFCorreo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTFCorreo1ActionPerformed(evt);
            }
        });
        JTFCorreo1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                JTFCorreo1KeyTyped(evt);
            }
        });
        JPFondo.add(JTFCorreo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 330, 550, 40));

        JCBFechaVencimiento1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Fecha" }));
        JCBFechaVencimiento1.setBorder(null);
        JCBFechaVencimiento1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JCBFechaVencimiento1ActionPerformed(evt);
            }
        });
        JPFondo.add(JCBFechaVencimiento1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 400, 480, 40));

        JBNRegistrar1.setBackground(new java.awt.Color(0, 153, 102));
        JBNRegistrar1.setFont(new java.awt.Font("Montserrat", 1, 14)); // NOI18N
        JBNRegistrar1.setForeground(new java.awt.Color(255, 255, 255));
        JBNRegistrar1.setText("Registrar");
        JBNRegistrar1.setBorder(null);
        JBNRegistrar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBNRegistrar1ActionPerformed(evt);
            }
        });
        JPFondo.add(JBNRegistrar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 490, 225, 45));

        JBNCancelar1.setFont(new java.awt.Font("Montserrat", 1, 14)); // NOI18N
        JBNCancelar1.setText("Cancelar");
        JBNCancelar1.setBorder(null);
        JBNCancelar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBNCancelar1ActionPerformed(evt);
            }
        });
        JPFondo.add(JBNCancelar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 520, 100, 30));

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Logo ETS 75 px.png"))); // NOI18N
        JPFondo.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 490, -1, -1));

        JLBRegistrarTecnico.setFont(new java.awt.Font("Montserrat", 1, 24)); // NOI18N
        JLBRegistrarTecnico.setForeground(new java.awt.Color(102, 102, 102));
        JLBRegistrarTecnico.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        JLBRegistrarTecnico.setText("Nueva Póliza");
        JPFondo.add(JLBRegistrarTecnico, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 780, 40));

        JLBNombre.setFont(new java.awt.Font("Montserrat", 1, 14)); // NOI18N
        JLBNombre.setForeground(new java.awt.Color(153, 153, 153));
        JLBNombre.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        JLBNombre.setText("Ingrese los datos correspondientes para la generación de una nueva póliza");
        JPFondo.add(JLBNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 780, -1));

        getContentPane().add(JPFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 790, 570));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JTFEmpresa1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_JTFEmpresa1FocusGained
        // TODO add your handling code here:
        if (JTFEmpresa1.getText().equals("Empresa")) {
            JTFEmpresa1.setText("");
            JTFEmpresa1.setForeground(new java.awt.Color(205, 205, 205));
        }
    }//GEN-LAST:event_JTFEmpresa1FocusGained

    private void JTFEmpresa1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_JTFEmpresa1FocusLost
        // TODO add your handling code here:
        if (JTFEmpresa1.getText().isEmpty()) {
            JTFEmpresa1.setText("Empresa");
            JTFEmpresa1.setForeground(new java.awt.Color(153, 153, 153));
        }
    }//GEN-LAST:event_JTFEmpresa1FocusLost

    private void JTFEmpresa1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTFEmpresa1ActionPerformed
        // TODO add your handling code here:
        JTFEmpresa1.addActionListener(e -> JTFDireccion1.requestFocus());
    }//GEN-LAST:event_JTFEmpresa1ActionPerformed

    private void JTFEmpresa1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_JTFEmpresa1KeyTyped
        // TODO add your handling code here:
        if (((javax.swing.JTextField) evt.getSource()).getText().length() >= 100) {
            evt.consume();
        }
    }//GEN-LAST:event_JTFEmpresa1KeyTyped

    private void JTFDireccion1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_JTFDireccion1FocusGained
        // TODO add your handling code here:
        if (JTFDireccion1.getText().equals("Dirección")) {
            JTFDireccion1.setText("");
            JTFDireccion1.setForeground(new java.awt.Color(205, 205, 205));
        }
    }//GEN-LAST:event_JTFDireccion1FocusGained

    private void JTFDireccion1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_JTFDireccion1FocusLost
        // TODO add your handling code here:
        if (JTFDireccion1.getText().isEmpty()) {
            JTFDireccion1.setText("Dirección");
            JTFDireccion1.setForeground(new java.awt.Color(153, 153, 153));
        }
    }//GEN-LAST:event_JTFDireccion1FocusLost

    private void JTFDireccion1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_JTFDireccion1KeyTyped
        // TODO add your handling code here:
        if (((javax.swing.JTextField) evt.getSource()).getText().length() >= 100) {
            evt.consume();
        }
    }//GEN-LAST:event_JTFDireccion1KeyTyped

    private void JTFTelefono1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_JTFTelefono1FocusGained
        // TODO add your handling code here:
        if (JTFTelefono1.getText().equals("Telefono")) {
            JTFTelefono1.setText("");
            JTFTelefono1.setForeground(new java.awt.Color(205, 205, 205));
        }
    }//GEN-LAST:event_JTFTelefono1FocusGained

    private void JTFTelefono1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_JTFTelefono1FocusLost
        // TODO add your handling code here:
        if (JTFTelefono1.getText().isEmpty()) {
            JTFTelefono1.setText("Telefono");
            JTFTelefono1.setForeground(new java.awt.Color(153, 153, 153));
        }
    }//GEN-LAST:event_JTFTelefono1FocusLost

    private void JTFTelefono1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_JTFTelefono1KeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if (!Character.isDigit(c) || JTFTelefono1.getText().length() >= 10) {
            evt.consume();
        }
    }//GEN-LAST:event_JTFTelefono1KeyTyped

    private void JTFCorreo1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_JTFCorreo1FocusGained
        // TODO add your handling code here:
        if (JTFCorreo1.getText().equals("Correo")) {
            JTFCorreo1.setText("");
            JTFCorreo1.setForeground(new java.awt.Color(205, 205, 205));
        }
    }//GEN-LAST:event_JTFCorreo1FocusGained

    private void JTFCorreo1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_JTFCorreo1FocusLost
        // TODO add your handling code here:
        if (JTFCorreo1.getText().isEmpty()) {
            JTFCorreo1.setText("Correo");
            JTFCorreo1.setForeground(new java.awt.Color(153, 153, 153));
        }
    }//GEN-LAST:event_JTFCorreo1FocusLost

    private void JCBFechaVencimiento1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JCBFechaVencimiento1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JCBFechaVencimiento1ActionPerformed

    private void JBNRegistrar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBNRegistrar1ActionPerformed
        // TODO add your handling code here:
      
    }//GEN-LAST:event_JBNRegistrar1ActionPerformed

    private void JTFDireccion1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTFDireccion1ActionPerformed
        // TODO add your handling code here:
        JTFDireccion1.addActionListener(e -> JTFTelefono1.requestFocus());
    }//GEN-LAST:event_JTFDireccion1ActionPerformed

    private void JTFTelefono1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTFTelefono1ActionPerformed
        // TODO add your handling code here:
        JTFTelefono1.addActionListener(e -> JTFCorreo1.requestFocus());
    }//GEN-LAST:event_JTFTelefono1ActionPerformed

    private void JTFCorreo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTFCorreo1ActionPerformed
        // TODO add your handling code here:
        JTFCorreo1.addActionListener(e -> JCBFechaVencimiento1.requestFocus());
    }//GEN-LAST:event_JTFCorreo1ActionPerformed

    private void JTFCorreo1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_JTFCorreo1KeyTyped
        // TODO add your handling code here:
        if (((javax.swing.JTextField) evt.getSource()).getText().length() >= 50) {
            evt.consume();
        }
    }//GEN-LAST:event_JTFCorreo1KeyTyped

    private void JBNCancelar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBNCancelar1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JBNCancelar1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NuevaPoliza2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NuevaPoliza2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NuevaPoliza2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NuevaPoliza2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NuevaPoliza2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton JBNCancelar1;
    public javax.swing.JButton JBNRegistrar1;
    public javax.swing.JComboBox<String> JCBFechaVencimiento1;
    public javax.swing.JLabel JLBNombre;
    public javax.swing.JLabel JLBRegistrarTecnico;
    private javax.swing.JPanel JPFondo;
    public javax.swing.JTextField JTFCorreo1;
    public javax.swing.JTextField JTFDireccion1;
    public javax.swing.JTextField JTFEmpresa1;
    public javax.swing.JTextField JTFTelefono1;
    public javax.swing.JLabel jLabel10;
    public javax.swing.JLabel jLabel11;
    public javax.swing.JLabel jLabel12;
    public javax.swing.JLabel jLabel13;
    public javax.swing.JLabel jLabel14;
    public javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables
}
