package Ejecutivo_Vinculacion_Frames;

import Ejecutivo_Vinculacion_Frames.ImagenPanel_EV;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */


/**
 *
 * @author suare
 */
public class NuevoCliente extends javax.swing.JFrame {

    /**
     * Creates new form NuevoCliente
     */
    public NuevoCliente() {
        initComponents();
        this.setSize(800, 580); // Fuerza el tamaño exacto
        this.setResizable(false);
        this.setLocationRelativeTo(null); // Centra la ventana en tu monitor
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JPFondo = new ImagenPanel_EV("/imagenes/FondoETS.jpg");
        JLBRegistrarCliente = new javax.swing.JLabel();
        JLBATelefono = new javax.swing.JLabel();
        JLBCorreo = new javax.swing.JLabel();
        JLBNombre = new javax.swing.JLabel();
        JBNGuardar = new javax.swing.JButton();
        JBNCancelar = new javax.swing.JButton();
        JTFNombre = new javax.swing.JTextField();
        JTFTelefono = new javax.swing.JTextField();
        JTFCorreo = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        JTFApellido = new javax.swing.JTextField();
        JLBNombre1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        JPFondo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        JLBRegistrarCliente.setFont(new java.awt.Font("Montserrat", 1, 24)); // NOI18N
        JLBRegistrarCliente.setForeground(new java.awt.Color(102, 102, 102));
        JLBRegistrarCliente.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        JLBRegistrarCliente.setText("Registrar Nuevo Cliente");
        JPFondo.add(JLBRegistrarCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 780, 40));

        JLBATelefono.setFont(new java.awt.Font("Montserrat", 1, 14)); // NOI18N
        JLBATelefono.setForeground(new java.awt.Color(102, 102, 102));
        JLBATelefono.setText("Telefono");
        JPFondo.add(JLBATelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 280, 150, 40));

        JLBCorreo.setFont(new java.awt.Font("Montserrat", 1, 14)); // NOI18N
        JLBCorreo.setForeground(new java.awt.Color(102, 102, 102));
        JLBCorreo.setText("Correo");
        JPFondo.add(JLBCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 350, 150, 40));

        JLBNombre.setFont(new java.awt.Font("Montserrat", 1, 14)); // NOI18N
        JLBNombre.setForeground(new java.awt.Color(102, 102, 102));
        JLBNombre.setText("Nombre (s)");
        JPFondo.add(JLBNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 140, 150, 40));

        JBNGuardar.setBackground(new java.awt.Color(0, 153, 102));
        JBNGuardar.setFont(new java.awt.Font("Montserrat", 1, 14)); // NOI18N
        JBNGuardar.setForeground(new java.awt.Color(255, 255, 255));
        JBNGuardar.setText("Guardar");
        JBNGuardar.setBorder(null);
        JBNGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBNGuardarActionPerformed(evt);
            }
        });
        JPFondo.add(JBNGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 460, 225, 45));

        JBNCancelar.setFont(new java.awt.Font("Montserrat", 1, 14)); // NOI18N
        JBNCancelar.setText("Cancelar");
        JBNCancelar.setBorder(null);
        JBNCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBNCancelarActionPerformed(evt);
            }
        });
        JPFondo.add(JBNCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 490, 100, 30));

        JTFNombre.setForeground(new java.awt.Color(153, 153, 153));
        JTFNombre.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        JTFNombre.setText("Nombre (s)");
        JTFNombre.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(200, 200, 200), 1, true));
        JTFNombre.setPreferredSize(new java.awt.Dimension(550, 40));
        JTFNombre.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                JTFNombreFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                JTFNombreFocusLost(evt);
            }
        });
        JTFNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTFNombreActionPerformed(evt);
            }
        });
        JTFNombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                JTFNombreKeyTyped(evt);
            }
        });
        JPFondo.add(JTFNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 140, 550, 40));

        JTFTelefono.setForeground(new java.awt.Color(153, 153, 153));
        JTFTelefono.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        JTFTelefono.setText("Telefono");
        JTFTelefono.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(200, 200, 200), 1, true));
        JTFTelefono.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                JTFTelefonoFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                JTFTelefonoFocusLost(evt);
            }
        });
        JTFTelefono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTFTelefonoActionPerformed(evt);
            }
        });
        JTFTelefono.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                JTFTelefonoKeyTyped(evt);
            }
        });
        JPFondo.add(JTFTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 280, 550, 40));

        JTFCorreo.setForeground(new java.awt.Color(153, 153, 153));
        JTFCorreo.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        JTFCorreo.setText("Correo");
        JTFCorreo.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(200, 200, 200), 1, true));
        JTFCorreo.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                JTFCorreoFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                JTFCorreoFocusLost(evt);
            }
        });
        JTFCorreo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTFCorreoActionPerformed(evt);
            }
        });
        JTFCorreo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                JTFCorreoKeyTyped(evt);
            }
        });
        JPFondo.add(JTFCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 350, 550, 40));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Logo ETS 75 px.png"))); // NOI18N
        JPFondo.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 460, -1, -1));

        jLabel1.setFont(new java.awt.Font("Montserrat", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 102, 102));
        jLabel1.setText("Apellido (s)");
        JPFondo.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 210, 150, 40));

        JTFApellido.setForeground(new java.awt.Color(153, 153, 153));
        JTFApellido.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        JTFApellido.setText("Apellido (s)");
        JTFApellido.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(200, 200, 200), 1, true));
        JTFApellido.setPreferredSize(new java.awt.Dimension(550, 40));
        JTFApellido.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                JTFApellidoFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                JTFApellidoFocusLost(evt);
            }
        });
        JTFApellido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTFApellidoActionPerformed(evt);
            }
        });
        JTFApellido.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                JTFApellidoKeyTyped(evt);
            }
        });
        JPFondo.add(JTFApellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 210, 550, 40));

        JLBNombre1.setFont(new java.awt.Font("Montserrat", 1, 14)); // NOI18N
        JLBNombre1.setForeground(new java.awt.Color(153, 153, 153));
        JLBNombre1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        JLBNombre1.setText("Ingrese los datos del cliente que desea registrar");
        JPFondo.add(JLBNombre1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 780, -1));

        getContentPane().add(JPFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 4, 790, 540));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void JBNGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBNGuardarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JBNGuardarActionPerformed

    private void JBNCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBNCancelarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JBNCancelarActionPerformed

    private void JTFNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTFNombreActionPerformed
        // TODO add your handling code here:
        JTFNombre.addActionListener(e -> JTFApellido.requestFocus());
        
        
        //Esta va en apellido
        //JTFApellido.addActionListener(e -> JTFTelefono.requestFocus());
        
    }//GEN-LAST:event_JTFNombreActionPerformed

    private void JTFTelefonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTFTelefonoActionPerformed
        // TODO add your handling code here:
        JTFTelefono.addActionListener(e -> JTFCorreo.requestFocus());
    }//GEN-LAST:event_JTFTelefonoActionPerformed

    private void JTFCorreoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTFCorreoActionPerformed
        // TODO add your handling code here:
        JTFCorreo.addActionListener(e -> JBNGuardar.doClick());
    }//GEN-LAST:event_JTFCorreoActionPerformed

    private void JTFNombreKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_JTFNombreKeyTyped
        // TODO add your handling code here:
        JTFNombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                char c = evt.getKeyChar();
                if (!(Character.isLetter(c) || c == ' ' || Character.isISOControl(c)) || JTFNombre.getText().length() >= 50) {
                    evt.consume();
                }
            }
        });
        
        /* 
        Para apellido
        
        JTFApellido.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                char c = evt.getKeyChar();
                if (!(Character.isLetter(c) || c == ' ' || Character.isISOControl(c)) || JTFApellido.getText().length() >= 50) {
                    evt.consume();
                }
            }
        });
        */
    }//GEN-LAST:event_JTFNombreKeyTyped

    private void JTFTelefonoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_JTFTelefonoKeyTyped
        // TODO add your handling code here:
        JTFTelefono.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                char c = evt.getKeyChar();
                if (!Character.isDigit(c) || JTFTelefono.getText().length() >= 10) {
                    evt.consume();
                }
            }
        });
    }//GEN-LAST:event_JTFTelefonoKeyTyped

    private void JTFCorreoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_JTFCorreoKeyTyped
        // TODO add your handling code here:
        JTFCorreo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                if (JTFCorreo.getText().length() >= 100) {
                    evt.consume();
                }
            }
        });
    }//GEN-LAST:event_JTFCorreoKeyTyped

    private void JTFNombreFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_JTFNombreFocusGained
        // TODO add your handling code here:
        if (JTFNombre.getText().equals("Nombre (s)")) {
            JTFNombre.setText("");
            JTFNombre.setForeground(new java.awt.Color(205, 205, 205)); 
        }    
    }//GEN-LAST:event_JTFNombreFocusGained

    private void JTFNombreFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_JTFNombreFocusLost
        // TODO add your handling code here:
        if (JTFNombre.getText().isEmpty()) {
            JTFNombre.setText("Nombre (s)");
            JTFNombre.setForeground(new java.awt.Color(153, 153, 153)); 
        }
        
        /**
         Para apellido
         *      **añade focus gained**
                if (JTFApellido.getText().equals("Apellido (s)")) {
                JTFApellido.setText("");
                JTFApellido.setForeground(new java.awt.Color(205, 205, 205));
                }
            
            *   **añade focus lost**
                if (JTFApellido.getText().isEmpty()) {
                JTFApellido.setText("Apellido (s)");
                JTFApellido.setForeground(new java.awt.Color(153, 153, 153));
                }
         */
        
    }//GEN-LAST:event_JTFNombreFocusLost

    private void JTFTelefonoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_JTFTelefonoFocusGained
        // TODO add your handling code here:
        if (JTFTelefono.getText().equals("Telefono")) {
            JTFTelefono.setText("");
            JTFTelefono.setForeground(new java.awt.Color(205, 205, 205));
        }
    }//GEN-LAST:event_JTFTelefonoFocusGained

    private void JTFTelefonoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_JTFTelefonoFocusLost
        // TODO add your handling code here:
        if (JTFTelefono.getText().isEmpty()) {
            JTFTelefono.setText("Telefono");
            JTFTelefono.setForeground(new java.awt.Color(153, 153, 153));
        }
    }//GEN-LAST:event_JTFTelefonoFocusLost

    private void JTFCorreoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_JTFCorreoFocusGained
        // TODO add your handling code here:
        if (JTFCorreo.getText().equals("Correo")) {
            JTFCorreo.setText("");
            JTFCorreo.setForeground(new java.awt.Color(205, 205, 205));
        }
    }//GEN-LAST:event_JTFCorreoFocusGained

    private void JTFCorreoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_JTFCorreoFocusLost
        // TODO add your handling code here:
        if (JTFCorreo.getText().isEmpty()) {
            JTFCorreo.setText("Correo");
            JTFCorreo.setForeground(new java.awt.Color(153, 153, 153));
        }
    }//GEN-LAST:event_JTFCorreoFocusLost

    private void JTFApellidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTFApellidoActionPerformed
        // TODO add your handling code here:
        JTFApellido.addActionListener(e -> JTFTelefono.requestFocus());
    }//GEN-LAST:event_JTFApellidoActionPerformed

    private void JTFApellidoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_JTFApellidoFocusGained
        // TODO add your handling code here:
        if (JTFApellido.getText().equals("Apellido (s)")) {
            JTFApellido.setText("");
            JTFApellido.setForeground(new java.awt.Color(205, 205, 205));
        }
    }//GEN-LAST:event_JTFApellidoFocusGained

    private void JTFApellidoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_JTFApellidoFocusLost
        // TODO add your handling code here:
        if (JTFApellido.getText().isEmpty()) {
            JTFApellido.setText("Apellido (s)");
            JTFApellido.setForeground(new java.awt.Color(153, 153, 153));
        }
    }//GEN-LAST:event_JTFApellidoFocusLost

    private void JTFApellidoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_JTFApellidoKeyTyped
        // TODO add your handling code here:
        JTFApellido.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                char c = evt.getKeyChar();
                if (!(Character.isLetter(c) || c == ' ' || Character.isISOControl(c)) || JTFApellido.getText().length() >= 50) {
                    evt.consume();
                }
            }
        });
    }//GEN-LAST:event_JTFApellidoKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NuevoCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NuevoCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NuevoCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NuevoCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NuevoCliente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton JBNCancelar;
    public javax.swing.JButton JBNGuardar;
    public javax.swing.JLabel JLBATelefono;
    public javax.swing.JLabel JLBCorreo;
    public javax.swing.JLabel JLBNombre;
    public javax.swing.JLabel JLBNombre1;
    public javax.swing.JLabel JLBRegistrarCliente;
    private javax.swing.JPanel JPFondo;
    public javax.swing.JTextField JTFApellido;
    public javax.swing.JTextField JTFCorreo;
    public javax.swing.JTextField JTFNombre;
    public javax.swing.JTextField JTFTelefono;
    private javax.swing.JLabel jLabel1;
    public javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
}
