/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Ejecutivo_Vinculacion_Frames;

/**
 *
 * @author suare
 */
public class NuevoUsuario2 extends javax.swing.JFrame {

    /**
     * Creates new form NuevoUsuario2
     */
    public NuevoUsuario2() {
        initComponents();
        this.setSize(800, 600); // Fuerza el tamaño exacto
        this.setResizable(false);
        this.setLocationRelativeTo(null); // Centra la ventana en tu monitor
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JPFondo = new ImagenPanel_EV("/imagenes/FondoETS.jpg");
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        JTFNombre = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        JBNGuardar = new javax.swing.JButton();
        JTFLocacion = new javax.swing.JTextField();
        JTFApelido = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        JBNCancelar = new javax.swing.JButton();
        JTFTelefono = new javax.swing.JTextField();
        JTFCorreo = new javax.swing.JTextField();
        JLBNombre1 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        JPFondo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Montserrat", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(102, 102, 102));
        jLabel2.setText("Apellido");
        JPFondo.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 190, 150, 40));

        jLabel5.setFont(new java.awt.Font("Montserrat", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(102, 102, 102));
        jLabel5.setText("Nombre:");
        JPFondo.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 120, 150, 40));

        JTFNombre.setForeground(new java.awt.Color(153, 153, 153));
        JTFNombre.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        JTFNombre.setText("Nombre (s)");
        JTFNombre.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(200, 200, 200), 1, true));
        JTFNombre.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                JTFNombreFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                JTFNombreFocusLost(evt);
            }
        });
        JTFNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTFNombreActionPerformed(evt);
            }
        });
        JTFNombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                JTFNombreKeyTyped(evt);
            }
        });
        JPFondo.add(JTFNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 120, 550, 40));

        jLabel7.setFont(new java.awt.Font("Montserrat", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(102, 102, 102));
        jLabel7.setText("Teléfono: ");
        JPFondo.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 330, 150, 40));

        jLabel1.setFont(new java.awt.Font("Montserrat", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 102, 102));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Registrar Usuario");
        JPFondo.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 780, 40));

        jLabel6.setFont(new java.awt.Font("Montserrat", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(102, 102, 102));
        jLabel6.setText("Locación:");
        JPFondo.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 260, 150, 40));

        JBNGuardar.setBackground(new java.awt.Color(0, 153, 102));
        JBNGuardar.setFont(new java.awt.Font("Montserrat", 1, 14)); // NOI18N
        JBNGuardar.setForeground(new java.awt.Color(255, 255, 255));
        JBNGuardar.setText("Guardar");
        JBNGuardar.setBorder(null);
        JBNGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBNGuardarActionPerformed(evt);
            }
        });
        JPFondo.add(JBNGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 490, 225, 45));

        JTFLocacion.setForeground(new java.awt.Color(153, 153, 153));
        JTFLocacion.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        JTFLocacion.setText("Locación");
        JTFLocacion.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(200, 200, 200), 1, true));
        JTFLocacion.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                JTFLocacionFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                JTFLocacionFocusLost(evt);
            }
        });
        JTFLocacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTFLocacionActionPerformed(evt);
            }
        });
        JTFLocacion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                JTFLocacionKeyTyped(evt);
            }
        });
        JPFondo.add(JTFLocacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 260, 550, 40));

        JTFApelido.setForeground(new java.awt.Color(153, 153, 153));
        JTFApelido.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        JTFApelido.setText("Apellido (s)");
        JTFApelido.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(200, 200, 200), 1, true));
        JTFApelido.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                JTFApelidoFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                JTFApelidoFocusLost(evt);
            }
        });
        JTFApelido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTFApelidoActionPerformed(evt);
            }
        });
        JTFApelido.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                JTFApelidoKeyTyped(evt);
            }
        });
        JPFondo.add(JTFApelido, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 190, 550, 40));

        jLabel8.setFont(new java.awt.Font("Montserrat", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(102, 102, 102));
        jLabel8.setText("Correo:");
        JPFondo.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 400, 150, 40));

        JBNCancelar.setFont(new java.awt.Font("Montserrat", 1, 14)); // NOI18N
        JBNCancelar.setText("Cancelar");
        JBNCancelar.setBorder(null);
        JBNCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBNCancelarActionPerformed(evt);
            }
        });
        JPFondo.add(JBNCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 520, 100, 30));

        JTFTelefono.setForeground(new java.awt.Color(153, 153, 153));
        JTFTelefono.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        JTFTelefono.setText("Teléfono");
        JTFTelefono.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(200, 200, 200), 1, true));
        JTFTelefono.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                JTFTelefonoFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                JTFTelefonoFocusLost(evt);
            }
        });
        JTFTelefono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTFTelefonoActionPerformed(evt);
            }
        });
        JTFTelefono.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                JTFTelefonoKeyTyped(evt);
            }
        });
        JPFondo.add(JTFTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 330, 550, 40));

        JTFCorreo.setForeground(new java.awt.Color(153, 153, 153));
        JTFCorreo.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        JTFCorreo.setText("Correo electrónico");
        JTFCorreo.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(200, 200, 200), 1, true));
        JTFCorreo.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                JTFCorreoFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                JTFCorreoFocusLost(evt);
            }
        });
        JTFCorreo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTFCorreoActionPerformed(evt);
            }
        });
        JTFCorreo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                JTFCorreoKeyTyped(evt);
            }
        });
        JPFondo.add(JTFCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 400, 550, 40));

        JLBNombre1.setFont(new java.awt.Font("Montserrat", 1, 14)); // NOI18N
        JLBNombre1.setForeground(new java.awt.Color(153, 153, 153));
        JLBNombre1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        JLBNombre1.setText("Ingrese los datos que desea registrar en la empresa seleccionada anteriormente");
        JPFondo.add(JLBNombre1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 780, -1));

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Logo ETS 75 px.png"))); // NOI18N
        JPFondo.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 490, -1, -1));

        getContentPane().add(JPFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 790, 570));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JTFNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTFNombreActionPerformed
        // TODO add your handling code here:
        JTFNombre.addActionListener(e -> JTFApelido.requestFocus());
    }//GEN-LAST:event_JTFNombreActionPerformed

    private void JTFLocacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTFLocacionActionPerformed
        // TODO add your handling code here:
        JTFLocacion.addActionListener(e -> JTFCorreo.requestFocus());
    }//GEN-LAST:event_JTFLocacionActionPerformed

    private void JTFTelefonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTFTelefonoActionPerformed
        // TODO add your handling code here:
        JTFTelefono.addActionListener(e -> JBNGuardar.doClick());
    }//GEN-LAST:event_JTFTelefonoActionPerformed

    private void JTFCorreoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTFCorreoActionPerformed
        // TODO add your handling code here:
        JTFCorreo.addActionListener(e -> JTFTelefono.requestFocus());
    }//GEN-LAST:event_JTFCorreoActionPerformed

    private void JBNGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBNGuardarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JBNGuardarActionPerformed

    private void JBNCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBNCancelarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JBNCancelarActionPerformed

    private void JTFNombreFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_JTFNombreFocusGained
        // TODO add your handling code here:
        if (JTFNombre.getText().equals("Nombre (s)")) {
            JTFNombre.setText("");
            JTFNombre.setForeground(new java.awt.Color(205, 205, 205));
        }
    }//GEN-LAST:event_JTFNombreFocusGained

    private void JTFNombreFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_JTFNombreFocusLost
        // TODO add your handling code here:
        if (JTFNombre.getText().isEmpty()) {
            JTFNombre.setText("Nombre (s)");
            JTFNombre.setForeground(new java.awt.Color(153, 153, 153));
        }
    }//GEN-LAST:event_JTFNombreFocusLost

    private void JTFApelidoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_JTFApelidoFocusGained
        // TODO add your handling code here:
        if (JTFApelido.getText().equals("Apellido (s)")) {
            JTFApelido.setText("");
            JTFApelido.setForeground(new java.awt.Color(205, 205, 205));
        }
    }//GEN-LAST:event_JTFApelidoFocusGained

    private void JTFApelidoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_JTFApelidoFocusLost
        // TODO add your handling code here:
        if (JTFApelido.getText().isEmpty()) {
            JTFApelido.setText("Apellido (s)");
            JTFApelido.setForeground(new java.awt.Color(153, 153, 153));
        }
    }//GEN-LAST:event_JTFApelidoFocusLost

    private void JTFLocacionFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_JTFLocacionFocusGained
        // TODO add your handling code here:
        if (JTFLocacion.getText().equals("Locación")) {
            JTFLocacion.setText("");
            JTFLocacion.setForeground(new java.awt.Color(205, 205, 205));
        }
    }//GEN-LAST:event_JTFLocacionFocusGained

    private void JTFLocacionFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_JTFLocacionFocusLost
        // TODO add your handling code here:
        if (JTFLocacion.getText().isEmpty()) {
            JTFLocacion.setText("Locación");
            JTFLocacion.setForeground(new java.awt.Color(153, 153, 153));
        }
    }//GEN-LAST:event_JTFLocacionFocusLost

    private void JTFCorreoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_JTFCorreoFocusGained
        // TODO add your handling code here:
        if (JTFCorreo.getText().equals("Correo electrónico")) {
            JTFCorreo.setText("");
            JTFCorreo.setForeground(new java.awt.Color(205, 205, 205));
        }
    }//GEN-LAST:event_JTFCorreoFocusGained

    private void JTFCorreoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_JTFCorreoFocusLost
        // TODO add your handling code here:
        if (JTFCorreo.getText().isEmpty()) {
            JTFCorreo.setText("Correo electrónico");
            JTFCorreo.setForeground(new java.awt.Color(153, 153, 153));
        }
    }//GEN-LAST:event_JTFCorreoFocusLost

    private void JTFTelefonoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_JTFTelefonoFocusGained
        // TODO add your handling code here:
        if (JTFTelefono.getText().equals("Teléfono")) {
            JTFTelefono.setText("");
            JTFTelefono.setForeground(new java.awt.Color(205, 205, 205));
        }
    }//GEN-LAST:event_JTFTelefonoFocusGained

    private void JTFTelefonoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_JTFTelefonoFocusLost
        // TODO add your handling code here:
        if (JTFTelefono.getText().isEmpty()) {
            JTFTelefono.setText("Teléfono");
            JTFTelefono.setForeground(new java.awt.Color(153, 153, 153));
        }
    }//GEN-LAST:event_JTFTelefonoFocusLost

    private void JTFApelidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTFApelidoActionPerformed
        // TODO add your handling code here:
        JTFApelido.addActionListener(e -> JTFLocacion.requestFocus());
    }//GEN-LAST:event_JTFApelidoActionPerformed

    private void JTFNombreKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_JTFNombreKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        javax.swing.JTextField field = (javax.swing.JTextField) evt.getSource();
        if (!(Character.isLetter(c) || c == ' ' || Character.isISOControl(c)) || field.getText().length() >= 50) {
            evt.consume();
        }
    }//GEN-LAST:event_JTFNombreKeyTyped

    private void JTFApelidoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_JTFApelidoKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        javax.swing.JTextField field = (javax.swing.JTextField) evt.getSource();
        if (!(Character.isLetter(c) || c == ' ' || Character.isISOControl(c)) || field.getText().length() >= 50) {
            evt.consume();
        }
    }//GEN-LAST:event_JTFApelidoKeyTyped

    private void JTFLocacionKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_JTFLocacionKeyTyped
        // TODO add your handling code here:
        if (((javax.swing.JTextField) evt.getSource()).getText().length() >= 100) {
            evt.consume();
        }
    }//GEN-LAST:event_JTFLocacionKeyTyped

    private void JTFCorreoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_JTFCorreoKeyTyped
        // TODO add your handling code here:
        if (((javax.swing.JTextField) evt.getSource()).getText().length() >= 100) {
            evt.consume();
        }
    }//GEN-LAST:event_JTFCorreoKeyTyped

    private void JTFTelefonoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_JTFTelefonoKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if (!Character.isDigit(c) || JTFTelefono.getText().length() >= 10) {
            evt.consume();
        }
    }//GEN-LAST:event_JTFTelefonoKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NuevoUsuario2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NuevoUsuario2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NuevoUsuario2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NuevoUsuario2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NuevoUsuario2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton JBNCancelar;
    public javax.swing.JButton JBNGuardar;
    public javax.swing.JLabel JLBNombre1;
    private javax.swing.JPanel JPFondo;
    public javax.swing.JTextField JTFApelido;
    public javax.swing.JTextField JTFCorreo;
    public javax.swing.JTextField JTFLocacion;
    public javax.swing.JTextField JTFNombre;
    public javax.swing.JTextField JTFTelefono;
    public javax.swing.JLabel jLabel1;
    public javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    public javax.swing.JLabel jLabel5;
    public javax.swing.JLabel jLabel6;
    public javax.swing.JLabel jLabel7;
    public javax.swing.JLabel jLabel8;
    // End of variables declaration//GEN-END:variables
}
