package Ejecutivo_Vinculacion_Frames;

import Ejecutivo_Vinculacion_Frames.ImagenPanel_EV;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */


/**
 *
 * @author suare
 */
public class NuevoCliente extends javax.swing.JFrame {

    /**
     * Creates new form NuevoCliente
     */
    public NuevoCliente() {
        initComponents();
        this.setSize(610, 550); // Fuerza el tamaño exacto
        this.setLocationRelativeTo(null); // Centra la ventana en tu monitor
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JPFondo = new ImagenPanel_EV("/imagenes/FondoETS.jpg");
        JLBRegistrarCliente = new javax.swing.JLabel();
        JLBATelefono = new javax.swing.JLabel();
        JLBCorreo = new javax.swing.JLabel();
        JLBNombre = new javax.swing.JLabel();
        JBNGuardar = new javax.swing.JButton();
        JBNCancelar = new javax.swing.JButton();
        JTFNombre = new javax.swing.JTextField();
        JTFTelefono = new javax.swing.JTextField();
        JTFCorreo = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        JTFApellido = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        JPFondo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        JLBRegistrarCliente.setFont(new java.awt.Font("Montserrat", 1, 36)); // NOI18N
        JLBRegistrarCliente.setForeground(new java.awt.Color(102, 102, 102));
        JLBRegistrarCliente.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        JLBRegistrarCliente.setText("Registrar Cliente:");
        JPFondo.add(JLBRegistrarCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 660, 50));

        JLBATelefono.setFont(new java.awt.Font("Montserrat", 1, 14)); // NOI18N
        JLBATelefono.setForeground(new java.awt.Color(153, 153, 153));
        JLBATelefono.setText("Telefono");
        JPFondo.add(JLBATelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 260, 100, 50));

        JLBCorreo.setFont(new java.awt.Font("Montserrat", 1, 14)); // NOI18N
        JLBCorreo.setForeground(new java.awt.Color(153, 153, 153));
        JLBCorreo.setText("Correo");
        JPFondo.add(JLBCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 330, 100, 50));

        JLBNombre.setFont(new java.awt.Font("Montserrat", 1, 14)); // NOI18N
        JLBNombre.setForeground(new java.awt.Color(153, 153, 153));
        JLBNombre.setText("Nombre (s)");
        JPFondo.add(JLBNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 110, 100, 50));

        JBNGuardar.setBackground(new java.awt.Color(0, 153, 102));
        JBNGuardar.setFont(new java.awt.Font("Montserrat", 1, 14)); // NOI18N
        JBNGuardar.setForeground(new java.awt.Color(255, 255, 255));
        JBNGuardar.setText("Guardar");
        JBNGuardar.setBorder(null);
        JBNGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBNGuardarActionPerformed(evt);
            }
        });
        JPFondo.add(JBNGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 430, 190, 50));

        JBNCancelar.setFont(new java.awt.Font("Montserrat", 1, 14)); // NOI18N
        JBNCancelar.setText("Cancelar");
        JBNCancelar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        JBNCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBNCancelarActionPerformed(evt);
            }
        });
        JPFondo.add(JBNCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 480, 100, 30));

        JTFNombre.setForeground(new java.awt.Color(153, 153, 153));
        JTFNombre.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        JTFNombre.setText("Nombre (s)");
        JTFNombre.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                JTFNombreFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                JTFNombreFocusLost(evt);
            }
        });
        JTFNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTFNombreActionPerformed(evt);
            }
        });
        JTFNombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                JTFNombreKeyTyped(evt);
            }
        });
        JPFondo.add(JTFNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 110, 420, 50));

        JTFTelefono.setForeground(new java.awt.Color(153, 153, 153));
        JTFTelefono.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        JTFTelefono.setText("Telefono");
        JTFTelefono.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                JTFTelefonoFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                JTFTelefonoFocusLost(evt);
            }
        });
        JTFTelefono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTFTelefonoActionPerformed(evt);
            }
        });
        JTFTelefono.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                JTFTelefonoKeyTyped(evt);
            }
        });
        JPFondo.add(JTFTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 260, 420, 50));

        JTFCorreo.setForeground(new java.awt.Color(153, 153, 153));
        JTFCorreo.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        JTFCorreo.setText("Correo");
        JTFCorreo.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                JTFCorreoFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                JTFCorreoFocusLost(evt);
            }
        });
        JTFCorreo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTFCorreoActionPerformed(evt);
            }
        });
        JTFCorreo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                JTFCorreoKeyTyped(evt);
            }
        });
        JPFondo.add(JTFCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 330, 420, 50));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Logo ETS 75 px.png"))); // NOI18N
        JPFondo.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 450, -1, -1));

        jLabel1.setText("apellido");
        JPFondo.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 210, -1, -1));

        JTFApellido.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        JTFApellido.setText("apellido");
        JTFApellido.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                JTFApellidoFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                JTFApellidoFocusLost(evt);
            }
        });
        JTFApellido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTFApellidoActionPerformed(evt);
            }
        });
        JTFApellido.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                JTFApellidoKeyTyped(evt);
            }
        });
        JPFondo.add(JTFApellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 200, 420, 40));

        getContentPane().add(JPFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 4, 660, 540));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void JBNGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBNGuardarActionPerformed
        // TODO add your handling code here:
        String correo = JTFCorreo.getText().trim();
        String tel = JTFTelefono.getText().trim();

        if (tel.length() < 10) {
            javax.swing.JOptionPane.showMessageDialog(this, "El teléfono debe tener 10 dígitos.", "Error de formato", javax.swing.JOptionPane.ERROR_MESSAGE);

        } else if (!correo.contains("@") || !correo.contains(".")) {
            javax.swing.JOptionPane.showMessageDialog(this, "Error de formato, asegurate que el correo contenga '@' y un dominio.", "Correo inválido", javax.swing.JOptionPane.ERROR_MESSAGE);
        }
 
    }//GEN-LAST:event_JBNGuardarActionPerformed

    private void JBNCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBNCancelarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JBNCancelarActionPerformed

    private void JTFNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTFNombreActionPerformed
        // TODO add your handling code here:
        JTFNombre.addActionListener(e -> JTFApellido.requestFocus());
        
        
        //Esta va en apellido
        //JTFApellido.addActionListener(e -> JTFTelefono.requestFocus());
        
    }//GEN-LAST:event_JTFNombreActionPerformed

    private void JTFTelefonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTFTelefonoActionPerformed
        // TODO add your handling code here:
        JTFTelefono.addActionListener(e -> JTFCorreo.requestFocus());
    }//GEN-LAST:event_JTFTelefonoActionPerformed

    private void JTFCorreoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTFCorreoActionPerformed
        // TODO add your handling code here:
        JTFCorreo.addActionListener(e -> JBNGuardar.doClick());
    }//GEN-LAST:event_JTFCorreoActionPerformed

    private void JTFNombreKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_JTFNombreKeyTyped
        // TODO add your handling code here:
        JTFNombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                char c = evt.getKeyChar();
                if (!(Character.isLetter(c) || c == ' ' || Character.isISOControl(c)) || JTFNombre.getText().length() >= 50) {
                    evt.consume();
                }
            }
        });
        
        /* 
        Para apellido
        
        JTFApellido.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                char c = evt.getKeyChar();
                if (!(Character.isLetter(c) || c == ' ' || Character.isISOControl(c)) || JTFApellido.getText().length() >= 50) {
                    evt.consume();
                }
            }
        });
        */
    }//GEN-LAST:event_JTFNombreKeyTyped

    private void JTFTelefonoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_JTFTelefonoKeyTyped
        // TODO add your handling code here:
        JTFTelefono.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                char c = evt.getKeyChar();
                if (!Character.isDigit(c) || JTFTelefono.getText().length() >= 10) {
                    evt.consume();
                }
            }
        });
    }//GEN-LAST:event_JTFTelefonoKeyTyped

    private void JTFCorreoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_JTFCorreoKeyTyped
        // TODO add your handling code here:
        JTFCorreo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                if (JTFCorreo.getText().length() >= 100) {
                    evt.consume();
                }
            }
        });
    }//GEN-LAST:event_JTFCorreoKeyTyped

    private void JTFNombreFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_JTFNombreFocusGained
        // TODO add your handling code here:
        if (JTFNombre.getText().equals("Nombre (s)")) {
            JTFNombre.setText("");
            JTFNombre.setForeground(new java.awt.Color(205, 205, 205)); 
        }    
    }//GEN-LAST:event_JTFNombreFocusGained

    private void JTFNombreFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_JTFNombreFocusLost
        // TODO add your handling code here:
        if (JTFNombre.getText().isEmpty()) {
            JTFNombre.setText("Nombre (s)");
            JTFNombre.setForeground(new java.awt.Color(153, 153, 153)); 
        }
        
        /**
         Para apellido
         *      **añade focus gained**
                if (JTFApellido.getText().equals("Apellido (s)")) {
                JTFApellido.setText("");
                JTFApellido.setForeground(new java.awt.Color(205, 205, 205));
                }
            
            *   **añade focus lost**
                if (JTFApellido.getText().isEmpty()) {
                JTFApellido.setText("Apellido (s)");
                JTFApellido.setForeground(new java.awt.Color(153, 153, 153));
                }
         */
        
    }//GEN-LAST:event_JTFNombreFocusLost

    private void JTFTelefonoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_JTFTelefonoFocusGained
        // TODO add your handling code here:
        if (JTFTelefono.getText().equals("Telefono")) {
            JTFTelefono.setText("");
            JTFTelefono.setForeground(new java.awt.Color(205, 205, 205));
        }
    }//GEN-LAST:event_JTFTelefonoFocusGained

    private void JTFTelefonoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_JTFTelefonoFocusLost
        // TODO add your handling code here:
        if (JTFTelefono.getText().isEmpty()) {
            JTFTelefono.setText("Telefono");
            JTFTelefono.setForeground(new java.awt.Color(153, 153, 153));
        }
    }//GEN-LAST:event_JTFTelefonoFocusLost

    private void JTFCorreoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_JTFCorreoFocusGained
        // TODO add your handling code here:
        if (JTFCorreo.getText().equals("Correo")) {
            JTFCorreo.setText("");
            JTFCorreo.setForeground(new java.awt.Color(205, 205, 205));
        }
    }//GEN-LAST:event_JTFCorreoFocusGained

    private void JTFCorreoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_JTFCorreoFocusLost
        // TODO add your handling code here:
        if (JTFCorreo.getText().isEmpty()) {
            JTFCorreo.setText("Correo");
            JTFCorreo.setForeground(new java.awt.Color(153, 153, 153));
        }
    }//GEN-LAST:event_JTFCorreoFocusLost

    private void JTFApellidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTFApellidoActionPerformed
        // TODO add your handling code here:
        JTFApellido.addActionListener(e -> JTFTelefono.requestFocus());
    }//GEN-LAST:event_JTFApellidoActionPerformed

    private void JTFApellidoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_JTFApellidoFocusGained
        // TODO add your handling code here:
        if (JTFApellido.getText().equals("Apellido (s)")) {
            JTFApellido.setText("");
            JTFApellido.setForeground(new java.awt.Color(205, 205, 205));
        }
    }//GEN-LAST:event_JTFApellidoFocusGained

    private void JTFApellidoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_JTFApellidoFocusLost
        // TODO add your handling code here:
        if (JTFApellido.getText().isEmpty()) {
            JTFApellido.setText("Apellido (s)");
            JTFApellido.setForeground(new java.awt.Color(153, 153, 153));
        }
    }//GEN-LAST:event_JTFApellidoFocusLost

    private void JTFApellidoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_JTFApellidoKeyTyped
        // TODO add your handling code here:
        JTFApellido.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                char c = evt.getKeyChar();
                if (!(Character.isLetter(c) || c == ' ' || Character.isISOControl(c)) || JTFApellido.getText().length() >= 50) {
                    evt.consume();
                }
            }
        });
    }//GEN-LAST:event_JTFApellidoKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NuevoCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NuevoCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NuevoCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NuevoCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NuevoCliente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton JBNCancelar;
    public javax.swing.JButton JBNGuardar;
    public javax.swing.JLabel JLBATelefono;
    public javax.swing.JLabel JLBCorreo;
    public javax.swing.JLabel JLBNombre;
    public javax.swing.JLabel JLBRegistrarCliente;
    private javax.swing.JPanel JPFondo;
    public javax.swing.JTextField JTFApellido;
    public javax.swing.JTextField JTFCorreo;
    public javax.swing.JTextField JTFNombre;
    public javax.swing.JTextField JTFTelefono;
    private javax.swing.JLabel jLabel1;
    public javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
}
