/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Ejecutivo_Vinculacion_Frames;

/**
 *
 * @author suare
 */
public class NuevaPoliza extends javax.swing.JFrame {

    /**
     * Creates new form NuevaPoliza
     */
    public NuevaPoliza() {
        initComponents();
        new Ejecutivo_Vinculacion_Controladores.ControladorNuevaPoliza(this);
        
        this.setSize(490, 525); // Fuerza el tamaño exacto
        this.setLocationRelativeTo(null); // Centra la ventana en tu monitor
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        JLBRegistrarTecnico = new javax.swing.JLabel();
        JLBNombre = new javax.swing.JLabel();
        JLBNombre1 = new javax.swing.JLabel();
        JCBClientes = new javax.swing.JComboBox<>();
        JLBNombre2 = new javax.swing.JLabel();
        JRBEscencial = new javax.swing.JRadioButton();
        JRBProfesional = new javax.swing.JRadioButton();
        JRBEmpresarial = new javax.swing.JRadioButton();
        JLBNombre3 = new javax.swing.JLabel();
        JLBNombre4 = new javax.swing.JLabel();
        JLBNombre5 = new javax.swing.JLabel();
        JBNSiguiente = new javax.swing.JButton();
        JBNCancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        JLBRegistrarTecnico.setFont(new java.awt.Font("Montserrat", 1, 24)); // NOI18N
        JLBRegistrarTecnico.setForeground(new java.awt.Color(102, 102, 102));
        JLBRegistrarTecnico.setText("Nueva Póliza");
        getContentPane().add(JLBRegistrarTecnico, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 20, -1, -1));

        JLBNombre.setFont(new java.awt.Font("Montserrat", 1, 18)); // NOI18N
        JLBNombre.setForeground(new java.awt.Color(153, 153, 153));
        JLBNombre.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        JLBNombre.setText("Seleccione al cliente que desea");
        getContentPane().add(JLBNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 70, 330, -1));

        JLBNombre1.setFont(new java.awt.Font("Montserrat", 1, 18)); // NOI18N
        JLBNombre1.setForeground(new java.awt.Color(153, 153, 153));
        JLBNombre1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        JLBNombre1.setText("adquirir una nueva póliza");
        getContentPane().add(JLBNombre1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 100, 330, -1));

        JCBClientes.setForeground(new java.awt.Color(153, 153, 153));
        JCBClientes.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Cliente" }));
        JCBClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JCBClientesActionPerformed(evt);
            }
        });
        getContentPane().add(JCBClientes, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 140, 370, 40));

        JLBNombre2.setFont(new java.awt.Font("Montserrat", 1, 14)); // NOI18N
        JLBNombre2.setForeground(new java.awt.Color(153, 153, 153));
        JLBNombre2.setText("Plan que desea contratar");
        getContentPane().add(JLBNombre2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 200, -1, -1));

        buttonGroup1.add(JRBEscencial);
        JRBEscencial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JRBEscencialActionPerformed(evt);
            }
        });
        getContentPane().add(JRBEscencial, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 240, -1, -1));

        buttonGroup1.add(JRBProfesional);
        getContentPane().add(JRBProfesional, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 280, -1, -1));

        buttonGroup1.add(JRBEmpresarial);
        getContentPane().add(JRBEmpresarial, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 320, -1, -1));

        JLBNombre3.setFont(new java.awt.Font("Montserrat", 1, 14)); // NOI18N
        JLBNombre3.setText("Escencial");
        getContentPane().add(JLBNombre3, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 240, 120, 20));

        JLBNombre4.setFont(new java.awt.Font("Montserrat", 1, 14)); // NOI18N
        JLBNombre4.setText("Profesional");
        getContentPane().add(JLBNombre4, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 280, 120, 20));

        JLBNombre5.setFont(new java.awt.Font("Montserrat", 1, 14)); // NOI18N
        JLBNombre5.setText("Empresarial");
        getContentPane().add(JLBNombre5, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 320, 120, 20));

        JBNSiguiente.setBackground(new java.awt.Color(0, 153, 102));
        JBNSiguiente.setFont(new java.awt.Font("Montserrat", 1, 14)); // NOI18N
        JBNSiguiente.setForeground(new java.awt.Color(255, 255, 255));
        JBNSiguiente.setText("Guardar");
        JBNSiguiente.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        JBNSiguiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBNSiguienteActionPerformed(evt);
            }
        });
        getContentPane().add(JBNSiguiente, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 370, 224, 42));

        JBNCancelar.setFont(new java.awt.Font("Montserrat", 1, 14)); // NOI18N
        JBNCancelar.setText("Cancelar");
        JBNCancelar.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        JBNCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBNCancelarActionPerformed(evt);
            }
        });
        getContentPane().add(JBNCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 430, 90, 30));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JCBClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JCBClientesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JCBClientesActionPerformed

    private void JRBEscencialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JRBEscencialActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JRBEscencialActionPerformed

    private void JBNSiguienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBNSiguienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JBNSiguienteActionPerformed

    private void JBNCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBNCancelarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JBNCancelarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NuevaPoliza.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NuevaPoliza.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NuevaPoliza.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NuevaPoliza.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NuevaPoliza().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton JBNCancelar;
    public javax.swing.JButton JBNSiguiente;
    public javax.swing.JComboBox<String> JCBClientes;
    public javax.swing.JLabel JLBNombre;
    public javax.swing.JLabel JLBNombre1;
    public javax.swing.JLabel JLBNombre2;
    public javax.swing.JLabel JLBNombre3;
    public javax.swing.JLabel JLBNombre4;
    public javax.swing.JLabel JLBNombre5;
    public javax.swing.JLabel JLBRegistrarTecnico;
    public javax.swing.JRadioButton JRBEmpresarial;
    public javax.swing.JRadioButton JRBEscencial;
    public javax.swing.JRadioButton JRBProfesional;
    private javax.swing.ButtonGroup buttonGroup1;
    // End of variables declaration//GEN-END:variables
}
