package Ejecutivo_Vinculacion_Frames;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */


/**
 *
 * @author suare
 */
public class NuevoCliente extends javax.swing.JFrame {

    /**
     * Creates new form NuevoCliente
     */
    public NuevoCliente() {
        initComponents();
        new Ejecutivo_Vinculacion_Controladores.ControladorNuevoCliente(this);
        this.setSize(610, 550); // Fuerza el tamaño exacto
        this.setLocationRelativeTo(null); // Centra la ventana en tu monitor
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JLBRegistrarTecnico = new javax.swing.JLabel();
        JLBATelefono = new javax.swing.JLabel();
        JLBCorreo = new javax.swing.JLabel();
        JLBNombre = new javax.swing.JLabel();
        JBNGuardar = new javax.swing.JButton();
        JBNCancelar = new javax.swing.JButton();
        JTFNombre = new javax.swing.JTextField();
        JTFTelefono = new javax.swing.JTextField();
        JTFCorreo = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        JLBRegistrarTecnico.setFont(new java.awt.Font("Montserrat", 1, 24)); // NOI18N
        JLBRegistrarTecnico.setForeground(new java.awt.Color(102, 102, 102));
        JLBRegistrarTecnico.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        JLBRegistrarTecnico.setText("Registrar Cliente:");
        getContentPane().add(JLBRegistrarTecnico, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 20, 240, 30));

        JLBATelefono.setFont(new java.awt.Font("Montserrat", 1, 14)); // NOI18N
        JLBATelefono.setForeground(new java.awt.Color(153, 153, 153));
        JLBATelefono.setText("Telefono");
        getContentPane().add(JLBATelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 250, 90, 40));

        JLBCorreo.setFont(new java.awt.Font("Montserrat", 1, 14)); // NOI18N
        JLBCorreo.setForeground(new java.awt.Color(153, 153, 153));
        JLBCorreo.setText("Correo");
        getContentPane().add(JLBCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 320, 90, 40));

        JLBNombre.setFont(new java.awt.Font("Montserrat", 1, 14)); // NOI18N
        JLBNombre.setForeground(new java.awt.Color(153, 153, 153));
        JLBNombre.setText("Nombre (s)");
        getContentPane().add(JLBNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, -1, -1));

        JBNGuardar.setBackground(new java.awt.Color(0, 153, 102));
        JBNGuardar.setFont(new java.awt.Font("Montserrat", 1, 14)); // NOI18N
        JBNGuardar.setForeground(new java.awt.Color(255, 255, 255));
        JBNGuardar.setText("Guardar");
        JBNGuardar.setBorder(null);
        JBNGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBNGuardarActionPerformed(evt);
            }
        });
        getContentPane().add(JBNGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 390, 190, 50));

        JBNCancelar.setFont(new java.awt.Font("Montserrat", 1, 14)); // NOI18N
        JBNCancelar.setText("Cancelar");
        JBNCancelar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        JBNCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBNCancelarActionPerformed(evt);
            }
        });
        getContentPane().add(JBNCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 460, 100, 30));

        JTFNombre.setForeground(new java.awt.Color(153, 153, 153));
        JTFNombre.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        JTFNombre.setText("Nombre (s)");
        getContentPane().add(JTFNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 100, 390, 40));

        JTFTelefono.setForeground(new java.awt.Color(153, 153, 153));
        JTFTelefono.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        JTFTelefono.setText("Telefono");
        getContentPane().add(JTFTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 240, 390, 40));

        JTFCorreo.setForeground(new java.awt.Color(153, 153, 153));
        JTFCorreo.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        JTFCorreo.setText("Correo");
        getContentPane().add(JTFCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 310, 390, 40));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void JBNGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBNGuardarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JBNGuardarActionPerformed

    private void JBNCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBNCancelarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JBNCancelarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NuevoCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NuevoCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NuevoCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NuevoCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NuevoCliente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton JBNCancelar;
    public javax.swing.JButton JBNGuardar;
    public javax.swing.JLabel JLBATelefono;
    public javax.swing.JLabel JLBCorreo;
    public javax.swing.JLabel JLBNombre;
    public javax.swing.JLabel JLBRegistrarTecnico;
    public javax.swing.JTextField JTFCorreo;
    public javax.swing.JTextField JTFNombre;
    public javax.swing.JTextField JTFTelefono;
    // End of variables declaration//GEN-END:variables
}
