/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Ejecutivo_Vinculacion_Frames;

/**
 *
 * @author glomy
 */
public class Nuevo_Usuario extends javax.swing.JFrame {

    /**
     * Creates new form Nuevo_Usuario
     */
    public Nuevo_Usuario() {
        initComponents();
        this.setSize(475, 400); // Fuerza el tamaño exacto
        this.setLocationRelativeTo(null); // Centra la ventana en tu monitor
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTituloNU = new javax.swing.JLabel();
        lblInstruccionesNU = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        JCBClientes = new javax.swing.JComboBox<>();
        JBNSiguiente = new javax.swing.JButton();
        JBNCancelar = new javax.swing.JButton();
        lblInstruccionesNU1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTituloNU.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        lblTituloNU.setForeground(new java.awt.Color(102, 102, 102));
        lblTituloNU.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTituloNU.setText("Nuevo Usuario");
        getContentPane().add(lblTituloNU, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 20, 300, -1));

        lblInstruccionesNU.setBackground(new java.awt.Color(255, 255, 255));
        lblInstruccionesNU.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        lblInstruccionesNU.setForeground(new java.awt.Color(153, 153, 153));
        lblInstruccionesNU.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblInstruccionesNU.setText("los servicios de la póliza al usuario");
        lblInstruccionesNU.setToolTipText("");
        getContentPane().add(lblInstruccionesNU, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, 390, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/ETS MINI2.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 280, -1, -1));

        JCBClientes.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        JCBClientes.setForeground(new java.awt.Color(153, 153, 153));
        JCBClientes.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Clientes registrados..." }));
        JCBClientes.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(JCBClientes, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 170, 350, 50));

        JBNSiguiente.setBackground(new java.awt.Color(0, 153, 102));
        JBNSiguiente.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        JBNSiguiente.setForeground(new java.awt.Color(255, 255, 255));
        JBNSiguiente.setText("Siguiente");
        JBNSiguiente.setBorderPainted(false);
        JBNSiguiente.setFocusPainted(false);
        getContentPane().add(JBNSiguiente, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 260, 120, 40));

        JBNCancelar.setBackground(new java.awt.Color(102, 102, 102));
        JBNCancelar.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        JBNCancelar.setForeground(new java.awt.Color(255, 255, 255));
        JBNCancelar.setText("Cancelar");
        JBNCancelar.setBorderPainted(false);
        JBNCancelar.setFocusPainted(false);
        getContentPane().add(JBNCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 320, -1, -1));

        lblInstruccionesNU1.setBackground(new java.awt.Color(255, 255, 255));
        lblInstruccionesNU1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        lblInstruccionesNU1.setForeground(new java.awt.Color(153, 153, 153));
        lblInstruccionesNU1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblInstruccionesNU1.setText("Seleccione al cliente que autoriza el uso de");
        lblInstruccionesNU1.setToolTipText("");
        getContentPane().add(lblInstruccionesNU1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 400, 30));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Nuevo_Usuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Nuevo_Usuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Nuevo_Usuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Nuevo_Usuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Nuevo_Usuario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton JBNCancelar;
    public javax.swing.JButton JBNSiguiente;
    public javax.swing.JComboBox<String> JCBClientes;
    public javax.swing.JLabel jLabel1;
    public javax.swing.JLabel lblInstruccionesNU;
    public javax.swing.JLabel lblInstruccionesNU1;
    public javax.swing.JLabel lblTituloNU;
    // End of variables declaration//GEN-END:variables
}
