/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Director_General_Frames;

/**
 *
 * @author suare
 */
public class GenerarReporteporTicket extends javax.swing.JFrame {

    /**
     * Creates new form GenerarReporteporTécnico
     */
    public GenerarReporteporTicket() {
        initComponents();
        this.setSize(1125,725 ); // Fuerza el tamaño exacto
        this.setResizable(false);
        this.setLocationRelativeTo(null); // Centra la ventana en tu monitor
        new Director_General_Controladores.ControladorReporteTicket(this);
        
        JPFiltros4.setVisible(false);
        JMIAlternarFiltros4.setText("Mostrar filtros");

        JPFiltros4.setVisible(false);
        JPBusqueda4.setVisible(false);
        JMIAlternarFiltros4.setText("Mostrar filtros");

    }
    
    
               private void toggleFiltros() {
                if (JPFiltros4.isVisible()&& JPBusqueda4.isVisible()) {
                    ocultarFiltros();
                } else {
                    mostrarFiltros();
                }
            }
            
            private void mostrarFiltros() {
                JPFiltros4.setVisible(true);
                JPBusqueda4.setVisible(true);

                getContentPane().remove(JLBTitulo);
                getContentPane().add(JLBTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 1160, -1));
                
                getContentPane().remove(jScrollPane1);
                getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, 1070, 320));

   
                 JMIAlternarFiltros4.setText("Ocultar filtros");

                getContentPane().revalidate();
                getContentPane().repaint();
            }

           private void ocultarFiltros() {
                JPFiltros4.setVisible(false);
                JPBusqueda4.setVisible(false);
                
                getContentPane().remove(JLBTitulo);
                getContentPane().add(JLBTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 1160, -1));

                getContentPane().remove(jScrollPane1);
                getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 1070, 600));

                 JMIAlternarFiltros4.setText("Mostrar filtros");
                 
                JTFBuscador4.setText("");
              // JCBSeleccionador4.setSelectedIndex(0);

                getContentPane().revalidate();
                getContentPane().repaint();
            }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JPFiltros4 = new javax.swing.JPanel();
        JBNAplicarFiltros = new javax.swing.JButton();
        JBNLimpiarFiltros = new javax.swing.JButton();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox();
        jLabel4 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox();
        jRadioButton4 = new javax.swing.JRadioButton();
        jRadioButton5 = new javax.swing.JRadioButton();
        jRadioButton6 = new javax.swing.JRadioButton();
        JPBusqueda4 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        JTFBuscador4 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        JLBTitulo = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        JBNRegresar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        JBTtickets1 = new javax.swing.JTable();
        jMenuBar1 = new javax.swing.JMenuBar();
        JMVista4 = new javax.swing.JMenu();
        JMIAlternarFiltros4 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1000, 750));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        JPFiltros4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        JPFiltros4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        JBNAplicarFiltros.setFont(new java.awt.Font("Montserrat", 1, 14)); // NOI18N
        JBNAplicarFiltros.setText("Aplicar Filtros");
        JBNAplicarFiltros.setBorder(null);
        JPFiltros4.add(JBNAplicarFiltros, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 30, 125, 30));

        JBNLimpiarFiltros.setFont(new java.awt.Font("Montserrat", 1, 14)); // NOI18N
        JBNLimpiarFiltros.setText("Limpiar Filtros");
        JBNLimpiarFiltros.setBorder(null);
        JPFiltros4.add(JBNLimpiarFiltros, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 80, 125, 30));

        jRadioButton1.setFont(new java.awt.Font("Montserrat", 0, 12)); // NOI18N
        jRadioButton1.setForeground(new java.awt.Color(102, 102, 102));
        jRadioButton1.setText("Asesoria");
        JPFiltros4.add(jRadioButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 90, 100, 40));

        jRadioButton2.setFont(new java.awt.Font("Montserrat", 0, 12)); // NOI18N
        jRadioButton2.setForeground(new java.awt.Color(102, 102, 102));
        jRadioButton2.setText("Remoto");
        JPFiltros4.add(jRadioButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 60, 100, 40));

        jRadioButton3.setFont(new java.awt.Font("Montserrat", 0, 12)); // NOI18N
        jRadioButton3.setForeground(new java.awt.Color(102, 102, 102));
        jRadioButton3.setText("Presencial");
        JPFiltros4.add(jRadioButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 30, 100, 40));

        jLabel1.setFont(new java.awt.Font("Montserrat", 0, 12)); // NOI18N
        jLabel1.setText("Estatus del Ticket");
        JPFiltros4.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 10, -1, -1));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        JPFiltros4.add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 220, 30));

        jLabel4.setFont(new java.awt.Font("Montserrat", 1, 12)); // NOI18N
        jLabel4.setText("Filtrar por Tècnico");
        JPFiltros4.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, -1, -1));

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        JPFiltros4.add(jComboBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 220, 30));

        jRadioButton4.setFont(new java.awt.Font("Montserrat", 0, 12)); // NOI18N
        jRadioButton4.setForeground(new java.awt.Color(102, 102, 102));
        jRadioButton4.setText("Cerrado");
        JPFiltros4.add(jRadioButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 60, 100, 40));

        jRadioButton5.setFont(new java.awt.Font("Montserrat", 0, 12)); // NOI18N
        jRadioButton5.setForeground(new java.awt.Color(102, 102, 102));
        jRadioButton5.setText("Proceso");
        JPFiltros4.add(jRadioButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 30, 100, 40));

        jRadioButton6.setFont(new java.awt.Font("Montserrat", 0, 12)); // NOI18N
        jRadioButton6.setForeground(new java.awt.Color(102, 102, 102));
        jRadioButton6.setText("Asignado");
        JPFiltros4.add(jRadioButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 90, 100, 40));

        JPBusqueda4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        JPBusqueda4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setText("Buscar por Ticket");
        JPBusqueda4.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 10, 160, 20));

        JTFBuscador4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTFBuscador4ActionPerformed(evt);
            }
        });
        JPBusqueda4.add(JTFBuscador4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 270, -1));

        JPFiltros4.add(JPBusqueda4, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 350, 310, 90));

        jLabel5.setFont(new java.awt.Font("Montserrat", 0, 12)); // NOI18N
        jLabel5.setText("Filtrar por empresa");
        JPFiltros4.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        jLabel6.setFont(new java.awt.Font("Montserrat", 0, 12)); // NOI18N
        jLabel6.setText("Tipo de Poliza");
        JPFiltros4.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 10, -1, -1));

        getContentPane().add(JPFiltros4, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 90, 830, 140));

        JLBTitulo.setFont(new java.awt.Font("Montserrat", 1, 36)); // NOI18N
        JLBTitulo.setForeground(new java.awt.Color(153, 153, 153));
        JLBTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        JLBTitulo.setText("Generar reporte de tickets");
        getContentPane().add(JLBTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 1030, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Logo ETS 75 px.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 580, -1, -1));

        JBNRegresar.setFont(new java.awt.Font("Montserrat", 0, 14)); // NOI18N
        JBNRegresar.setText("Regresar");
        JBNRegresar.setBorder(null);
        JBNRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBNRegresarActionPerformed(evt);
            }
        });
        getContentPane().add(JBNRegresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 610, 125, 40));

        JBTtickets1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Técnico", "Modalidad", "Fecha Creación", "Fecha Cierre", "Status", "Empresa", "Solicitante", "Descripción"
            }
        ));
        JBTtickets1.setShowGrid(true);
        jScrollPane1.setViewportView(JBTtickets1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 1070, 490));

        JMVista4.setText("Ver");

        JMIAlternarFiltros4.setText("Mostrar");
        JMIAlternarFiltros4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JMIAlternarFiltros4ActionPerformed(evt);
            }
        });
        JMVista4.add(JMIAlternarFiltros4);

        jMenuBar1.add(JMVista4);

        setJMenuBar(jMenuBar1);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void JBNRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBNRegresarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JBNRegresarActionPerformed

    private void JTFBuscador4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTFBuscador4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JTFBuscador4ActionPerformed

    private void JMIAlternarFiltros4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JMIAlternarFiltros4ActionPerformed
        // TODO add your handling code here:
        toggleFiltros();
        
    }//GEN-LAST:event_JMIAlternarFiltros4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GenerarReporteporTicket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GenerarReporteporTicket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GenerarReporteporTicket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GenerarReporteporTicket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GenerarReporteporTicket().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton JBNAplicarFiltros;
    public javax.swing.JButton JBNLimpiarFiltros;
    public javax.swing.JButton JBNRegresar;
    public javax.swing.JTable JBTtickets1;
    public javax.swing.JLabel JLBTitulo;
    private javax.swing.JMenuItem JMIAlternarFiltros4;
    private javax.swing.JMenu JMVista4;
    private javax.swing.JPanel JPBusqueda4;
    private javax.swing.JPanel JPFiltros4;
    public javax.swing.JTextField JTFBuscador4;
    public javax.swing.JComboBox jComboBox1;
    public javax.swing.JComboBox jComboBox2;
    private javax.swing.JLabel jLabel1;
    public javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JMenuBar jMenuBar1;
    public javax.swing.JRadioButton jRadioButton1;
    public javax.swing.JRadioButton jRadioButton2;
    public javax.swing.JRadioButton jRadioButton3;
    public javax.swing.JRadioButton jRadioButton4;
    public javax.swing.JRadioButton jRadioButton5;
    public javax.swing.JRadioButton jRadioButton6;
    public javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
