/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Director_General_Frames;

/**
 *
 * @author suare
 */
public class GenerarReportePóliza extends javax.swing.JFrame {

    /**
     * Creates new form GenerarReportePóliza
     */
    public GenerarReportePóliza() {
        initComponents();
        new Director_General_Controladores.ControladorReportePoliza(this);
       JPFiltros.setVisible(false);
        JMIAlternarFiltros.setText("Mostrar filtros");

        JPFiltros.setVisible(false);
        JPBusqueda.setVisible(false);
        JMIAlternarFiltros.setText("Mostrar filtros");
   
    }
    
            private void toggleFiltros() {
                if (JPFiltros.isVisible()&& JPBusqueda.isVisible()) {
                    ocultarFiltros();
                } else {
                    mostrarFiltros();
                }
            }
            
            private void mostrarFiltros() {
                JPFiltros.setVisible(true);
                JPBusqueda.setVisible(true);

                getContentPane().remove(JLBTitulo);
                getContentPane().add(JLBTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 30, 330, 30));
                
                getContentPane().remove(JSPTabla);
                getContentPane().add(JSPTabla, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 100, 980, 240));

   
                 JMIAlternarFiltros.setText("Ocultar filtros");

                getContentPane().revalidate();
                getContentPane().repaint();
            }

            private void ocultarFiltros() {
                JPFiltros.setVisible(false);
                JPBusqueda.setVisible(false);
                
                getContentPane().remove(JLBTitulo);
                getContentPane().add(JLBTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 20, 330, 20));

                getContentPane().remove(JSPTabla);
                getContentPane().add(JSPTabla, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 1100, 280));

                 JMIAlternarFiltros.setText("Mostrar filtros");
                 
                JTFBuscador.setText("");
                JCBSeleccionador.setSelectedIndex(0);

                getContentPane().revalidate();
                getContentPane().repaint();
            }

            
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JBGFechas = new javax.swing.ButtonGroup();
        JLBTitulo = new javax.swing.JLabel();
        JSPTabla = new javax.swing.JScrollPane();
        JTBPolizas = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        JBNRegresar = new javax.swing.JButton();
        JPFiltros = new javax.swing.JPanel();
        JCBActiva = new javax.swing.JCheckBox();
        JCBInactiva = new javax.swing.JCheckBox();
        JCBEsencial = new javax.swing.JCheckBox();
        JCBProfesional = new javax.swing.JCheckBox();
        JCBEmpresarial = new javax.swing.JCheckBox();
        JRBInicioMasActual = new javax.swing.JRadioButton();
        JRBInicioMasAntigua = new javax.swing.JRadioButton();
        JRBVenceMasPronta = new javax.swing.JRadioButton();
        JRBVenceMasLejana = new javax.swing.JRadioButton();
        JCBOrdenCliente = new javax.swing.JComboBox<>();
        JBNAplicarFiltros = new javax.swing.JButton();
        JBNLimpiarFiltros = new javax.swing.JButton();
        JPBusqueda = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        JTFBuscador = new javax.swing.JTextField();
        JCBSeleccionador = new javax.swing.JComboBox<>();
        jMenuBar1 = new javax.swing.JMenuBar();
        JMVista = new javax.swing.JMenu();
        JMIAlternarFiltros = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        JLBTitulo.setFont(new java.awt.Font("Montserrat", 1, 24)); // NOI18N
        JLBTitulo.setForeground(new java.awt.Color(153, 153, 153));
        JLBTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        JLBTitulo.setText("Generar reporte póliza ");
        getContentPane().add(JLBTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 30, 330, -1));

        JTBPolizas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Estado", "Plan", "Fecha Inicio", "Fecha Vencimiento", "Nombre Cliente", "Correo"
            }
        ));
        JTBPolizas.setShowGrid(true);
        JSPTabla.setViewportView(JTBPolizas);

        getContentPane().add(JSPTabla, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 1020, 260));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Logo ETS 75 px.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 340, 110, 80));

        JBNRegresar.setFont(new java.awt.Font("Montserrat", 0, 12)); // NOI18N
        JBNRegresar.setText("Regresar");
        JBNRegresar.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        JBNRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBNRegresarActionPerformed(evt);
            }
        });
        getContentPane().add(JBNRegresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 360, 79, 29));

        JPFiltros.setBorder(new javax.swing.border.MatteBorder(null));
        JPFiltros.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        JCBActiva.setText("Activas");
        JPFiltros.add(JCBActiva, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, -1, 20));

        JCBInactiva.setText("Inactivas");
        JPFiltros.add(JCBInactiva, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, -1, -1));

        JCBEsencial.setText("Esencial");
        JPFiltros.add(JCBEsencial, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, -1, -1));

        JCBProfesional.setText("Profesional");
        JPFiltros.add(JCBProfesional, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, -1, -1));

        JCBEmpresarial.setText("Empresarial");
        JPFiltros.add(JCBEmpresarial, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 110, -1, -1));

        JBGFechas.add(JRBInicioMasActual);
        JRBInicioMasActual.setText("Mas Actual");
        JRBInicioMasActual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JRBInicioMasActualActionPerformed(evt);
            }
        });
        JPFiltros.add(JRBInicioMasActual, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 170, -1, -1));

        JBGFechas.add(JRBInicioMasAntigua);
        JRBInicioMasAntigua.setText("Mas Antigua");
        JPFiltros.add(JRBInicioMasAntigua, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 190, -1, -1));

        JBGFechas.add(JRBVenceMasPronta);
        JRBVenceMasPronta.setText("Vence Mas Pronta");
        JPFiltros.add(JRBVenceMasPronta, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 210, -1, -1));

        JBGFechas.add(JRBVenceMasLejana);
        JRBVenceMasLejana.setText("Vence Mas Lejana");
        JPFiltros.add(JRBVenceMasLejana, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 230, -1, -1));

        JCBOrdenCliente.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Orden Cliente", "A-Z", "Z-A" }));
        JPFiltros.add(JCBOrdenCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 270, 110, -1));

        JBNAplicarFiltros.setText("Aplicar Filtros");
        JPFiltros.add(JBNAplicarFiltros, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 300, -1, -1));

        JBNLimpiarFiltros.setText("Limpiar Filtros");
        JPFiltros.add(JBNLimpiarFiltros, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 330, -1, -1));

        getContentPane().add(JPFiltros, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 130, 360));

        JPBusqueda.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        JPBusqueda.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setText("Buscar por nombre o correo");
        JPBusqueda.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 160, 20));

        JTFBuscador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTFBuscadorActionPerformed(evt);
            }
        });
        JPBusqueda.add(JTFBuscador, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 270, -1));

        JCBSeleccionador.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tipo de Busqueda", "Nombre", "Correo" }));
        JCBSeleccionador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JCBSeleccionadorActionPerformed(evt);
            }
        });
        JPBusqueda.add(JCBSeleccionador, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 10, 130, 20));

        getContentPane().add(JPBusqueda, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 10, 310, 80));

        JMVista.setText("Ver");

        JMIAlternarFiltros.setText("Mostrar filtros");
        JMIAlternarFiltros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JMIAlternarFiltrosActionPerformed(evt);
            }
        });
        JMVista.add(JMIAlternarFiltros);

        jMenuBar1.add(JMVista);

        setJMenuBar(jMenuBar1);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void JBNRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBNRegresarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JBNRegresarActionPerformed

    private void JCBSeleccionadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JCBSeleccionadorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JCBSeleccionadorActionPerformed

    private void JRBInicioMasActualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JRBInicioMasActualActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JRBInicioMasActualActionPerformed

    private void JMIAlternarFiltrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JMIAlternarFiltrosActionPerformed
        // TODO add your handling code here:
         toggleFiltros();
    }//GEN-LAST:event_JMIAlternarFiltrosActionPerformed

    private void JTFBuscadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTFBuscadorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JTFBuscadorActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GenerarReportePóliza.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GenerarReportePóliza.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GenerarReportePóliza.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GenerarReportePóliza.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GenerarReportePóliza().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.ButtonGroup JBGFechas;
    public javax.swing.JButton JBNAplicarFiltros;
    public javax.swing.JButton JBNLimpiarFiltros;
    public javax.swing.JButton JBNRegresar;
    public javax.swing.JCheckBox JCBActiva;
    public javax.swing.JCheckBox JCBEmpresarial;
    public javax.swing.JCheckBox JCBEsencial;
    public javax.swing.JCheckBox JCBInactiva;
    public javax.swing.JComboBox<String> JCBOrdenCliente;
    public javax.swing.JCheckBox JCBProfesional;
    public javax.swing.JComboBox<String> JCBSeleccionador;
    public javax.swing.JLabel JLBTitulo;
    private javax.swing.JMenuItem JMIAlternarFiltros;
    private javax.swing.JMenu JMVista;
    private javax.swing.JPanel JPBusqueda;
    public javax.swing.JPanel JPFiltros;
    public javax.swing.JRadioButton JRBInicioMasActual;
    public javax.swing.JRadioButton JRBInicioMasAntigua;
    public javax.swing.JRadioButton JRBVenceMasLejana;
    public javax.swing.JRadioButton JRBVenceMasPronta;
    public javax.swing.JScrollPane JSPTabla;
    public javax.swing.JTable JTBPolizas;
    public javax.swing.JTextField JTFBuscador;
    public javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenuBar jMenuBar1;
    // End of variables declaration//GEN-END:variables
}
