/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Director_General_Frames;

/**
 *
 * @author suare
 */
public class GenerarReporteporCliente extends javax.swing.JFrame {

    /**
     * Creates new form GenerarReporteporCliente
     */
    public GenerarReporteporCliente() {
        initComponents();
        new Director_General_Controladores.ControladorReporteCliente(this);
        JPFiltros2.setVisible(false);
        JPBusqueda2.setVisible(false);
        JMIAlternarFiltros2.setText("Mostrar filtros");

        
    }
    
                private void toggleFiltros() {
                if (JPFiltros2.isVisible()&& JPBusqueda2.isVisible()) {
                    ocultarFiltros();
                } else {
                    mostrarFiltros();
                }
            }
                
                private void mostrarFiltros() {
                JPFiltros2.setVisible(true);
                JPBusqueda2.setVisible(true);

                JPFondo.remove(JLBTitulo2);
                JPFondo.add(JLBTitulo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 1160, -1));
                
                JPFondo.remove(jScrollPane2);
                JPFondo.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 110, 810, 360));

   
                 JMIAlternarFiltros2.setText("Ocultar filtros");

                getContentPane().revalidate();
                getContentPane().repaint();
            }
                
                
                
                private void ocultarFiltros() {
                JPFiltros2.setVisible(false);
                JPBusqueda2.setVisible(false);

                JPFondo.remove(JLBTitulo2);
                JPFondo.add(JLBTitulo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 1160, -1));
                
                JPFondo.remove(jScrollPane2);
                JPFondo.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, 1080, 360));

   
                 JMIAlternarFiltros2.setText("Mostrar filtros");

                getContentPane().revalidate();
                getContentPane().repaint();
            }
    
    
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JBGFechas2 = new javax.swing.ButtonGroup();
        JPFondo = new ImagenPanel_DG("/imagenes/FondoETS.jpg");
        JLBTitulo2 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        JBNRegresar = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        JSPTabla2 = new javax.swing.JTable();
        JPBusqueda2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        JTFBuscador2 = new javax.swing.JTextField();
        JCBSeleccionador2 = new javax.swing.JComboBox<>();
        JPFiltros2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        JCBInactiva2 = new javax.swing.JCheckBox();
        JCBActiva2 = new javax.swing.JCheckBox();
        JRBTiempoMayor = new javax.swing.JRadioButton();
        JRBTiempoMenor = new javax.swing.JRadioButton();
        jLabel4 = new javax.swing.JLabel();
        JBNAplicarFiltros2 = new javax.swing.JButton();
        JBNLimpiarFiltros2 = new javax.swing.JButton();
        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        JMIAlternarFiltros2 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        JPFondo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        JLBTitulo2.setFont(new java.awt.Font("Montserrat", 1, 36)); // NOI18N
        JLBTitulo2.setForeground(new java.awt.Color(102, 102, 102));
        JLBTitulo2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        JLBTitulo2.setText("Reporte por Cliente");
        JPFondo.add(JLBTitulo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 1160, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Logo ETS 75 px.png"))); // NOI18N
        JPFondo.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        JBNRegresar.setFont(new java.awt.Font("Montserrat", 1, 12)); // NOI18N
        JBNRegresar.setText("Regresar");
        JBNRegresar.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        JBNRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBNRegresarActionPerformed(evt);
            }
        });
        JPFondo.add(JBNRegresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(1040, 500, 100, 30));

        JSPTabla2.setFont(new java.awt.Font("Montserrat", 0, 12)); // NOI18N
        JSPTabla2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Estado de la Póliza", "Nombre Cliente", "Empresa", "Solicitante de servicio", "Tiempo de poliza act ", "Correo del Cliente", "Teléfono del Cliente"
            }
        ));
        JSPTabla2.setRowHeight(25);
        JSPTabla2.setShowGrid(true);
        jScrollPane2.setViewportView(JSPTabla2);

        JPFondo.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, 1080, 360));

        JPBusqueda2.setBackground(new java.awt.Color(255, 255, 255, 180));
        JPBusqueda2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Búsqueda Rápida", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Montserrat", 1, 12))); // NOI18N
        JPBusqueda2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Montserrat", 0, 11)); // NOI18N
        jLabel3.setText("Buscar por:");
        JPBusqueda2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 80, 20));

        JTFBuscador2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTFBuscador2ActionPerformed(evt);
            }
        });
        JPBusqueda2.add(JTFBuscador2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 45, 290, -1));

        JCBSeleccionador2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tipo de Busqueda", "Nombre del Cliente", "Empresa", "Solicitante de servicio", "Correo del Cliente" }));
        JCBSeleccionador2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JCBSeleccionador2ActionPerformed(evt);
            }
        });
        JPBusqueda2.add(JCBSeleccionador2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 20, 170, 20));

        JPFondo.add(JPBusqueda2, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 480, 310, 80));

        JPFiltros2.setBackground(new java.awt.Color(255, 255, 255, 180));
        JPFiltros2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Filtros", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Montserrat", 1, 12))); // NOI18N
        JPFiltros2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Montserrat", 1, 11)); // NOI18N
        jLabel1.setText("Estado:");
        JPFiltros2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, -1));

        JCBInactiva2.setText("Inactivas");
        JCBInactiva2.setOpaque(false);
        JPFiltros2.add(JCBInactiva2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, -1, -1));

        JCBActiva2.setText("Activas");
        JCBActiva2.setOpaque(false);
        JPFiltros2.add(JCBActiva2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, -1, 20));

        JBGFechas2.add(JRBTiempoMayor);
        JRBTiempoMayor.setText("Tiempo Mayor");
        JRBTiempoMayor.setOpaque(false);
        JPFiltros2.add(JRBTiempoMayor, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 40, -1, -1));

        JBGFechas2.add(JRBTiempoMenor);
        JRBTiempoMenor.setText("Tiempo Menor");
        JRBTiempoMenor.setOpaque(false);
        JPFiltros2.add(JRBTiempoMenor, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 60, -1, -1));

        jLabel4.setFont(new java.awt.Font("Montserrat", 1, 11)); // NOI18N
        jLabel4.setText("Organizar:");
        JPFiltros2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 20, -1, -1));

        JBNAplicarFiltros2.setText("Aplicar");
        JPFiltros2.add(JBNAplicarFiltros2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 100, -1));

        JBNLimpiarFiltros2.setText("Limpiar");
        JPFiltros2.add(JBNLimpiarFiltros2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 100, 100, -1));

        JPFondo.add(JPFiltros2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 280, 140));

        getContentPane().add(JPFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1160, 580));

        jMenu1.setText("Ver");

        JMIAlternarFiltros2.setText("Mostrar filtros");
        JMIAlternarFiltros2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JMIAlternarFiltros2ActionPerformed(evt);
            }
        });
        jMenu1.add(JMIAlternarFiltros2);

        jMenuBar2.add(jMenu1);

        setJMenuBar(jMenuBar2);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void JBNRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBNRegresarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JBNRegresarActionPerformed

    private void JTFBuscador2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTFBuscador2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JTFBuscador2ActionPerformed

    private void JCBSeleccionador2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JCBSeleccionador2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JCBSeleccionador2ActionPerformed

    private void JMIAlternarFiltros2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JMIAlternarFiltros2ActionPerformed
        // TODO add your handling code here:
        toggleFiltros();
    }//GEN-LAST:event_JMIAlternarFiltros2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GenerarReporteporCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GenerarReporteporCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GenerarReporteporCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GenerarReporteporCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GenerarReporteporCliente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.ButtonGroup JBGFechas2;
    public javax.swing.JButton JBNAplicarFiltros2;
    public javax.swing.JButton JBNLimpiarFiltros2;
    public javax.swing.JButton JBNRegresar;
    public javax.swing.JCheckBox JCBActiva2;
    public javax.swing.JCheckBox JCBInactiva2;
    public javax.swing.JComboBox<String> JCBSeleccionador2;
    public javax.swing.JLabel JLBTitulo2;
    private javax.swing.JMenuItem JMIAlternarFiltros2;
    private javax.swing.JPanel JPBusqueda2;
    private javax.swing.JPanel JPFiltros2;
    private javax.swing.JPanel JPFondo;
    public javax.swing.JRadioButton JRBTiempoMayor;
    public javax.swing.JRadioButton JRBTiempoMenor;
    public javax.swing.JTable JSPTabla2;
    public javax.swing.JTextField JTFBuscador2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar2;
    public javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
