/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Director_General_Frames;

/**
 *
 * @author Alejandro
 */
public class Menu_Director_General extends javax.swing.JFrame {

    /**
     * Creates new form Test2
     */
    public Menu_Director_General() {
        initComponents();
        this.setSize(800, 600); // Fuerza el tamaño exacto
        this.setResizable(false);
        this.setLocationRelativeTo(null); // Centra la ventana en tu monitor
        jMenuBar1.add(javax.swing.Box.createHorizontalGlue(), 2);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        JPFondo = new ImagenPanel_DG("/imagenes/FondoETS.jpg");
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        JBNPersonal = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        JBNReportes = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        JMIReporteTecnico = new javax.swing.JMenuItem();
        JMIReporteCliente = new javax.swing.JMenuItem();
        JMIReportePoliza = new javax.swing.JMenuItem();
        JMIConsumos = new javax.swing.JMenuItem();
        JMBPersonal = new javax.swing.JMenu();
        JMINuevoTecnico = new javax.swing.JMenuItem();
        JMNCerrarSesion = new javax.swing.JMenu();
        JMICerrarSesion = new javax.swing.JMenuItem();

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setMinimumSize(new java.awt.Dimension(450, 380));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        JPFondo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Montserrat", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 102, 102));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("¡Bienvenido!");
        JPFondo.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 800, -1));

        jLabel2.setFont(new java.awt.Font("Montserrat", 1, 48)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(102, 102, 102));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Director General");
        JPFondo.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, 800, -1));

        JBNPersonal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos90/reportecliente90.png"))); // NOI18N
        JBNPersonal.setToolTipText("");
        JBNPersonal.setMaximumSize(new java.awt.Dimension(130, 130));
        JBNPersonal.setMinimumSize(new java.awt.Dimension(130, 130));
        JBNPersonal.setPreferredSize(new java.awt.Dimension(130, 130));
        JPFondo.add(JBNPersonal, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 240, 140, 150));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Logo ETS 75 px.png"))); // NOI18N
        JPFondo.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        JBNReportes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/tickets mini.png"))); // NOI18N
        JBNReportes.setMaximumSize(new java.awt.Dimension(130, 130));
        JBNReportes.setMinimumSize(new java.awt.Dimension(130, 130));
        JPFondo.add(JBNReportes, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 240, 140, 150));

        getContentPane().add(JPFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 820, 540));

        jMenuBar1.setFont(new java.awt.Font("Montserrat", 0, 12)); // NOI18N

        jMenu1.setText("Reportes     ");

        JMIReporteTecnico.setText("Reporte Tecnico");
        jMenu1.add(JMIReporteTecnico);

        JMIReporteCliente.setText("Reporte Cliente");
        jMenu1.add(JMIReporteCliente);

        JMIReportePoliza.setText("Reporte Poliza");
        jMenu1.add(JMIReportePoliza);

        JMIConsumos.setText("Consumos");
        jMenu1.add(JMIConsumos);

        jMenuBar1.add(jMenu1);

        JMBPersonal.setText("Personal");

        JMINuevoTecnico.setText("Nuevo Tecnico");
        JMBPersonal.add(JMINuevoTecnico);

        jMenuBar1.add(JMBPersonal);

        JMNCerrarSesion.setText("Cerrar Sesión");
        JMNCerrarSesion.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);

        JMICerrarSesion.setText("Salir");
        JMNCerrarSesion.add(JMICerrarSesion);

        jMenuBar1.add(JMNCerrarSesion);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu_Director_General.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu_Director_General.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu_Director_General.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu_Director_General.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Menu_Director_General vista = new Menu_Director_General();
                new Director_General_Controladores.ControladorMenuDirector(vista);
                vista.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton JBNPersonal;
    public javax.swing.JButton JBNReportes;
    public javax.swing.JMenu JMBPersonal;
    public javax.swing.JMenuItem JMICerrarSesion;
    public javax.swing.JMenuItem JMIConsumos;
    public javax.swing.JMenuItem JMINuevoTecnico;
    public javax.swing.JMenuItem JMIReporteCliente;
    public javax.swing.JMenuItem JMIReportePoliza;
    public javax.swing.JMenuItem JMIReporteTecnico;
    public javax.swing.JMenu JMNCerrarSesion;
    private javax.swing.JPanel JPFondo;
    public javax.swing.JLabel jLabel1;
    public javax.swing.JLabel jLabel2;
    public javax.swing.JLabel jLabel3;
    public javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    // End of variables declaration//GEN-END:variables
}
