/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Supervisor_Tecnico_Frames;

/**
 *
 * @author suare
 */
public class AsignarTicket extends javax.swing.JFrame {

    /**
     * Creates new form AsignarTicket
     */
    public AsignarTicket() {
        initComponents();
        this.setSize(500, 550); // Fuerza el tamaño exacto
        this.setLocationRelativeTo(null); // Centra la ventana en tu monitor
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtUsuario = new javax.swing.JTextField();
        JLBAsignarTecnico = new javax.swing.JLabel();
        JLBDescripcion1 = new javax.swing.JLabel();
        JLBDescripcion2 = new javax.swing.JLabel();
        JLBDescripcion3 = new javax.swing.JLabel();
        JTFNumeroTicket = new javax.swing.JTextField();
        JBNSiguienteTF = new javax.swing.JButton();
        JCBTickets = new javax.swing.JComboBox<>();
        JBNSiguienteCB = new javax.swing.JButton();
        JBNCancelar = new javax.swing.JButton();

        txtUsuario.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtUsuario.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtUsuario.setText("Usuario");
        txtUsuario.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 153), 2, true));
        txtUsuario.setPreferredSize(new java.awt.Dimension(150, 30));
        txtUsuario.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtUsuarioFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtUsuarioFocusLost(evt);
            }
        });
        txtUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUsuarioActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        JLBAsignarTecnico.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        JLBAsignarTecnico.setForeground(new java.awt.Color(102, 102, 102));
        JLBAsignarTecnico.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        JLBAsignarTecnico.setText("Asignar técnico");
        getContentPane().add(JLBAsignarTecnico, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 20, 280, -1));

        JLBDescripcion1.setFont(new java.awt.Font("Montserrat", 1, 18)); // NOI18N
        JLBDescripcion1.setForeground(new java.awt.Color(153, 153, 153));
        JLBDescripcion1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        JLBDescripcion1.setText("Ingrese o seleccione el numero");
        getContentPane().add(JLBDescripcion1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 70, 300, -1));

        JLBDescripcion2.setFont(new java.awt.Font("Montserrat", 1, 18)); // NOI18N
        JLBDescripcion2.setForeground(new java.awt.Color(153, 153, 153));
        JLBDescripcion2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        JLBDescripcion2.setText("de ticket al cual se le va a ");
        getContentPane().add(JLBDescripcion2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 100, 300, -1));

        JLBDescripcion3.setFont(new java.awt.Font("Montserrat", 1, 18)); // NOI18N
        JLBDescripcion3.setForeground(new java.awt.Color(153, 153, 153));
        JLBDescripcion3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        JLBDescripcion3.setText("asignar un técnico");
        getContentPane().add(JLBDescripcion3, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 130, 300, -1));

        JTFNumeroTicket.setFont(new java.awt.Font("Montserrat", 1, 14)); // NOI18N
        JTFNumeroTicket.setForeground(new java.awt.Color(102, 102, 102));
        JTFNumeroTicket.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        JTFNumeroTicket.setText("Numero de ticket");
        JTFNumeroTicket.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        JTFNumeroTicket.setPreferredSize(new java.awt.Dimension(150, 30));
        JTFNumeroTicket.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                JTFNumeroTicketFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                JTFNumeroTicketFocusLost(evt);
            }
        });
        JTFNumeroTicket.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTFNumeroTicketActionPerformed(evt);
            }
        });
        getContentPane().add(JTFNumeroTicket, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 180, 390, 40));

        JBNSiguienteTF.setBackground(new java.awt.Color(0, 153, 102));
        JBNSiguienteTF.setFont(new java.awt.Font("Montserrat", 1, 14)); // NOI18N
        JBNSiguienteTF.setForeground(new java.awt.Color(255, 255, 255));
        JBNSiguienteTF.setText("Siguiente");
        JBNSiguienteTF.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(39, 174, 96), 1, true));
        JBNSiguienteTF.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        JBNSiguienteTF.setOpaque(true);
        JBNSiguienteTF.setPreferredSize(new java.awt.Dimension(100, 25));
        JBNSiguienteTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBNSiguienteTFActionPerformed(evt);
            }
        });
        getContentPane().add(JBNSiguienteTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 250, 200, 42));

        JCBTickets.setFont(new java.awt.Font("Montserrat", 0, 14)); // NOI18N
        JCBTickets.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ticket", "Ticket", "Ticket", "Ticket" }));
        JCBTickets.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        getContentPane().add(JCBTickets, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 330, 390, 50));

        JBNSiguienteCB.setBackground(new java.awt.Color(0, 153, 102));
        JBNSiguienteCB.setFont(new java.awt.Font("Montserrat", 1, 14)); // NOI18N
        JBNSiguienteCB.setForeground(new java.awt.Color(255, 255, 255));
        JBNSiguienteCB.setText("Siguiente");
        JBNSiguienteCB.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(39, 174, 96), 1, true));
        JBNSiguienteCB.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        JBNSiguienteCB.setOpaque(true);
        JBNSiguienteCB.setPreferredSize(new java.awt.Dimension(100, 25));
        JBNSiguienteCB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBNSiguienteCBActionPerformed(evt);
            }
        });
        getContentPane().add(JBNSiguienteCB, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 410, 200, 42));

        JBNCancelar.setFont(new java.awt.Font("Montserrat", 1, 14)); // NOI18N
        JBNCancelar.setText("Cancelar");
        JBNCancelar.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        JBNCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBNCancelarActionPerformed(evt);
            }
        });
        getContentPane().add(JBNCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 460, 80, 30));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtUsuarioFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtUsuarioFocusGained
        if (txtUsuario.getText().equals("Usuario")) {
            txtUsuario.setText("");
            txtUsuario.setForeground(new java.awt.Color(51, 51, 51)); // Letra oscura al escribir
        }
    }//GEN-LAST:event_txtUsuarioFocusGained

    private void txtUsuarioFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtUsuarioFocusLost
        if (txtUsuario.getText().isEmpty()) {
            txtUsuario.setText("Usuario");
            txtUsuario.setForeground(new java.awt.Color(153, 153, 153)); // Vuelve al gris claro
        }
    }//GEN-LAST:event_txtUsuarioFocusLost

    private void txtUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUsuarioActionPerformed

    private void JTFNumeroTicketFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_JTFNumeroTicketFocusGained
        if (txtUsuario.getText().equals("Usuario")) {
            txtUsuario.setText("");
            txtUsuario.setForeground(new java.awt.Color(51, 51, 51)); // Letra oscura al escribir
        }
    }//GEN-LAST:event_JTFNumeroTicketFocusGained

    private void JTFNumeroTicketFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_JTFNumeroTicketFocusLost
        if (txtUsuario.getText().isEmpty()) {
            txtUsuario.setText("Usuario");
            txtUsuario.setForeground(new java.awt.Color(153, 153, 153)); // Vuelve al gris claro
        }
    }//GEN-LAST:event_JTFNumeroTicketFocusLost

    private void JTFNumeroTicketActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTFNumeroTicketActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JTFNumeroTicketActionPerformed

    private void JBNSiguienteTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBNSiguienteTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JBNSiguienteTFActionPerformed

    private void JBNSiguienteCBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBNSiguienteCBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JBNSiguienteCBActionPerformed

    private void JBNCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBNCancelarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JBNCancelarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AsignarTicket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AsignarTicket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AsignarTicket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AsignarTicket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AsignarTicket().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton JBNCancelar;
    public javax.swing.JButton JBNSiguienteCB;
    public javax.swing.JButton JBNSiguienteTF;
    public javax.swing.JComboBox<String> JCBTickets;
    public javax.swing.JLabel JLBAsignarTecnico;
    public javax.swing.JLabel JLBDescripcion1;
    public javax.swing.JLabel JLBDescripcion2;
    public javax.swing.JLabel JLBDescripcion3;
    public javax.swing.JTextField JTFNumeroTicket;
    private javax.swing.JTextField txtUsuario;
    // End of variables declaration//GEN-END:variables
}
