/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Supervisor_Tecnico_Frames;

/**
 *
 * @author Alejandro
 */
public class MenuSupervisorTecnico extends javax.swing.JFrame {

    /**
     * Creates new form MenuSupervisorTecnico
     */
    public MenuSupervisorTecnico() {
        initComponents();
        this.setSize(435, 400); // Fuerza el tamaño exacto
        this.setLocationRelativeTo(null); // Centra la ventana en tu monitor
        JMBSupervisorTecnico.add(javax.swing.Box.createHorizontalGlue(), 2);
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JLBBienvenido = new javax.swing.JLabel();
        JLBSupervisorTecnico = new javax.swing.JLabel();
        JBNNuevoTicket = new javax.swing.JButton();
        JBNAsignarTicket = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        JMBSupervisorTecnico = new javax.swing.JMenuBar();
        JMNSTTickets = new javax.swing.JMenu();
        JMINuevoTicket = new javax.swing.JMenuItem();
        JMIAsignarTicket = new javax.swing.JMenuItem();
        JMIEditarTicket = new javax.swing.JMenuItem();
        JMNSTTecnicos = new javax.swing.JMenu();
        JMIEditarTecnico = new javax.swing.JMenuItem();
        JMNSTCerrarSesion = new javax.swing.JMenu();
        JMICerrarSesion = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        JLBBienvenido.setFont(new java.awt.Font("Montserrat", 1, 24)); // NOI18N
        JLBBienvenido.setForeground(new java.awt.Color(102, 102, 102));
        JLBBienvenido.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        JLBBienvenido.setText("¡Bienvenido!");
        getContentPane().add(JLBBienvenido, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 40, 220, -1));

        JLBSupervisorTecnico.setFont(new java.awt.Font("Montserrat", 1, 24)); // NOI18N
        JLBSupervisorTecnico.setForeground(new java.awt.Color(102, 102, 102));
        JLBSupervisorTecnico.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        JLBSupervisorTecnico.setText("Supervisor Técnico");
        getContentPane().add(JLBSupervisorTecnico, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 70, -1, -1));

        JBNNuevoTicket.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Nuevo Ticke.png"))); // NOI18N
        getContentPane().add(JBNNuevoTicket, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 150, -1, -1));

        JBNAsignarTicket.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Asignar Ticket.png"))); // NOI18N
        getContentPane().add(JBNAsignarTicket, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 150, 79, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/ETS MINI2.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 242, -1, -1));

        JMBSupervisorTecnico.setFont(new java.awt.Font("Montserrat", 0, 12)); // NOI18N

        JMNSTTickets.setText("Tickets");

        JMINuevoTicket.setText("Nuevo Ticket");
        JMINuevoTicket.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JMINuevoTicketActionPerformed(evt);
            }
        });
        JMNSTTickets.add(JMINuevoTicket);

        JMIAsignarTicket.setText("Asignar Ticket");
        JMNSTTickets.add(JMIAsignarTicket);

        JMIEditarTicket.setText("Editar Ticket");
        JMNSTTickets.add(JMIEditarTicket);

        JMBSupervisorTecnico.add(JMNSTTickets);

        JMNSTTecnicos.setText("Técnicos");

        JMIEditarTecnico.setText("Editar Técnico");
        JMNSTTecnicos.add(JMIEditarTecnico);

        JMBSupervisorTecnico.add(JMNSTTecnicos);

        JMNSTCerrarSesion.setText("Cerrar Sesión");

        JMICerrarSesion.setText("Salir");
        JMNSTCerrarSesion.add(JMICerrarSesion);

        JMBSupervisorTecnico.add(JMNSTCerrarSesion);

        setJMenuBar(JMBSupervisorTecnico);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JMINuevoTicketActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JMINuevoTicketActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JMINuevoTicketActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuSupervisorTecnico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuSupervisorTecnico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuSupervisorTecnico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuSupervisorTecnico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
        public void run() {
            MenuSupervisorTecnico vista = new MenuSupervisorTecnico();
            new Supervisor_Tecnico_Controladores.ControladorMenuSupervisor(vista); 
            vista.setVisible(true);
        }
    });
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton JBNAsignarTicket;
    public javax.swing.JButton JBNNuevoTicket;
    public javax.swing.JLabel JLBBienvenido;
    public javax.swing.JLabel JLBSupervisorTecnico;
    private javax.swing.JMenuBar JMBSupervisorTecnico;
    public javax.swing.JMenuItem JMIAsignarTicket;
    public javax.swing.JMenuItem JMICerrarSesion;
    public javax.swing.JMenuItem JMIEditarTecnico;
    public javax.swing.JMenuItem JMIEditarTicket;
    public javax.swing.JMenuItem JMINuevoTicket;
    public javax.swing.JMenu JMNSTCerrarSesion;
    public javax.swing.JMenu JMNSTTecnicos;
    public javax.swing.JMenu JMNSTTickets;
    public javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
