/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Supervisor_Tecnico_Frames;

/**
 *
 * @author suare
 */
public class ModificarTecnico extends javax.swing.JFrame {

    /**
     * Creates new form ModificarTecnico
     */
    public ModificarTecnico() {
        initComponents();
        this.setSize(490, 550); // Fuerza el tamaño exacto
        this.setLocationRelativeTo(null); // Centra la ventana en tu monitor
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JLBEditarTecnico = new javax.swing.JLabel();
        JLBDescripcion1 = new javax.swing.JLabel();
        JLBDescripcion2 = new javax.swing.JLabel();
        JLBDescripcion3 = new javax.swing.JLabel();
        JTFNumeroEmpleado = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        JLSTecnicos = new javax.swing.JList<>();
        JBNSiguienteTF = new javax.swing.JButton();
        JBNSiguienteJLS = new javax.swing.JButton();
        JBNCancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        JLBEditarTecnico.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        JLBEditarTecnico.setForeground(new java.awt.Color(102, 102, 102));
        JLBEditarTecnico.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        JLBEditarTecnico.setText("Editar técnico");
        getContentPane().add(JLBEditarTecnico, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 10, 350, 30));

        JLBDescripcion1.setFont(new java.awt.Font("Montserrat", 1, 18)); // NOI18N
        JLBDescripcion1.setForeground(new java.awt.Color(153, 153, 153));
        JLBDescripcion1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        JLBDescripcion1.setText("Ingrese el numero de empleado");
        getContentPane().add(JLBDescripcion1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 50, 370, 30));

        JLBDescripcion2.setFont(new java.awt.Font("Montserrat", 1, 18)); // NOI18N
        JLBDescripcion2.setForeground(new java.awt.Color(153, 153, 153));
        JLBDescripcion2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        JLBDescripcion2.setText("del técnico o seleccione de la lista");
        getContentPane().add(JLBDescripcion2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 80, 370, 30));

        JLBDescripcion3.setFont(new java.awt.Font("Montserrat", 1, 18)); // NOI18N
        JLBDescripcion3.setForeground(new java.awt.Color(153, 153, 153));
        JLBDescripcion3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        JLBDescripcion3.setText("para editar su información actual");
        getContentPane().add(JLBDescripcion3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 110, 370, 30));

        JTFNumeroEmpleado.setFont(new java.awt.Font("Montserrat", 1, 14)); // NOI18N
        JTFNumeroEmpleado.setForeground(new java.awt.Color(153, 153, 153));
        JTFNumeroEmpleado.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        JTFNumeroEmpleado.setText("Numero de empleado");
        JTFNumeroEmpleado.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        JTFNumeroEmpleado.setPreferredSize(new java.awt.Dimension(150, 30));
        JTFNumeroEmpleado.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                JTFNumeroEmpleadoFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                JTFNumeroEmpleadoFocusLost(evt);
            }
        });
        JTFNumeroEmpleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTFNumeroEmpleadoActionPerformed(evt);
            }
        });
        getContentPane().add(JTFNumeroEmpleado, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 160, 390, -1));

        JLSTecnicos.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        JLSTecnicos.setFont(new java.awt.Font("Montserrat", 0, 12)); // NOI18N
        JLSTecnicos.setForeground(new java.awt.Color(153, 153, 153));
        JLSTecnicos.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "ASCENCIO GARCIA JOSE ALEJANDRO ", "SUAREZ FLORES ISAU", "BEJAR ROSALES NAMUR ALEJANDRO", "MEDINA GARCIA VICTOR IVAN" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(JLSTecnicos);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 290, 400, 110));

        JBNSiguienteTF.setBackground(new java.awt.Color(0, 153, 102));
        JBNSiguienteTF.setFont(new java.awt.Font("Montserrat", 1, 14)); // NOI18N
        JBNSiguienteTF.setForeground(new java.awt.Color(255, 255, 255));
        JBNSiguienteTF.setText("Siguiente");
        JBNSiguienteTF.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(39, 174, 96), 1, true));
        JBNSiguienteTF.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        JBNSiguienteTF.setOpaque(true);
        JBNSiguienteTF.setPreferredSize(new java.awt.Dimension(100, 25));
        JBNSiguienteTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBNSiguienteTFActionPerformed(evt);
            }
        });
        getContentPane().add(JBNSiguienteTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 220, 200, 42));

        JBNSiguienteJLS.setBackground(new java.awt.Color(0, 153, 102));
        JBNSiguienteJLS.setFont(new java.awt.Font("Montserrat", 1, 14)); // NOI18N
        JBNSiguienteJLS.setForeground(new java.awt.Color(255, 255, 255));
        JBNSiguienteJLS.setText("Siguiente");
        JBNSiguienteJLS.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(39, 174, 96), 1, true));
        JBNSiguienteJLS.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        JBNSiguienteJLS.setOpaque(true);
        JBNSiguienteJLS.setPreferredSize(new java.awt.Dimension(100, 25));
        JBNSiguienteJLS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBNSiguienteJLSActionPerformed(evt);
            }
        });
        getContentPane().add(JBNSiguienteJLS, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 420, 200, 42));

        JBNCancelar.setFont(new java.awt.Font("Montserrat", 1, 14)); // NOI18N
        JBNCancelar.setText("Cancelar");
        JBNCancelar.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        JBNCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBNCancelarActionPerformed(evt);
            }
        });
        getContentPane().add(JBNCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 460, 80, 30));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JTFNumeroEmpleadoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_JTFNumeroEmpleadoFocusGained
        if (JTFNumeroEmpleado.getText().equals("Usuario")) {
            JTFNumeroEmpleado.setText("");
            JTFNumeroEmpleado.setForeground(new java.awt.Color(51, 51, 51)); // Letra oscura al escribir
        }
    }//GEN-LAST:event_JTFNumeroEmpleadoFocusGained

    private void JTFNumeroEmpleadoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_JTFNumeroEmpleadoFocusLost
        if (JTFNumeroEmpleado.getText().isEmpty()) {
            JTFNumeroEmpleado.setText("Usuario");
            JTFNumeroEmpleado.setForeground(new java.awt.Color(153, 153, 153)); // Vuelve al gris claro
        }
    }//GEN-LAST:event_JTFNumeroEmpleadoFocusLost

    private void JTFNumeroEmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTFNumeroEmpleadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JTFNumeroEmpleadoActionPerformed

    private void JBNSiguienteTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBNSiguienteTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JBNSiguienteTFActionPerformed

    private void JBNSiguienteJLSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBNSiguienteJLSActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JBNSiguienteJLSActionPerformed

    private void JBNCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBNCancelarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JBNCancelarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ModificarTecnico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ModificarTecnico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ModificarTecnico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ModificarTecnico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ModificarTecnico().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton JBNCancelar;
    public javax.swing.JButton JBNSiguienteJLS;
    public javax.swing.JButton JBNSiguienteTF;
    public javax.swing.JLabel JLBDescripcion1;
    public javax.swing.JLabel JLBDescripcion2;
    public javax.swing.JLabel JLBDescripcion3;
    public javax.swing.JLabel JLBEditarTecnico;
    private javax.swing.JList<String> JLSTecnicos;
    public javax.swing.JTextField JTFNumeroEmpleado;
    public javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
