/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Supervisor_Tecnico_Frames;

/**
 *
 * @author Alejandro
 */
public class ModificarTecnico2 extends javax.swing.JFrame {

    /**
     * Creates new form ModificarTecnico2
     */
    public ModificarTecnico2() {
        initComponents();
        this.setSize(700, 700); // Fuerza el tamaño exacto
        this.setResizable(false);
        this.setLocationRelativeTo(null); // Centra la ventana en tu monitor
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JPFondo = new ImagenPanel_ST("/imagenes/FondoETS.jpg");
        JLBRegistrarTecnico = new javax.swing.JLabel();
        JLBNombre = new javax.swing.JLabel();
        JTFNombre = new javax.swing.JTextField();
        JTFApellido = new javax.swing.JTextField();
        JLBApellido = new javax.swing.JLabel();
        JLBATelefono = new javax.swing.JLabel();
        JTFTelefono = new javax.swing.JTextField();
        JTFCorreo = new javax.swing.JTextField();
        JLBCorreo = new javax.swing.JLabel();
        JLBEspecialidad = new javax.swing.JLabel();
        JCBEspecialidades = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        JBNGuardar = new javax.swing.JButton();
        JBNCancelar = new javax.swing.JButton();
        JCBTecnico = new javax.swing.JComboBox();
        JLBBusqueda = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        JPFondo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        JLBRegistrarTecnico.setFont(new java.awt.Font("Montserrat", 1, 24)); // NOI18N
        JLBRegistrarTecnico.setForeground(new java.awt.Color(102, 102, 102));
        JLBRegistrarTecnico.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        JLBRegistrarTecnico.setText("Modificar Técnico");
        JPFondo.add(JLBRegistrarTecnico, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 680, 40));

        JLBNombre.setFont(new java.awt.Font("Montserrat", 1, 14)); // NOI18N
        JLBNombre.setForeground(new java.awt.Color(102, 102, 102));
        JLBNombre.setText("Nombre (s):");
        JPFondo.add(JLBNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, 100, 40));

        JTFNombre.setForeground(new java.awt.Color(102, 102, 102));
        JTFNombre.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        JTFNombre.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(200, 200, 200), 1, true));
        JTFNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTFNombreActionPerformed(evt);
            }
        });
        JTFNombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                JTFNombreKeyTyped(evt);
            }
        });
        JPFondo.add(JTFNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 220, 520, 40));

        JTFApellido.setForeground(new java.awt.Color(102, 102, 102));
        JTFApellido.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        JTFApellido.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(200, 200, 200), 1, true));
        JTFApellido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTFApellidoActionPerformed(evt);
            }
        });
        JTFApellido.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                JTFApellidoKeyTyped(evt);
            }
        });
        JPFondo.add(JTFApellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 290, 520, 40));

        JLBApellido.setFont(new java.awt.Font("Montserrat", 1, 14)); // NOI18N
        JLBApellido.setForeground(new java.awt.Color(102, 102, 102));
        JLBApellido.setText("Apellido (s)");
        JPFondo.add(JLBApellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 290, 100, 40));

        JLBATelefono.setFont(new java.awt.Font("Montserrat", 1, 14)); // NOI18N
        JLBATelefono.setForeground(new java.awt.Color(102, 102, 102));
        JLBATelefono.setText("Teléfono:");
        JPFondo.add(JLBATelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 360, 100, 40));

        JTFTelefono.setForeground(new java.awt.Color(102, 102, 102));
        JTFTelefono.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        JTFTelefono.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(200, 200, 200), 1, true));
        JTFTelefono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTFTelefonoActionPerformed(evt);
            }
        });
        JTFTelefono.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                JTFTelefonoKeyTyped(evt);
            }
        });
        JPFondo.add(JTFTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 360, 520, 40));

        JTFCorreo.setForeground(new java.awt.Color(102, 102, 102));
        JTFCorreo.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        JTFCorreo.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(200, 200, 200), 1, true));
        JTFCorreo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTFCorreoActionPerformed(evt);
            }
        });
        JTFCorreo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                JTFCorreoKeyTyped(evt);
            }
        });
        JPFondo.add(JTFCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 430, 520, 40));

        JLBCorreo.setFont(new java.awt.Font("Montserrat", 1, 14)); // NOI18N
        JLBCorreo.setForeground(new java.awt.Color(102, 102, 102));
        JLBCorreo.setText("Correo:");
        JPFondo.add(JLBCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 430, 100, 40));

        JLBEspecialidad.setFont(new java.awt.Font("Montserrat", 1, 14)); // NOI18N
        JLBEspecialidad.setForeground(new java.awt.Color(102, 102, 102));
        JLBEspecialidad.setText("Especialidad:");
        JPFondo.add(JLBEspecialidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 500, 100, 40));

        JCBEspecialidades.setForeground(new java.awt.Color(102, 102, 102));
        JCBEspecialidades.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Soporte técnico general", "Soporte de redes", "Soporte de impresoras", "Soporte de portatiles", "Soporte de equipos", "Cableado estructurado" }));
        JCBEspecialidades.setBorder(null);
        JCBEspecialidades.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JCBEspecialidadesActionPerformed(evt);
            }
        });
        JPFondo.add(JCBEspecialidades, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 500, 520, 40));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Logo ETS 75 px.png"))); // NOI18N
        JPFondo.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 590, -1, -1));

        JBNGuardar.setBackground(new java.awt.Color(0, 153, 102));
        JBNGuardar.setFont(new java.awt.Font("Montserrat", 1, 14)); // NOI18N
        JBNGuardar.setForeground(new java.awt.Color(255, 255, 255));
        JBNGuardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/botones/guardar3.png"))); // NOI18N
        JBNGuardar.setText("Guardar");
        JBNGuardar.setBorder(null);
        JBNGuardar.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        JBNGuardar.setIconTextGap(15);
        JBNGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBNGuardarActionPerformed(evt);
            }
        });
        JPFondo.add(JBNGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 580, 225, 45));

        JBNCancelar.setFont(new java.awt.Font("Montserrat", 1, 14)); // NOI18N
        JBNCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/botones/cancelar2.png"))); // NOI18N
        JBNCancelar.setText("Cancelar");
        JBNCancelar.setBorder(null);
        JBNCancelar.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        JBNCancelar.setIconTextGap(10);
        JBNCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBNCancelarActionPerformed(evt);
            }
        });
        JPFondo.add(JBNCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 610, 125, 40));

        JCBTecnico.setForeground(new java.awt.Color(102, 102, 102));
        JCBTecnico.setBorder(null);
        JPFondo.add(JCBTecnico, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 650, 40));

        JLBBusqueda.setFont(new java.awt.Font("Montserrat", 1, 14)); // NOI18N
        JLBBusqueda.setForeground(new java.awt.Color(102, 102, 102));
        JLBBusqueda.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        JLBBusqueda.setText("Técnico");
        JPFondo.add(JLBBusqueda, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 80, 40));

        jSeparator2.setAlignmentX(1.0F);
        jSeparator2.setAlignmentY(1.0F);
        JPFondo.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 80, 590, 10));

        jSeparator3.setAlignmentX(1.0F);
        jSeparator3.setAlignmentY(1.0F);
        JPFondo.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 20, 10));

        jLabel3.setFont(new java.awt.Font("Montserrat", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(153, 153, 153));
        jLabel3.setText("Seleccione el Técnico que desea modificar");
        JPFondo.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, 600, 30));

        jSeparator1.setAlignmentX(1.0F);
        jSeparator1.setAlignmentY(1.0F);
        JPFondo.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 190, 690, 10));

        getContentPane().add(JPFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 660));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JCBEspecialidadesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JCBEspecialidadesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JCBEspecialidadesActionPerformed

    private void JBNCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBNCancelarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JBNCancelarActionPerformed

    private void JTFNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTFNombreActionPerformed
        // TODO add your handling code here:
        JTFNombre.addActionListener(e -> JTFApellido.requestFocus());
    }//GEN-LAST:event_JTFNombreActionPerformed

    private void JTFApellidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTFApellidoActionPerformed
        // TODO add your handling code here:
        JTFApellido.addActionListener(e -> JTFTelefono.requestFocus());
    }//GEN-LAST:event_JTFApellidoActionPerformed

    private void JTFTelefonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTFTelefonoActionPerformed
        // TODO add your handling code here:
        JTFTelefono.addActionListener(e -> JTFCorreo.requestFocus());
    }//GEN-LAST:event_JTFTelefonoActionPerformed

    private void JTFCorreoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTFCorreoActionPerformed
        // TODO add your handling code here:
        JTFCorreo.addActionListener(e -> JCBEspecialidades.requestFocus());
    }//GEN-LAST:event_JTFCorreoActionPerformed

    private void JTFNombreKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_JTFNombreKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        javax.swing.JTextField field = (javax.swing.JTextField) evt.getSource();
        if (!(Character.isLetter(c) || c == ' ' || Character.isISOControl(c)) || field.getText().length() >= 50) {
            evt.consume();
        }
    }//GEN-LAST:event_JTFNombreKeyTyped

    private void JTFApellidoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_JTFApellidoKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        javax.swing.JTextField field = (javax.swing.JTextField) evt.getSource();
        if (!(Character.isLetter(c) || c == ' ' || Character.isISOControl(c)) || field.getText().length() >= 50) {
            evt.consume();
        }
    }//GEN-LAST:event_JTFApellidoKeyTyped

    private void JTFTelefonoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_JTFTelefonoKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if (!Character.isDigit(c) || JTFTelefono.getText().length() >= 10) {
            evt.consume();
        }
    }//GEN-LAST:event_JTFTelefonoKeyTyped

    private void JTFCorreoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_JTFCorreoKeyTyped
        // TODO add your handling code here:
        if (((javax.swing.JTextField) evt.getSource()).getText().length() >= 100) {
            evt.consume();
        }
    }//GEN-LAST:event_JTFCorreoKeyTyped

    private void JBNGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBNGuardarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JBNGuardarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ModificarTecnico2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ModificarTecnico2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ModificarTecnico2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ModificarTecnico2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ModificarTecnico2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton JBNCancelar;
    public javax.swing.JButton JBNGuardar;
    public javax.swing.JComboBox<String> JCBEspecialidades;
    public javax.swing.JComboBox JCBTecnico;
    public javax.swing.JLabel JLBATelefono;
    public javax.swing.JLabel JLBApellido;
    public javax.swing.JLabel JLBBusqueda;
    public javax.swing.JLabel JLBCorreo;
    public javax.swing.JLabel JLBEspecialidad;
    public javax.swing.JLabel JLBNombre;
    private javax.swing.JLabel JLBRegistrarTecnico;
    private javax.swing.JPanel JPFondo;
    public javax.swing.JTextField JTFApellido;
    public javax.swing.JTextField JTFCorreo;
    public javax.swing.JTextField JTFNombre;
    public javax.swing.JTextField JTFTelefono;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    // End of variables declaration//GEN-END:variables
}
