/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Supervisor_Tecnico_Frames;

/**
 *
 * @author Alejandro
 */
public class ModificarTicket2 extends javax.swing.JFrame {

    /**
     * Creates new form ModificarTicket2
     */
    public ModificarTicket2() {
        initComponents();
        this.setSize(775, 650); // Fuerza el tamaño exacto
        this.setLocationRelativeTo(null); // Centra la ventana en tu monitor
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        RBGTipoServicio = new javax.swing.ButtonGroup();
        JLBDescripcion = new javax.swing.JLabel();
        JTADescripcion = new javax.swing.JTextField();
        JLBDescripcion3 = new javax.swing.JLabel();
        JCBTecnico = new javax.swing.JComboBox();
        JLBLogo = new javax.swing.JLabel();
        JLBAsignarTecnico = new javax.swing.JLabel();
        JBNCancelar = new javax.swing.JButton();
        JLBDescripcion1 = new javax.swing.JLabel();
        JTFEmpresa = new javax.swing.JTextField();
        JCBFinalizado = new javax.swing.JCheckBox();
        JBNSiguienteJLS3 = new javax.swing.JButton();
        JTFConcepto = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        JLBNombre2 = new javax.swing.JLabel();
        JRBPresencial1 = new javax.swing.JRadioButton();
        JRBRemoto = new javax.swing.JRadioButton();
        JRBAsesoria = new javax.swing.JRadioButton();
        JLBNombre3 = new javax.swing.JLabel();
        JLBNombre4 = new javax.swing.JLabel();
        JLBNombre5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        JLBDescripcion.setFont(new java.awt.Font("Montserrat", 1, 12)); // NOI18N
        JLBDescripcion.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        JLBDescripcion.setText("Detalles del ticket:");
        getContentPane().add(JLBDescripcion, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 300, 125, -1));

        JTADescripcion.setFont(new java.awt.Font("Montserrat", 1, 12)); // NOI18N
        JTADescripcion.setForeground(new java.awt.Color(153, 153, 153));
        JTADescripcion.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        JTADescripcion.setText("Descripción de los servicios a realizar y detalles puntuales");
        JTADescripcion.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        JTADescripcion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTADescripcionActionPerformed(evt);
            }
        });
        JTADescripcion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                JTADescripcionKeyTyped(evt);
            }
        });
        getContentPane().add(JTADescripcion, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 330, 600, 129));

        JLBDescripcion3.setFont(new java.awt.Font("Montserrat", 1, 14)); // NOI18N
        JLBDescripcion3.setForeground(new java.awt.Color(153, 153, 153));
        JLBDescripcion3.setText("Técnico");
        getContentPane().add(JLBDescripcion3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 90, 40));

        JCBTecnico.setFont(new java.awt.Font("Montserrat", 1, 12)); // NOI18N
        JCBTecnico.setForeground(new java.awt.Color(153, 153, 153));
        JCBTecnico.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Ascencio", " " }));
        JCBTecnico.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        JCBTecnico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JCBTecnicoActionPerformed(evt);
            }
        });
        getContentPane().add(JCBTecnico, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 140, 170, 40));

        JLBLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Logo ETS 75 px.png"))); // NOI18N
        getContentPane().add(JLBLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 570, -1, -1));

        JLBAsignarTecnico.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        JLBAsignarTecnico.setForeground(new java.awt.Color(102, 102, 102));
        JLBAsignarTecnico.setText("Editar Ticket");
        getContentPane().add(JLBAsignarTecnico, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 20, -1, -1));

        JBNCancelar.setFont(new java.awt.Font("Montserrat", 1, 14)); // NOI18N
        JBNCancelar.setText("Cancelar");
        JBNCancelar.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        JBNCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBNCancelarActionPerformed(evt);
            }
        });
        getContentPane().add(JBNCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 560, 80, 29));

        JLBDescripcion1.setFont(new java.awt.Font("Montserrat", 1, 14)); // NOI18N
        JLBDescripcion1.setForeground(new java.awt.Color(153, 153, 153));
        JLBDescripcion1.setText("Solicita ");
        getContentPane().add(JLBDescripcion1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 90, 40));

        JTFEmpresa.setFont(new java.awt.Font("Montserrat", 1, 12)); // NOI18N
        JTFEmpresa.setForeground(new java.awt.Color(153, 153, 153));
        JTFEmpresa.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        JTFEmpresa.setText("Macias y Aso");
        JTFEmpresa.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        JTFEmpresa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTFEmpresaActionPerformed(evt);
            }
        });
        getContentPane().add(JTFEmpresa, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 80, 230, 40));

        JCBFinalizado.setFont(new java.awt.Font("Montserrat", 1, 14)); // NOI18N
        JCBFinalizado.setText("  ¿Ticket Finalizado?");
        JCBFinalizado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JCBFinalizadoActionPerformed(evt);
            }
        });
        getContentPane().add(JCBFinalizado, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 490, 220, -1));

        JBNSiguienteJLS3.setBackground(new java.awt.Color(0, 153, 102));
        JBNSiguienteJLS3.setFont(new java.awt.Font("Montserrat", 1, 14)); // NOI18N
        JBNSiguienteJLS3.setForeground(new java.awt.Color(255, 255, 255));
        JBNSiguienteJLS3.setText("Siguiente");
        JBNSiguienteJLS3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(39, 174, 96), 1, true));
        JBNSiguienteJLS3.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        JBNSiguienteJLS3.setOpaque(true);
        JBNSiguienteJLS3.setPreferredSize(new java.awt.Dimension(100, 25));
        JBNSiguienteJLS3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBNSiguienteJLS3ActionPerformed(evt);
            }
        });
        getContentPane().add(JBNSiguienteJLS3, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 540, 200, 42));

        JTFConcepto.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        JTFConcepto.setText("Concepto");
        JTFConcepto.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                JTFConceptoFocusGained(evt);
            }
        });
        JTFConcepto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTFConceptoActionPerformed(evt);
            }
        });
        JTFConcepto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                JTFConceptoKeyTyped(evt);
            }
        });
        getContentPane().add(JTFConcepto, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 250, 400, -1));

        jLabel1.setText("Concepto");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 250, -1, -1));

        JLBNombre2.setFont(new java.awt.Font("Montserrat", 1, 14)); // NOI18N
        JLBNombre2.setForeground(new java.awt.Color(153, 153, 153));
        JLBNombre2.setText("Tipo de Servicio");
        getContentPane().add(JLBNombre2, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 140, -1, -1));

        RBGTipoServicio.add(JRBPresencial1);
        JRBPresencial1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JRBPresencial1ActionPerformed(evt);
            }
        });
        getContentPane().add(JRBPresencial1, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 120, -1, -1));

        RBGTipoServicio.add(JRBRemoto);
        getContentPane().add(JRBRemoto, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 140, -1, -1));

        RBGTipoServicio.add(JRBAsesoria);
        getContentPane().add(JRBAsesoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 160, -1, -1));

        JLBNombre3.setFont(new java.awt.Font("Montserrat", 1, 14)); // NOI18N
        JLBNombre3.setText("Presencial");
        getContentPane().add(JLBNombre3, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 120, 120, 20));

        JLBNombre4.setFont(new java.awt.Font("Montserrat", 1, 14)); // NOI18N
        JLBNombre4.setText("Remoto");
        getContentPane().add(JLBNombre4, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 140, 120, 20));

        JLBNombre5.setFont(new java.awt.Font("Montserrat", 1, 14)); // NOI18N
        JLBNombre5.setText("Asesoria");
        getContentPane().add(JLBNombre5, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 160, 120, 20));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JCBTecnicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JCBTecnicoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JCBTecnicoActionPerformed

    private void JBNCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBNCancelarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JBNCancelarActionPerformed

    private void JTFEmpresaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTFEmpresaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JTFEmpresaActionPerformed

    private void JCBFinalizadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JCBFinalizadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JCBFinalizadoActionPerformed

    private void JBNSiguienteJLS3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBNSiguienteJLS3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JBNSiguienteJLS3ActionPerformed

    private void JRBPresencial1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JRBPresencial1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JRBPresencial1ActionPerformed

    private void JTADescripcionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTADescripcionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JTADescripcionActionPerformed

    private void JTFConceptoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_JTFConceptoKeyTyped
        // TODO add your handling code here:
        if (((javax.swing.JTextField) evt.getSource()).getText().length() >= 100) {
            evt.consume();
        }
    }//GEN-LAST:event_JTFConceptoKeyTyped

    private void JTFConceptoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_JTFConceptoFocusGained
        // TODO add your handling code here:
        
    }//GEN-LAST:event_JTFConceptoFocusGained

    private void JTFConceptoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTFConceptoActionPerformed
        // TODO add your handling code here:
        JTFConcepto.addActionListener(e -> JTADescripcion.requestFocus());
    }//GEN-LAST:event_JTFConceptoActionPerformed

    private void JTADescripcionKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_JTADescripcionKeyTyped
        // TODO add your handling code here:
        if (((javax.swing.JTextArea) evt.getSource()).getText().length() >= 240) {
            evt.consume();
        }
    }//GEN-LAST:event_JTADescripcionKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ModificarTicket2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ModificarTicket2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ModificarTicket2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ModificarTicket2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ModificarTicket2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton JBNCancelar;
    public javax.swing.JButton JBNSiguienteJLS3;
    public javax.swing.JCheckBox JCBFinalizado;
    public javax.swing.JComboBox JCBTecnico;
    public javax.swing.JLabel JLBAsignarTecnico;
    public javax.swing.JLabel JLBDescripcion;
    public javax.swing.JLabel JLBDescripcion1;
    public javax.swing.JLabel JLBDescripcion3;
    public javax.swing.JLabel JLBLogo;
    public javax.swing.JLabel JLBNombre2;
    public javax.swing.JLabel JLBNombre3;
    public javax.swing.JLabel JLBNombre4;
    public javax.swing.JLabel JLBNombre5;
    public javax.swing.JRadioButton JRBAsesoria;
    public javax.swing.JRadioButton JRBPresencial1;
    public javax.swing.JRadioButton JRBRemoto;
    public javax.swing.JTextField JTADescripcion;
    public javax.swing.JTextField JTFConcepto;
    public javax.swing.JTextField JTFEmpresa;
    private javax.swing.ButtonGroup RBGTipoServicio;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
