/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Supervisor_Tecnico_Frames;

/**
 *
 * @author Alejandro
 */
public class NuevoTicket extends javax.swing.JFrame {

    /**
     * Creates new form NuevoTicket
     */
    public NuevoTicket() {
        initComponents();
        this.setLocationRelativeTo(null); // Centra la ventana en tu monitor
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JBGTipoServicio = new javax.swing.ButtonGroup();
        JLBNuevoTicket = new javax.swing.JLabel();
        JLBDescripcion1 = new javax.swing.JLabel();
        JLBDescripcion2 = new javax.swing.JLabel();
        JLBDescripcion3 = new javax.swing.JLabel();
        JTFNumeroDePoliza = new javax.swing.JTextField();
        JBNCancelar = new javax.swing.JButton();
        JLBLogo = new javax.swing.JLabel();
        JBNSiguienteJLS3 = new javax.swing.JButton();
        JLBNombre2 = new javax.swing.JLabel();
        JRBEscencial = new javax.swing.JRadioButton();
        JRBProfesional = new javax.swing.JRadioButton();
        JRBEmpresarial = new javax.swing.JRadioButton();
        JLBNombre3 = new javax.swing.JLabel();
        JLBNombre4 = new javax.swing.JLabel();
        JLBNombre5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        JLBNuevoTicket.setFont(new java.awt.Font("Montserrat", 1, 24)); // NOI18N
        JLBNuevoTicket.setForeground(new java.awt.Color(102, 102, 102));
        JLBNuevoTicket.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        JLBNuevoTicket.setText("Nuevo Ticket");
        getContentPane().add(JLBNuevoTicket, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 20, -1, -1));

        JLBDescripcion1.setFont(new java.awt.Font("Montserrat", 1, 18)); // NOI18N
        JLBDescripcion1.setForeground(new java.awt.Color(153, 153, 153));
        JLBDescripcion1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        JLBDescripcion1.setText("Ingrese el numero de póliza");
        getContentPane().add(JLBDescripcion1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 60, 290, -1));

        JLBDescripcion2.setFont(new java.awt.Font("Montserrat", 1, 18)); // NOI18N
        JLBDescripcion2.setForeground(new java.awt.Color(153, 153, 153));
        JLBDescripcion2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        JLBDescripcion2.setText("del solicitante y modalidad");
        getContentPane().add(JLBDescripcion2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 90, 290, -1));

        JLBDescripcion3.setFont(new java.awt.Font("Montserrat", 1, 18)); // NOI18N
        JLBDescripcion3.setForeground(new java.awt.Color(153, 153, 153));
        JLBDescripcion3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        JLBDescripcion3.setText("de atención requerida");
        getContentPane().add(JLBDescripcion3, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 120, 290, 20));

        JTFNumeroDePoliza.setFont(new java.awt.Font("Montserrat ExtraLight", 1, 12)); // NOI18N
        JTFNumeroDePoliza.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        JTFNumeroDePoliza.setText("Numero de poliza");
        JTFNumeroDePoliza.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        JTFNumeroDePoliza.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTFNumeroDePolizaActionPerformed(evt);
            }
        });
        getContentPane().add(JTFNumeroDePoliza, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 160, 310, 50));

        JBNCancelar.setFont(new java.awt.Font("Montserrat", 1, 14)); // NOI18N
        JBNCancelar.setText("Cancelar");
        JBNCancelar.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        getContentPane().add(JBNCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 440, 80, 30));

        JLBLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Logo ETS 75 px.png"))); // NOI18N
        getContentPane().add(JLBLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 410, -1, -1));

        JBNSiguienteJLS3.setBackground(new java.awt.Color(0, 153, 102));
        JBNSiguienteJLS3.setFont(new java.awt.Font("Montserrat", 1, 14)); // NOI18N
        JBNSiguienteJLS3.setForeground(new java.awt.Color(255, 255, 255));
        JBNSiguienteJLS3.setText("Guardar");
        JBNSiguienteJLS3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(39, 174, 96), 1, true));
        JBNSiguienteJLS3.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        JBNSiguienteJLS3.setOpaque(true);
        JBNSiguienteJLS3.setPreferredSize(new java.awt.Dimension(100, 25));
        JBNSiguienteJLS3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBNSiguienteJLS3ActionPerformed(evt);
            }
        });
        getContentPane().add(JBNSiguienteJLS3, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 390, 200, 42));

        JLBNombre2.setFont(new java.awt.Font("Montserrat", 1, 14)); // NOI18N
        JLBNombre2.setForeground(new java.awt.Color(153, 153, 153));
        JLBNombre2.setText("Tipo de Servicio");
        getContentPane().add(JLBNombre2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 220, -1, -1));

        JRBEscencial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JRBEscencialActionPerformed(evt);
            }
        });
        getContentPane().add(JRBEscencial, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 260, -1, -1));
        getContentPane().add(JRBProfesional, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 300, -1, -1));
        getContentPane().add(JRBEmpresarial, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 340, -1, -1));

        JLBNombre3.setFont(new java.awt.Font("Montserrat", 1, 14)); // NOI18N
        JLBNombre3.setText("Escencial");
        getContentPane().add(JLBNombre3, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 260, 120, 20));

        JLBNombre4.setFont(new java.awt.Font("Montserrat", 1, 14)); // NOI18N
        JLBNombre4.setText("Profesional");
        getContentPane().add(JLBNombre4, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 300, 120, 20));

        JLBNombre5.setFont(new java.awt.Font("Montserrat", 1, 14)); // NOI18N
        JLBNombre5.setText("Empresarial");
        getContentPane().add(JLBNombre5, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 340, 120, 20));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JTFNumeroDePolizaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTFNumeroDePolizaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JTFNumeroDePolizaActionPerformed

    private void JBNSiguienteJLS3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBNSiguienteJLS3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JBNSiguienteJLS3ActionPerformed

    private void JRBEscencialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JRBEscencialActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JRBEscencialActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NuevoTicket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NuevoTicket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NuevoTicket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NuevoTicket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

/* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                NuevoTicket vistaNuevoTicket = new NuevoTicket();
                // Conectamos el controlador para que la vista no esté "sorda"
                Supervisor_Tecnico_Controladores.ControladorNuevoTicket ctrl = new Supervisor_Tecnico_Controladores.ControladorNuevoTicket(vistaNuevoTicket);
                vistaNuevoTicket.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup JBGTipoServicio;
    public javax.swing.JButton JBNCancelar;
    public javax.swing.JButton JBNSiguienteJLS3;
    public javax.swing.JLabel JLBDescripcion1;
    public javax.swing.JLabel JLBDescripcion2;
    public javax.swing.JLabel JLBDescripcion3;
    public javax.swing.JLabel JLBLogo;
    public javax.swing.JLabel JLBNombre2;
    public javax.swing.JLabel JLBNombre3;
    public javax.swing.JLabel JLBNombre4;
    public javax.swing.JLabel JLBNombre5;
    public javax.swing.JLabel JLBNuevoTicket;
    public javax.swing.JRadioButton JRBEmpresarial;
    public javax.swing.JRadioButton JRBEscencial;
    public javax.swing.JRadioButton JRBProfesional;
    public javax.swing.JTextField JTFNumeroDePoliza;
    // End of variables declaration//GEN-END:variables
}
