/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Supervisor_Tecnico_Frames;

/**
 *
 * @author Alejandro
 */
public class NuevoTicket extends javax.swing.JFrame {

    /**
     * Creates new form NuevoTicket
     */
    public NuevoTicket() {
        initComponents();
        this.setSize(800, 600); // Fuerza el tamaño exacto
        this.setResizable(false);
        this.setLocationRelativeTo(null); // Centra la ventana en tu monitor
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JBGTipoServicio = new javax.swing.ButtonGroup();
        JPFondo = new ImagenPanel_ST("/imagenes/FondoETS.jpg");
        JLBNuevoTicket = new javax.swing.JLabel();
        JBNCancelar = new javax.swing.JButton();
        JLBLogo = new javax.swing.JLabel();
        JBNSiguienteJLS3 = new javax.swing.JButton();
        JRBPresencial = new javax.swing.JRadioButton();
        JRBRemoto = new javax.swing.JRadioButton();
        JRBAsesoria = new javax.swing.JRadioButton();
        JLBNombre3 = new javax.swing.JLabel();
        JLBNombre4 = new javax.swing.JLabel();
        JLBNombre5 = new javax.swing.JLabel();
        JTFusuario = new javax.swing.JTextField();
        JCBUsuario = new javax.swing.JComboBox<>();
        JLBNombre = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        JLBBusqueda = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        JLBNombre6 = new javax.swing.JLabel();
        JLBNombre7 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jSeparator5 = new javax.swing.JSeparator();
        JLBBusqueda1 = new javax.swing.JLabel();
        jSeparator6 = new javax.swing.JSeparator();
        jSeparator8 = new javax.swing.JSeparator();
        jSeparator7 = new javax.swing.JSeparator();
        jSeparator1 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        JPFondo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        JLBNuevoTicket.setFont(new java.awt.Font("Montserrat", 1, 24)); // NOI18N
        JLBNuevoTicket.setForeground(new java.awt.Color(102, 102, 102));
        JLBNuevoTicket.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        JLBNuevoTicket.setText("Nuevo Ticket");
        JPFondo.add(JLBNuevoTicket, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 780, 40));

        JBNCancelar.setFont(new java.awt.Font("Montserrat", 1, 14)); // NOI18N
        JBNCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/botones/cancelar2.png"))); // NOI18N
        JBNCancelar.setText("Cancelar");
        JBNCancelar.setBorder(null);
        JBNCancelar.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        JBNCancelar.setIconTextGap(10);
        JPFondo.add(JBNCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 520, 125, 40));

        JLBLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Logo ETS 75 px.png"))); // NOI18N
        JPFondo.add(JLBLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 490, -1, -1));

        JBNSiguienteJLS3.setBackground(new java.awt.Color(0, 153, 102));
        JBNSiguienteJLS3.setFont(new java.awt.Font("Montserrat", 1, 14)); // NOI18N
        JBNSiguienteJLS3.setForeground(new java.awt.Color(255, 255, 255));
        JBNSiguienteJLS3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/botones/siguiente1.png"))); // NOI18N
        JBNSiguienteJLS3.setText("Siguiente");
        JBNSiguienteJLS3.setBorder(null);
        JBNSiguienteJLS3.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        JBNSiguienteJLS3.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        JBNSiguienteJLS3.setIconTextGap(15);
        JBNSiguienteJLS3.setPreferredSize(new java.awt.Dimension(100, 25));
        JBNSiguienteJLS3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBNSiguienteJLS3ActionPerformed(evt);
            }
        });
        JPFondo.add(JBNSiguienteJLS3, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 490, 225, 45));

        JRBPresencial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JRBPresencialActionPerformed(evt);
            }
        });
        JPFondo.add(JRBPresencial, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 260, -1, -1));
        JPFondo.add(JRBRemoto, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 300, -1, -1));
        JPFondo.add(JRBAsesoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 340, -1, -1));

        JLBNombre3.setFont(new java.awt.Font("Montserrat", 1, 14)); // NOI18N
        JLBNombre3.setText("Presencial");
        JPFondo.add(JLBNombre3, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 260, 120, 20));

        JLBNombre4.setFont(new java.awt.Font("Montserrat", 1, 14)); // NOI18N
        JLBNombre4.setText("Remoto");
        JPFondo.add(JLBNombre4, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 300, 120, 20));

        JLBNombre5.setFont(new java.awt.Font("Montserrat", 1, 14)); // NOI18N
        JLBNombre5.setText("Asesoria");
        JPFondo.add(JLBNombre5, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 340, 120, 20));

        JTFusuario.setForeground(new java.awt.Color(102, 102, 102));
        JTFusuario.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        JTFusuario.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(200, 200, 200), 1, true));
        JTFusuario.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                JTFusuarioFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                JTFusuarioFocusLost(evt);
            }
        });
        JTFusuario.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                JTFusuarioKeyTyped(evt);
            }
        });
        JPFondo.add(JTFusuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, 370, 40));

        JCBUsuario.setForeground(new java.awt.Color(102, 102, 102));
        JPFondo.add(JCBUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 360, 370, 40));

        JLBNombre.setFont(new java.awt.Font("Montserrat", 1, 14)); // NOI18N
        JLBNombre.setForeground(new java.awt.Color(153, 153, 153));
        JLBNombre.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        JLBNombre.setText("Ingrese los datos de busqueda y seleccione al usuario y el tipo de servicio que se requiere");
        JPFondo.add(JLBNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 790, 20));

        jSeparator3.setAlignmentX(1.0F);
        jSeparator3.setAlignmentY(1.0F);
        JPFondo.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 130, 30, 10));

        JLBBusqueda.setFont(new java.awt.Font("Montserrat", 1, 14)); // NOI18N
        JLBBusqueda.setForeground(new java.awt.Color(102, 102, 102));
        JLBBusqueda.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        JLBBusqueda.setText("Busqueda de Usuario");
        JPFondo.add(JLBBusqueda, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, 170, 40));

        jSeparator4.setAlignmentX(1.0F);
        jSeparator4.setAlignmentY(1.0F);
        JPFondo.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 130, 210, 10));

        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jSeparator2.setAlignmentX(1.0F);
        jSeparator2.setAlignmentY(1.0F);
        JPFondo.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 130, 10, 121));

        JLBNombre6.setFont(new java.awt.Font("Montserrat", 1, 14)); // NOI18N
        JLBNombre6.setForeground(new java.awt.Color(153, 153, 153));
        JLBNombre6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        JLBNombre6.setText("Seleccione el tipo de servicio que requiere");
        JPFondo.add(JLBNombre6, new org.netbeans.lib.awtextra.AbsoluteConstraints(417, 220, 370, -1));

        JLBNombre7.setFont(new java.awt.Font("Montserrat", 1, 24)); // NOI18N
        JLBNombre7.setForeground(new java.awt.Color(102, 102, 102));
        JLBNombre7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        JLBNombre7.setText("Tipo de Servicio");
        JPFondo.add(JLBNombre7, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 180, 370, -1));

        jLabel3.setFont(new java.awt.Font("Montserrat", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(153, 153, 153));
        jLabel3.setText("Ingrese el nombre del usuario solicitante");
        JPFondo.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, 370, 40));

        jLabel1.setFont(new java.awt.Font("Montserrat", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(153, 153, 153));
        jLabel1.setText("Seleccione el usuario correspondiente a su busqueda");
        JPFondo.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 320, 370, 40));

        jSeparator5.setAlignmentX(1.0F);
        jSeparator5.setAlignmentY(1.0F);
        JPFondo.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 300, 220, 10));

        JLBBusqueda1.setFont(new java.awt.Font("Montserrat", 1, 14)); // NOI18N
        JLBBusqueda1.setForeground(new java.awt.Color(102, 102, 102));
        JLBBusqueda1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        JLBBusqueda1.setText("Selección de Usuario");
        JPFondo.add(JLBBusqueda1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 280, 160, 40));

        jSeparator6.setAlignmentX(1.0F);
        jSeparator6.setAlignmentY(1.0F);
        JPFondo.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 300, 30, 10));

        jSeparator8.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jSeparator8.setAlignmentX(1.0F);
        jSeparator8.setAlignmentY(1.0F);
        JPFondo.add(jSeparator8, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 300, 10, 121));

        jSeparator7.setAlignmentX(1.0F);
        jSeparator7.setAlignmentY(1.0F);
        JPFondo.add(jSeparator7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 420, 410, 10));

        jSeparator1.setAlignmentX(1.0F);
        jSeparator1.setAlignmentY(1.0F);
        JPFondo.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 250, 410, 10));

        getContentPane().add(JPFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 790, 570));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void JBNSiguienteJLS3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBNSiguienteJLS3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JBNSiguienteJLS3ActionPerformed

    private void JRBPresencialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JRBPresencialActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JRBPresencialActionPerformed

    private void JTFusuarioFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_JTFusuarioFocusGained
        // TODO add your handling code here:
        if (JTFusuario.getText().equals("Usuario")) {
            JTFusuario.setText("");
            JTFusuario.setForeground(new java.awt.Color(205, 205, 205));
        }
    }//GEN-LAST:event_JTFusuarioFocusGained

    private void JTFusuarioFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_JTFusuarioFocusLost
        // TODO add your handling code here:
        if (JTFusuario.getText().isEmpty()) {
            JTFusuario.setText("Usuario");
            JTFusuario.setForeground(new java.awt.Color(153, 153, 153));
        }
    }//GEN-LAST:event_JTFusuarioFocusLost

    private void JTFusuarioKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_JTFusuarioKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        javax.swing.JTextField field = (javax.swing.JTextField) evt.getSource();
        if (!(Character.isLetter(c) || c == ' ' || Character.isISOControl(c)) || field.getText().length() >= 50) {
            evt.consume();
        }
    }//GEN-LAST:event_JTFusuarioKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NuevoTicket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NuevoTicket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NuevoTicket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NuevoTicket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

/* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                NuevoTicket vistaNuevoTicket = new NuevoTicket();
                // Conectamos el controlador para que la vista no esté "sorda"
                Supervisor_Tecnico_Controladores.ControladorNuevoTicket ctrl = new Supervisor_Tecnico_Controladores.ControladorNuevoTicket(vistaNuevoTicket);
                vistaNuevoTicket.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup JBGTipoServicio;
    public javax.swing.JButton JBNCancelar;
    public javax.swing.JButton JBNSiguienteJLS3;
    public javax.swing.JComboBox<String> JCBUsuario;
    public javax.swing.JLabel JLBBusqueda;
    public javax.swing.JLabel JLBBusqueda1;
    public javax.swing.JLabel JLBLogo;
    public javax.swing.JLabel JLBNombre;
    public javax.swing.JLabel JLBNombre3;
    public javax.swing.JLabel JLBNombre4;
    public javax.swing.JLabel JLBNombre5;
    public javax.swing.JLabel JLBNombre6;
    public javax.swing.JLabel JLBNombre7;
    public javax.swing.JLabel JLBNuevoTicket;
    private javax.swing.JPanel JPFondo;
    public javax.swing.JRadioButton JRBAsesoria;
    public javax.swing.JRadioButton JRBPresencial;
    public javax.swing.JRadioButton JRBRemoto;
    public javax.swing.JTextField JTFusuario;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    // End of variables declaration//GEN-END:variables
}
