/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Tecnico_Frames;

/**
 *
 * @author suare
 */
public class CambioPass extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(CambioPass.class.getName());

    /**
     * Creates new form CambioPass
     */
    public CambioPass() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        JPWCambio = new javax.swing.JPasswordField();
        jLabel3 = new javax.swing.JLabel();
        JPWConfirmacion = new javax.swing.JPasswordField();
        JBNConfirmar = new javax.swing.JButton();
        JBNcancelar = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        JPWPassActual = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Cambio de contraseña");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(169, 29, 164, -1));

        jLabel2.setText("Escribe la nueva contraseña");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, 182, -1));

        JPWCambio.setText("jPasswordField1");
        getContentPane().add(JPWCambio, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 140, 190, 30));

        jLabel3.setText("Confirma tu nueva contraseña");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, -1, -1));

        JPWConfirmacion.setText("jPasswordField1");
        getContentPane().add(JPWConfirmacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 180, 190, 30));

        JBNConfirmar.setText("Confirmar");
        getContentPane().add(JBNConfirmar, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 260, 110, 40));

        JBNcancelar.setText("Cancelar");
        getContentPane().add(JBNcancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 280, -1, -1));

        jLabel4.setText("Contraseña Actual");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 80, -1, -1));

        JPWPassActual.setText("jPasswordField1");
        getContentPane().add(JPWPassActual, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 80, 200, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new CambioPass().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton JBNConfirmar;
    public javax.swing.JButton JBNcancelar;
    public javax.swing.JPasswordField JPWCambio;
    public javax.swing.JPasswordField JPWConfirmacion;
    public javax.swing.JPasswordField JPWPassActual;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    // End of variables declaration//GEN-END:variables
}
