/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Tecnico_Frames;

/**
 *
 * @author suare
 */
public class MisTickets extends javax.swing.JFrame {

    /**
     * Creates new form MisTickets
     */
    public MisTickets() {
        initComponents();
        this.setSize(495, 550); // Fuerza el tamaño exacto
        this.setLocationRelativeTo(null); // Centra la ventana en tu monitor
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JCBTicketsA = new javax.swing.JComboBox<>();
        JLBMisTickets = new javax.swing.JLabel();
        JCBTicketsR = new javax.swing.JComboBox<>();
        JCBTicketsP = new javax.swing.JComboBox<>();
        JBNCancelar = new javax.swing.JButton();
        JBNSiguienteJLS4 = new javax.swing.JButton();
        JBNSiguienteJLS3 = new javax.swing.JButton();
        JBNSiguienteJLS2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        JCBTicketsA.setFont(new java.awt.Font("Montserrat", 0, 14)); // NOI18N
        JCBTicketsA.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tickets de asesoria", "Ticket", "Ticket", "Ticket" }));
        JCBTicketsA.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 153), 2, true));
        getContentPane().add(JCBTicketsA, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 70, 330, 50));

        JLBMisTickets.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        JLBMisTickets.setForeground(new java.awt.Color(102, 102, 102));
        JLBMisTickets.setText("Mis Tickets");
        getContentPane().add(JLBMisTickets, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 20, -1, -1));

        JCBTicketsR.setFont(new java.awt.Font("Montserrat", 0, 14)); // NOI18N
        JCBTicketsR.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tickets remotos", "Ticket", "Ticket", "Ticket" }));
        JCBTicketsR.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 153), 2, true));
        getContentPane().add(JCBTicketsR, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 200, 330, 50));

        JCBTicketsP.setFont(new java.awt.Font("Montserrat", 0, 14)); // NOI18N
        JCBTicketsP.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tickets presenciales", "Ticket", "Ticket", "Ticket" }));
        JCBTicketsP.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 153), 2, true));
        getContentPane().add(JCBTicketsP, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 330, 330, 50));

        JBNCancelar.setFont(new java.awt.Font("Montserrat", 1, 14)); // NOI18N
        JBNCancelar.setText("Cancelar");
        JBNCancelar.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        JBNCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBNCancelarActionPerformed(evt);
            }
        });
        getContentPane().add(JBNCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 460, 90, 30));

        JBNSiguienteJLS4.setBackground(new java.awt.Color(0, 153, 102));
        JBNSiguienteJLS4.setFont(new java.awt.Font("Montserrat", 1, 14)); // NOI18N
        JBNSiguienteJLS4.setForeground(new java.awt.Color(255, 255, 255));
        JBNSiguienteJLS4.setText("Siguiente");
        JBNSiguienteJLS4.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(39, 174, 96), 1, true));
        JBNSiguienteJLS4.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        JBNSiguienteJLS4.setOpaque(true);
        JBNSiguienteJLS4.setPreferredSize(new java.awt.Dimension(100, 25));
        JBNSiguienteJLS4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBNSiguienteJLS4ActionPerformed(evt);
            }
        });
        getContentPane().add(JBNSiguienteJLS4, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 400, 200, 42));

        JBNSiguienteJLS3.setBackground(new java.awt.Color(0, 153, 102));
        JBNSiguienteJLS3.setFont(new java.awt.Font("Montserrat", 1, 14)); // NOI18N
        JBNSiguienteJLS3.setForeground(new java.awt.Color(255, 255, 255));
        JBNSiguienteJLS3.setText("Siguiente");
        JBNSiguienteJLS3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(39, 174, 96), 1, true));
        JBNSiguienteJLS3.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        JBNSiguienteJLS3.setOpaque(true);
        JBNSiguienteJLS3.setPreferredSize(new java.awt.Dimension(100, 25));
        JBNSiguienteJLS3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBNSiguienteJLS3ActionPerformed(evt);
            }
        });
        getContentPane().add(JBNSiguienteJLS3, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 270, 200, 42));

        JBNSiguienteJLS2.setBackground(new java.awt.Color(0, 153, 102));
        JBNSiguienteJLS2.setFont(new java.awt.Font("Montserrat", 1, 14)); // NOI18N
        JBNSiguienteJLS2.setForeground(new java.awt.Color(255, 255, 255));
        JBNSiguienteJLS2.setText("Siguiente");
        JBNSiguienteJLS2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(39, 174, 96), 1, true));
        JBNSiguienteJLS2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        JBNSiguienteJLS2.setOpaque(true);
        JBNSiguienteJLS2.setPreferredSize(new java.awt.Dimension(100, 25));
        JBNSiguienteJLS2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBNSiguienteJLS2ActionPerformed(evt);
            }
        });
        getContentPane().add(JBNSiguienteJLS2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 140, 200, 42));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JBNCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBNCancelarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JBNCancelarActionPerformed

    private void JBNSiguienteJLS4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBNSiguienteJLS4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JBNSiguienteJLS4ActionPerformed

    private void JBNSiguienteJLS3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBNSiguienteJLS3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JBNSiguienteJLS3ActionPerformed

    private void JBNSiguienteJLS2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBNSiguienteJLS2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JBNSiguienteJLS2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MisTickets.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MisTickets.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MisTickets.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MisTickets.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MisTickets().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton JBNCancelar;
    public javax.swing.JButton JBNSiguienteJLS2;
    public javax.swing.JButton JBNSiguienteJLS3;
    public javax.swing.JButton JBNSiguienteJLS4;
    public javax.swing.JComboBox<String> JCBTicketsA;
    public javax.swing.JComboBox<String> JCBTicketsP;
    public javax.swing.JComboBox<String> JCBTicketsR;
    public javax.swing.JLabel JLBMisTickets;
    // End of variables declaration//GEN-END:variables
}
